### ISSUE TITLE
version number for new release

### ISSUE THREAD

**Issue by patkan** [python-escpos/python-escpos#103]
I plan to do a release with all our fixes in the near future.

Which version number should we use?
The last version number here is `1.0.9` in order to avoid confusion with https://pypi.python.org/pypi/python-escpos/1.0.10 we should at least take something bigger than `1.0.10`.

I would take `1.1.0` since we had quite a lot of changes. I think incrementing the major version is unnecessary since I am not aware of any API changes that break behaviour.

What do you think?

**Comment by patkan** [comment]
As further input, a guide on semantic versioning: http://semver.org/

**Comment by braveheuel** [comment]
This sounds ok to me! I haven't seen API changes as well.

**Comment by patkan** [comment]
OK, so I will tag v1.1.0 when we release.
