### ISSUE TITLE
Test on Windows platform

### ISSUE THREAD

**Issue by patkan** [python-escpos/python-escpos#108]
We should probably test on a Windows system too, apart from travis. Maybe appveyor is a suitable choice.

**Comment by boelle** [comment]
will we not need some windows drivers for these old printers to test them?

**Comment by patkan** [comment]
I am still not sure, whether testing on windows is needed at all.
I assume that speaking to the printer would be handled somewhere in e.g. libusb, but I don't really know.
My intention was to be as platform-independant as possible.

**Comment by boelle** [comment]
i guess that would mean building a driver etc.... a nightmare i guess

**Comment by patkan** [comment]
In theory, everything is in place in ec454d1ca42d3da0f9a4d9cd01afa14919b41862.
In practice installing the testing dependencies does not work out of the box and I currently do not have the time to debug this.

Since the outcome is rather low and the work rather high, I am dropping this for v3. If anybody is interested in implementing this integration, feel free to pick it up.

**Comment by patkan** [comment]
fixed with #342
