### ISSUE TITLE
make Contributing-information more precise, supply code style guidelines

### ISSUE THREAD

**Issue by patkan** [python-escpos/python-escpos#114]
The current contributing.rst is not that useful.

**Comment by mike42** [comment]
Suggestion for #122: GitHub has a new repo setting called "Only allow squash commits" ([link](https://github.com/blog/2141-squash-your-commits)). It looks like this can create a single commit based off `development` each time a pull request is made, without any extra effort from developers.

If a linear history is the goal, then this should be enabled and used in place of the line requesting a `rebase` in the developer guide IMHO.

**Comment by patkan** [comment]
I have seen that. However, squashing the commits creates one single feature commit, that is sometimes a bit too compressed (imho).

You are right, the guide is somewhat contradictory. The ideal pull request would contain imho logically grouped commits and would then be merged as a non-fast-forward-merge.

Maybe we should discuss first, how the proper workflow for commiting should be. Then it is easier to put it into a guide.
Do you think the current workflow should be changed? I'm always open for improvements.

**Comment by patkan** [comment]
And another thing to dicuss is: do we need a development-branch. We have it now, because refactoring the code was a large task and then more and more PRs came, but maybe we should switch to a "PRs against master"-workflow.

**Comment by mike42** [comment]
Maybe it could be re-phrased to give `master` some purpose (eg. latest tag), and suggest an interactive rebase for improving the clarity of a pull request where necessary.

> Git
> ^^^
> The master branch contains code that has been released to PyPi. Issues are closed
> when they have been resolved in a released version of the package.
> 
> When you have a change to make, begin by creating a new branch from the HEAD of `python-escpos/development`. Name your branch to indicate what you are trying to achieve. Good branch names might be `improve/text-handling`, `feature/enable-color-printing`.
> 
> Please try to group your commits into logical units. If you need to tidy up your branch, you can make use of a git feature called an 'interactive rebase' before making a pull request. A small, self-contained change-set is easier to review, and improves the chance of your code being merged.
