### ISSUE TITLE
Network printer is not working

### ISSUE THREAD

**Issue by imuneer** [python-escpos/python-escpos#142]
I have:
- [done ] searched open and closed issues for duplicates

### Bug description
I am trying to connect my Epson UB-E03 printer through network. I can not get it work. Although it works with the USB connection by supplying the vendorid and productid.

### Steps to reproduce
- My printer IP is 192.168.123.4 (assigned by DHCP). I can access the printer webpage and ping using the mentioned IP
- from escpos import *
- Epson = printer.Network("192.168.123.4")
- Epson.text("Hello World\n")

I can not see any action in the printer.

### Device info

 **Printer:** EPSON TM-T20II (UB-E03)

 **python-escpos version:** v2.0.0.0

 **operating system:** Fedora/Centos

**Comment by patkan** [comment]
Thank you for your ticket. Do you now of any version of python-escpos or similar libraries with which it does work?

**Comment by imuneer** [comment]
No. I am only using python-escpos. This is the first time I am trying with such printer and this library. As I mentioned, USB connection works perfectly using the same library. But Network not.

_Note:_
Above mentioned printer model no is of the chipset/board. The printers Model is **TM-T20II**

**Comment by patkan** [comment]
That's difficult. @python-escpos/dev does anyone here have such a printer or a network-model at all?

**Comment by imuneer** [comment]
I was able to sort it out. The issue was not with the code. It was with the printer/network. I was able to trouble shoot by sending raw text to printer using netcat.
**Ex:** 
`echo "OK" | nc 192.168.123.4 9100`

That didn't work even. Resetting the printer interface, did it.

**Comment by patkan** [comment]
OK, thanks for the feedback. I will add a troubleshooting tip to the documentation.
