### ISSUE TITLE
Read raw data

### ISSUE THREAD

**Issue by yellow1979** [python-escpos/python-escpos#145]
Hello,
I can send raw data to my Custom VKP80 printer with the command _raw().
Is there a way to read binary data?

**Comment by DavisGoglin** [comment]
That looks like a pretty cool printer. 

We don't have a lot in the API for getting information yet, but you can access the connection property directly. It's usually named `device`, but depends on what kind of connection you made. You can see that property assigned in each `__init__` [here](https://github.com/python-escpos/python-escpos/blob/master/src/escpos/printer.py). 

There is a couple lines for reading status commands over at #143.

**Comment by prochac** [comment]
Hi,
i have similiar wish.
I'm using Custom TG1260H printer and had a issue with CUT. Solution: _raw('\x1c\xc0\x34')
Now i need read paper status.
If you want, i can provide documentation for TG1260H, TG2460H, TG2480H, TL60 and TL80 printers
HAND

**Comment by patkan** [comment]
This will be closed in favor of #143 (it basically describes the same issue)
