### ISSUE TITLE
Experience with thermal printer 8250?

### ISSUE THREAD

**Issue by mattbue** [python-escpos/python-escpos#150]
Hi,

i have a thermal printer ZJ-8250 /POS-8250 from ebay.
I'm trying to print using Raspbian on a Raspberry Pi 3, without success.

Does someone has any experience using this printer?

I will post some more information later when i'm back home.

Thanks
matt

**Comment by patkan** [comment]
Hi matt,
I have no such printer, maybe someone else.
What exactly is not working? Which interface do you use? Are you unable to connect or does the printer simply not print?

**Comment by patkan** [comment]
@mattbue Do you have more information?
