### ISSUE TITLE
Printer not parsing ESCPOS from python correctly

### ISSUE THREAD

**Issue by mashedkeyboard** [python-escpos/python-escpos#160]
I have:
- [x] searched open and closed issues for duplicates

### Bug description
My printer doesn't seem to be accepting the ESCPOS commands being sent by python-escpos in the correct manner. Don't get me wrong, it seems to be having a valiant go at it, but it's not making much headway. For instance, `Epson.barcode('1324354657687','EAN13',64,2,'','')` prints `aw1324354657687` on the printer, and any of the `.set()` commands simply make the text tiny and occasionally miss some letters. It's a bit of a weird one - any ideas?

### Device info

 **Printer:** [Generic 58mm Thermal Reciept Printer POS-5890K](http://www.banggood.com/POS-5890K-58mm-Thermal-Receipt-Printer-Support-WIndows-Linux-p-1053549.html?p=ZK20011801823201506V) set up on `/dev/usb/lpt0`

 **python-escpos version:** 2.1.3

 **python version:** 3.4.2

 **operating system:** Raspbian Jessie Lite

**Comment by mashedkeyboard** [comment]
_Update:_ Barcodes don't seem to be supported by this printer, as `cat [barcode.bin](https://python-escpos.readthedocs.io/en/latest/_downloads/barcode.bin) > /dev/usb/lp0` doesn't print the barcodes either. However, that file does print the headers correctly - something that python-escpos refuses to do, seemingly. The plot thickens!

Also, I have reproduced this behaviour with `printer.Usb` as well as `printer.File` with the 5890K.

**Comment by mike42** [comment]
Hey, the barcode binary blob is test data from mike42/escpos-php - this should explain why the output is different to the python-escpos output.

You would need to render a barcode to an image via a software library and send it as a "bit image" for printers from this manufacturer (not many commands are available natively).

**Comment by mashedkeyboard** [comment]
Hi @mike42, thanks - appreciated! - but the barcodes aren't the main issue really, it's the fact that I can't set text sizes, print images or do anything really other than print plain text - it simply results in a giant undecipherable mess of seemingly random characters being printed with images, or text becoming smaller and occasional letters disappearing with the .set command.

**Comment by patkan** [comment]
Hi @mashedkeyboard could you maybe post a minimal working example for printing something with formatting?
Although the usability of set is currently not that good, it should work.
Do you have a link to the printers manual?

**Comment by mashedkeyboard** [comment]
Heya @patkan,

The printer manual is [here](http://www.zjiang.com/cn/TechnicalSupport/2016/0226/243.html). I've actually managed to make set work now (I was using the wrong syntax), but the images still won't work. The printer can definitely print images, as I was successful in printing one using the printer's Windows driver as part of a test print.

Any ideas?

**Comment by mashedkeyboard** [comment]
`p.control("CR")` doesn't work either - for instance, the script

```
from escpos import *
p = printer.Usb(0x0416,0x5011)
p.text("Hello,")
p.control("CR")
p.text("Curtis")
p.cut()
```
actually outputted `ello,tis` exactly like that (no carriage return whatsoever).

And now my desk is full of tiny sheets of thermal paper!

**Comment by patkan** [comment]
Yeah, the syntax is not really beautiful. That one has to change in a future update.

Have you already tried all three image-implementations? (Parameter `impl` in [image-method](https://github.com/python-escpos/python-escpos/blob/master/src/escpos/escpos.py#L59).
Also, please make sure that you are starting your image on a newline (e.g. by issuing a `p.text("\n")`) before the image.

If that is not working, you could try v2.1.2. I changed image-printing slightly in the last bugfix-release. That should not affect anything, but maybe I introduced a defect.

For the carriage return: maybe try to use the text-function with escpae-sequences like `\n`. (`\n` as text definitely works on epson-printers)

**Comment by mashedkeyboard** [comment]
Tested the implementations, `bitImageColumn` is the only one that works - but it leaves arbitrary output (in one instance, the number 3, in another a load of random characters) in front of the image for some reason?

`p.text("Hello,\nCurtis")` gives me

```
ello,
Curtis
```

Closer, but not quite >.<

**Comment by mashedkeyboard** [comment]
@patkan in response to your update, I ran this code:

```
from escpos import *
p = printer.Usb(0x0416,0x5011)
p.text("Test")
p.control("LF")
p.text("Test2")
p.control("CR")
p.text("Test3")
p.cut()
```

That printed `Test` and then nothing. Erm... help? That makes no sense!

**Comment by mike42** [comment]
Hey, I've got a similar-ish printer, ZJ 5890T. Reading this thread, I still don't know what your use case is though.

Can you please post an example of what type of output you want, how you're trying to achieve it (code) and a picture of what you get instead?

This would make it possible to see whether its a problem with expectations, printer support, library support, or the snippet itself.

**Comment by mashedkeyboard** [comment]
Hi @mike42,

The actual use case is a little project I'm working on called [Dashday](https://github.com/mashedkeyboard/Dashday) (yes the code is awful, but it works - it's very much a 'screw it, it'll do for now' job). Running main.py in there with the weather and news plugins enabled, I get [this beautiful mess](https://mashedkeyboard.me/work/dashday/brokenprint.png) out from the printer.

I was rather hoping for it to print the "Hello" bit in bold and in large font, as the code tells it to. Under that there should be a weather image, but that's turned out an absolute mess of characters (albeit the case that that can be explained away by the fact I'm not using `bitImageColumn` for that at the moment). There should be carriage returns around the headers (both above and below) which clearly isn't happening, and there should also be carriage returns between the news story headlines and the news content on the news feed, which doesn't happen either. The news headlines should be in bold, too, which they are not in the print.

**Comment by mike42** [comment]
I've ported an example from this project's PHP sibling which includes a similar set of features (images, some basic formatting, and line breaks). Maybe you can start by printing it and then refactoring it to meet your needs? The picture below is output from a ZJ 5890T.

Note that the command for "bold" that we send here appears to be ignored by this printer, but will work on other ESC/POS printers. I haven't dug into it, but double-width is a good substitute that should get you on track.

Image:

![2016-08-zj5890t-example](https://cloud.githubusercontent.com/assets/2080552/17929615/e98e3c5a-6a44-11e6-87e5-63a621efb62f.png)

Code:

```python
#!/usr/bin/env python
from escpos import printer

# A wrapper to organise item names & prices into columns
class item:
    def __init__(self, name="", price="", dollarSign=False):
        self.name=name
        self.price=price
        self.dollarSign=dollarSign

    def encode(self):
        rightCols = 6
        leftCols = 24
        if(self.dollarSign):
            leftCols = leftCols / 2 - rightCols / 2
        left = self.name.ljust(leftCols)
        sign = "$" if self.dollarSign else ""
        right = (sign + self.price).rjust(rightCols)
        return (left + right + "\n").encode()

# Information for the receipt
items = [
    item(name="Example item #1", price="4.00"),
    item(name="Another thing", price="3.50"),
    item(name="Something else", price="1.00"),
    item(name="A final item", price="4.45")
]
subtotal = item(name="Subtotal", price="12.95")
tax = item(name="A local tax", price="1.30");
total = item(name="Total", price="14.25", dollarSign=True);

# Date is kept the same for testing
date = "Monday 6th of April 2015 02:56:25 PM";

# Start the printer
p = printer.File("/dev/usb/lp0")

# Print top logo
p.set(align="center")
p.image("escpos-php.png", impl="bitImageColumn")

# Name of shop
p.set(align="center", width=2)
p.text("ExampleMart Ltd.\n");
p.set(align="center")
p.text("Shop No. 42.\n")
p.text("\n")

# Title of receipt
p.set(align="center", text_type="B")
p.text("SALES INVOICE\n");

# Items
p.set(align="left", text_type="B")
p.text(item(name="", price="$"));
p.set(align="left")
for item in items:
    p.text(item);
p.set(text_type="B")
p.text(subtotal);
p.text("\n")

# Tax and total
p.set()
p.text(tax);
p.set(width=2);
p.text(total);

# Footer
p.text("\n\n")
p.set(align="center")
p.text("Thank you for shopping at\nExampleMart.\n");
p.text("For trading hours, please visit example.com\n");
p.text("\n\n")
p.text(date + "\n");

# Cut the paper
p.cut()
```

Binary blob: [receipt-with-logo-zj5890t-pythonescpos.zip](https://github.com/python-escpos/python-escpos/files/434613/receipt-with-logo-zj5890t-pythonescpos.zip)

**Comment by mashedkeyboard** [comment]
Hi @mike42, I'm just waiting for a shipment of thermal rolls for the printer to come through as my current lot has run out. Will update when I recieve & test :)

**Comment by mashedkeyboard** [comment]
@mike42, the printer rolls have just arrived, and I can confirm that your test works. My syntax must be wrong - I'll close this issue and go over my code. Thanks for the help :)

**Comment by blutme** [comment]
> Hey,
> 
> I've just ported an example from this project's PHP sibling which includes a similar set of features (images, some basic formatting, and line breaks). Maybe you can start by printing this, then refactoring to match your expected output? The picture below is output from a ZJ 5890T.
> 
> Note that the command for "bold" that we send here appears to be ignored by this printer, but will work on other ESC/POS printers. I haven't dug into it, but double-width is a good substitute that should get you on track.
> 
> Image:
> 
> ![2016-08-zj5890t-example](https://cloud.githubusercontent.com/assets/2080552/17929615/e98e3c5a-6a44-11e6-87e5-63a621efb62f.png)
> 
> Code:
> 
> ```python
> #!/usr/bin/env python
> from escpos import printer
> 
> # A wrapper to organise item names & prices into columns
> class item:
>     def __init__(self, name="", price="", dollarSign=False):
>         self.name=name
>         self.price=price
>         self.dollarSign=dollarSign
> 
>     def encode(self):
>         rightCols = 6
>         leftCols = 24
>         if(self.dollarSign):
>             leftCols = leftCols / 2 - rightCols / 2
>         left = self.name.ljust(leftCols)
>         sign = "$" if self.dollarSign else ""
>         right = (sign + self.price).rjust(rightCols)
>         return (left + right + "\n").encode()
> 
> # Information for the receipt
> items = [
>     item(name="Example item #1", price="4.00"),
>     item(name="Another thing", price="3.50"),
>     item(name="Something else", price="1.00"),
>     item(name="A final item", price="4.45")
> ]
> subtotal = item(name="Subtotal", price="12.95")
> tax = item(name="A local tax", price="1.30");
> total = item(name="Total", price="14.25", dollarSign=True);
> 
> # Date is kept the same for testing
> date = "Monday 6th of April 2015 02:56:25 PM";
> 
> # Start the printer
> p = printer.File("/dev/usb/lp0")
> 
> # Print top logo
> p.set(align="center")
> p.image("escpos-php.png", impl="bitImageColumn")
> 
> # Name of shop
> p.set(align="center", width=2)
> p.text("ExampleMart Ltd.\n");
> p.set(align="center")
> p.text("Shop No. 42.\n")
> p.text("\n")
> 
> # Title of receipt
> p.set(align="center", text_type="B")
> p.text("SALES INVOICE\n");
> 
> # Items
> p.set(align="left", text_type="B")
> p.text(item(name="", price="$"));
> p.set(align="left")
> for item in items:
>     p.text(item);
> p.set(text_type="B")
> p.text(subtotal);
> p.text("\n")
> 
> # Tax and total
> p.set()
> p.text(tax);
> p.set(width=2);
> p.text(total);
> 
> # Footer
> p.text("\n\n")
> p.set(align="center")
> p.text("Thank you for shopping at\nExampleMart.\n");
> p.text("For trading hours, please visit example.com\n");
> p.text("\n\n")
> p.text(date + "\n");
> 
> # Cut the paper
> p.cut()
> ```
> 
> Binary blob: [receipt-with-logo-zj5890t-pythonescpos.zip](https://github.com/python-escpos/python-escpos/files/434613/receipt-with-logo-zj5890t-pythonescpos.zip)

for python 3.7+ and 3nStar RPT008 THERMAL PRINTER:

you must add usb library:

`from escpos.printer import Usb`

and change the line 38 for this:

`p = Usb(0x1fc9, 0x2016, 0)`  “Vendor ID” and “Product ID”, you found with: >lsusb

and 16 for this:

`            leftCols = leftCols / 2 - rightCols / 2    `
`            leftCols = int(leftCols) `
