### ISSUE TITLE
Corrections for direct printer firmware typeface flags

### ISSUE THREAD

**Issue by GoogleCodeExporter** [python-escpos/python-escpos#18]
```
What steps will reproduce the problem?

1. Epson.set('center','A','NORMAL',2,2)

   ( The typeface is tall and not wide;
     double width and height is a single 0x30 flag,
     not 0x10 and 0x20 in sequence;
     0x20 ends up cancelling 0x10. )

2. Epson.set('center','U2','NORMAL',2,2)

   ( a stale constant for turning off Italic remains;
     this is not defined in constants.py; therefore,
     delete this line )



What is the expected output? What do you see instead?

1. For text that should be quad area, I see
   Text that is tall, and not wide

2. For normal weight with strong underline,
   I see A NameError:

>>> Epson.set('center','A','U2',2,2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/escpos/escpos.py", line 206, in set
    self._raw(TXT_ITALIC_OFF)
NameError: global name 'TXT_ITALIC_OFF' is not defined



What version of the product are you using? On what operating system?

$ hg summary
parent: 12:849dabb63ce0 tip
 Added syntax to have print working on windows
branch: default
commit: 2 modified, 5 unknown
update: (current)

$ uname -imrs 
FreeBSD 9.2-RELEASE i386 GENERIC



Please provide any additional information below.

  diff attached in hg-diff-escpos.txt;

  constants.py:
    1. I have introduced a suggested fix for quad area characters,
    in the form of a new constant, "TXT_4SQUARE".

  escpos.py:
    1. For quad-area characters, reset to normal first,
    then send only one flag to activate double width and height.

    2. The deprecated constant, "TXT_ITALIC_OFF", is removed.

This was verified on an Epson TM-H6000, IEE-1284 (parallel)
  Epson = printer.File("/dev/lpt0")


Thank you for this library. I look forward to extending it
if I am able to.

Thanks as well to the developers of Mercurial;
an R.C.S that works, just as the developers intended.
```

Original issue reported on code.google.com by `syncma...@gmail.com` on 10 Dec 2013 at 4:03

Attachments:
* [hg-diff-escpos.txt](https://storage.googleapis.com/google-code-attachments/python-escpos/issue-18/comment-0/hg-diff-escpos.txt)

**Comment by patkan** [comment]
main issue should already be fixed in master

**Comment by Davnc988** [comment]
Hello, 

First of all thank you for the hexadecimal commands they have been helpful. However, I'm encountering an issue with slip mode printing. I would like users of my application to be able to print checks. However, I can't seem to rotate the content for printing from top to bottom. I used the command "0x1B,0x54,0x03," but it doesn't seem to work.

Any ideas ? 

``const command = {
    SET_PRINT_ROLL:[0x1B,0x63,0x30,0x03],
    SET_PRINT_SLIP:[0x1B,0x63,0x30,0x04],
    PAPER_SLIP_OUT:[0x1B,0x4B,0xC0],
    ALIGN_RIGHT:[0x1B,0x61,0x02],
    SET_VERTICAL_PRINT:[0x1B,0x54,0x03],
}

const connectSlip = async () =>{
    console.log('ok')

    //connexion to slip mode
    await new Promise((resolve) => {
        serialPort.write(command.SET_PRINT_SLIP, resolve);
    });

    //align the text to the right
    await new Promise((resolve) => {
        serialPort.write(command.ALIGN_RIGHT, resolve);
    });

    //active the page mode
    await new Promise((resolve) => {
        serialPort.write([0x1B,0x4C], resolve);
    });

    //rotate the text
    await new Promise((resolve) => {
        serialPort.write(command.SET_VERTICAL_PRINT, resolve);
    });

    //send the message to print
    await new Promise((resolve) => {
        serialPort.write('Hello', resolve);
    });

    //throw the paper out
    await new Promise((resolve) => {
        serialPort.write(command.PAPER_SLIP_OUT, resolve);
    });

    //send back to the receipt mode
    await new Promise((resolve) => {
        serialPort.write(command.SET_PRINT_ROLL, resolve);
    });
}
``
