### ISSUE TITLE
Need method for multiple linefeed

### ISSUE THREAD

**Issue by ethangoldstein** [python-escpos/python-escpos#183]
Would be convenient to have a method in the class which takes the number of lines, and then feeds that number of lines. Currently, i am using an ugly function which wraps around my already invoked object.

**Comment by mike42** [comment]
Great suggestion.

We should use the proper ESC/POS for it. I've [previously implemented](https://github.com/mike42/escpos-php/blob/6e9eeecc00ae4e307fb46b6bb32dbfdd47b61ae2/src/Mike42/Escpos/Printer.php#L524) multi-line fed with the `ESC d` command.

**Comment by patkan** [comment]
fixed in abbe32f845d9d1431f066a14087fbd29fd1982da
