### ISSUE TITLE
Changing QR code properties

### ISSUE THREAD

**Issue by ethangoldstein** [python-escpos/python-escpos#184]
Would be convenient if the QR code properties could be changed, such as higher error correction or image scaling.

**Comment by mike42** [comment]
The feature you are requesting already exists!

Please check out the [documented](http://python-escpos.readthedocs.io/en/development/api/escpos.html#escpos.escpos.Escpos.qr) `ec` and `size` options to the `qr()` method.

There is a page in the documentation which doesn't mention everything, so the API guide is your best source once you've got the basics worked out.

**Comment by ethangoldstein** [comment]
Awesome! Thanks!
