### ISSUE TITLE
Update documentation on installation (especially on Raspi)

### ISSUE THREAD

**Issue by FahmiG** [python-escpos/python-escpos#185]
I have:
- [x] searched open and closed issues for duplicates

I have follow  Raspberry Pi installation process in the user documentation.

When I try to run the example code, I'm getting this error:

```
File "/usr/local/lib/python3.4/dist-packages/python_escpos-2.2.1.dev67_ng46305fa-py3.4.egg/escpos/capabilities.py", line 8, in <module>
    with open(path.join(path.dirname(__file__), 'capabilities.json')) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.4/dist-packages/python_escpos-2.2.1.dev67_ng46305fa-py3.4.egg/escpos/capabilities.json'
```

How can I solve this error?
### Device info

 **python-escpos version:** 2.2.1

 **python version:** 3.4

 **operating system:** Raspbian Jessie

**Comment by patkan** [comment]
Thank you for the issue! Am I right, that you have followed the description exactly? So you haven't used `git clone --recursive`?
Then probably you are missing the submodule. Please let me know if I am right.
(The description is unfortunately a bit old and has to be reworked.)

**Comment by FahmiG** [comment]
Yes, I haven't used  `git clone --recursive`

Now everything is working fine.

Thank you very much.

**Comment by patkan** [comment]
Thank you. I will leave this open as a reminder that we have to clean this part of the documentation.

**Comment by an0key** [comment]
+1, needs the --recursive

Just spent a few hours, until I got to this bug... resolved and working as expected now.

**Comment by patkan** [comment]
The development documentation has already been updated. The problem was that the default branch shown in readthedocs is the master.
I have updated the pointers in readthedocs and will add a commit that improves the part on raspi.
