### ISSUE TITLE
missing capabilities.json

### ISSUE THREAD

**Issue by andrecastro0o** [python-escpos/python-escpos#186]
I have:
- [x ] searched open and closed issues for duplicates

### Bug description
I wanted to study the pytho-escpos code and add the possibilities to have margins, so I installed the library for development.
However I was confronted with **a missing file python-escpos/src/escpos/capabilities.json**

`ls -l src/escpos` show:
`capabilities.json -> ../../capabilities-data/dist/capabilities.json`
 `../../capabilities-data/dist/` is empty

When I installed it using pip. It ran fine!

### Steps to reproduce
- installation: `python setup.py develop --user` 
- run w/out errors: `import escpos`   
- run: `from escpos.printer import Usb` 
- `IOError: [Errno 2]  No such file or directory: '/home/path/to/local/python-escpos/src/escpos/capabilities.json'

### Device info

 **Printer:** Epson Lx300

 **python-escpos version:**  latest source

 **python version:** 2.7

 **operating system:** Debian: GNU/Linux

**Comment by patkan** [comment]
I am sorry the documentation on that part is lacking. Could you please try if you are succesfull after doing `git submodule init` and then `git submodule update`?

**Comment by andrecastro0o** [comment]
It did the trick :) thanks a lot @patkan 
Great lib, BTW
