### ISSUE TITLE
escpos and cx_freeze

### ISSUE THREAD

**Issue by sergegauthier** [python-escpos/python-escpos#195]
I am using ecspos to print label on PR4 printer and it works fine. I use python3.4 with pydev. I can print what I need correctly when I run my program from the source code.

To run the program on the computer of my friend I send it, I use cx_freeze to compile it and so it's not necessary to install all things on his computer.

My problem is when I build it including printer from ecspos the executable file gives me a error:

"SyntaxError: Non-UTF-8 code starting with '\xc3' in file on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details"

and I am not able to find where is this error.

Could you give me some help ?

Thanks a lot, regards

**Comment by sergegauthier** [comment]
Hi,

Thanks for helping me.

Attached the small test file testEcs.py. It's running well with python3 
testEcs.py command. It prints 2 lines.

I give you the cx_freeze file setup.py. To build run python3 setup.py build.

In the build/exe.linux... you will find the executable file testEcs.

Try to run it with python3 testEcs to see the error message.

Regards

**Comment by sergegauthier** [comment]
Tell me if the joined files are not avalaible.

Thanks

**Comment by patkan** [comment]
Unfortunately you are right, the files are missing. You can add them maybe here by dragging them into the window or just write me a mail to dev[at]pkanzler.de
Thanks!

**Comment by patkan** [comment]
Sorry, I can't test it at the moment, because I run into this bug: https://bitbucket.org/anthony_tuininga/cx_freeze/issues/209/no-module-named-__startup__
Whatever I tried I couldn't resolve it. Maybe someone else can help or I can have a look at it when there is a fix or workaround available.

**Comment by patkan** [comment]
Just as a heads-up: The bug that I encountered is tracked in anthony-tuininga/cx_Freeze#209 and I subscribed to it. As soon as it is resolved I will try your code again.
@sergegauthier Please tell me if you were successful in the meantime.

**Comment by sergegauthier** [comment]
Hi,

Thanks a lot.

Using a older version of cx_freeze it is possible to run my program. 
With cx_freeze 5, there is significant segmentation errors. That's the 
problem. But, I will use the python files directly to avoid this type of 
problem in the future...

Thanks for your help.

**Comment by patkan** [comment]
So this problem is resolved for you? We can close the issue?

**Comment by sergegauthier** [comment]
yes for the moment

Thanks

**Comment by patkan** [comment]
OK, thanks for the feedback, just reopen it when you need to.
