### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by thijstriemstra** [python-escpos/python-escpos#197]
I'd like to be able to use the changes in master with a pip install -U.

**Comment by patkan** [comment]
Youy

**Comment by patkan** [comment]
You probably mean the branch `development`?
The problem is that some.of these changes in there break compatibility and we would like to have done some refactoring before we release a new major version. But basically you are right, we should try to get the refactoring done and then release.

**Comment by thijstriemstra** [comment]
@patkan tried to add python 3.6 builder (which is stable now) but was confused by the python 3.5 dev stuff, maybe you can also check that out.

**Comment by patkan** [comment]
The alpha release is out. We can get the changes gradually out by just doing some alphas. That way people can already test the new features and find bugs. :-)
