### ISSUE TITLE
Dapper-Geyi Q583P + capabilities database

### ISSUE THREAD

**Issue by globalcitizen** [python-escpos/python-escpos#206]
I have:
- [x] searched open and closed issues for duplicates

### Steps to reproduce
- Attempt to use device with [mike42/escpos-php](https://github.com/mike42/escpos-php/)
- Discover device limitations
- Report need to extend/reconsider capabilities database
  - Recommendation: "Add reverse feed supported?"
  - Recommendation: Reconsider/remove column width calculation as a feature
  - Recommendation: Add method to old/custom/alternative full-cut command sequence (eg. `ESC i`)
  - Recommendation: A "how much extra feed to execute before a cut" setting should be possible to associate with a device
  - Problem: column counts do not work well with some systems, or with `ESC V <n>`
- Directed here due to capabilities database being shared

### Device info

 **Printer:** Dapper-Geyi Q583P

 **python-escpos version:** N/A

 **operating system:** Linux

### Problems

See mike42/escpos-php#296

**Comment by patkan** [comment]
Hi @globalcitizen, thank you for the issue.
I think @mike42 meant the [escpos-printer-db](https://github.com/receipt-print-hq/escpos-printer-db).
As soon as the capabilities are in the db we can of course work on extending python-escpos.

**Comment by patkan** [comment]
I will close this now. As soon as escpos-printer-db has been extended we can reopen this.
