### ISSUE TITLE
Works fine on OS X 10.10.5 with USB IEEE-1284 Controller and TM-T88III

### ISSUE THREAD

**Issue by aokolovskis** [python-escpos/python-escpos#207]
Hi guys, 

just wanted to provide some positive feedback and ask if some guideline is appreciated how to get it running on a mac? 

Regards,
Alex

**Comment by patkan** [comment]
Thank you for the feedback!
Definitely, yes. If you want to, you could try to add the information to https://github.com/python-escpos/python-escpos/blob/development/doc/user/installation.rst.
It is currently very Linux-centric, but feel free to rewrite this part if needed.

**Comment by patkan** [comment]
Hi @aokolovskis you could also just write up a small howto and put it here ;-)

**Comment by patkan** [comment]
I am closing this now.
