### ISSUE TITLE
“text()”   Can I increase control over text formatting?

### ISSUE THREAD

**Issue by 494895913** [python-escpos/python-escpos#210]
my code:

from escpos.printer import Usb

p = Usb(0x04b8,0x0202)

p.codepage  = "gb2312"

p.text("你好")     # this is text1

p.text("你好，世界") # this is text2

p.cut()

I want text1 to have a different font format than text2

**Comment by 494895913** [comment]
I think I solved my problem   This is an example of the solution：

from escps.escpos import EscposIO

from escps.printer import Usb

with EscposIO(Usb(0x04b8,0x0202)) as p:

p .writelines("hello",width=1,height=1)

p.writelines("hello workd",width=2,height=2)

But I have a new question，I entered the Chinese when the garbled

**Comment by patkan** [comment]
Yes, this is a possible solution. Otherwise you can just manipulate the formatting with the `set()`-function.

Proper printing of chinese characters is a bit more difficult, see issue #190. It is however difficult for me to help there since I don't have a printer that supports the codepage.

**Comment by patkan** [comment]
The original issue is solved
