### ISSUE TITLE
Cut paper without feeding it

### ISSUE THREAD

**Issue by boardnick0815** [python-escpos/python-escpos#213]
Hello alltogether,

currently i'm facing a problem with the .cut()-function.
I would like to achieve a cut of the paper without feeding, so i do not have approx. 4 lines at the top of each next sheet.

Inside of  _python-escpos/src/escpos/constants.py_ between lines 54-57 i can see the esc sequence for full and partial cut but i do not find any code for cutting without feeding.

So i tried to send raw data (GS V 66 0) to the printer, but i got _AttributeError: 'Usb' object has no attribute 'raw'_.

(How) is it possible to make a cut at the end one "sheet" without having blank lines on the top of the next sheet?

Due to the fact that i'm not a (good) programmer i apologize for this maybe stupid question...

Best regards!

I have:
- [x] searched open and closed issues for duplicates

### Device info

 **Controler:** Epson BA-T500II USB
 **Printer:** M-T522AF II

 **python-escpos version:** 2.2.0

 **python version:** 3.4.2

 **operating system:** Raspbian GNU/Linux 8 (jessie)

**Comment by patkan** [comment]
Hi @boardnick0815,
thank you for your issue. In the long term this would need to be implemented. If you want to, you can create a PR for this. Best you would extend `cut()` with an additional parameter.

For now you should be able to send the command just with raw. Just be aware that you have to call `._raw()` (with underscore, this function normally is not intended for external use, but should be fine).

Some example code could be
```python
from escpos.constants import GS
from escpos.printer import Usb
import six

p = Usb()  # insert proper initialization here
p._raw(GS + b'V' + six.int2byte(66) + b'\x00')
```

**Comment by boardnick0815** [comment]
Hi @patkan,

thank you very much for your fast response!
Sending a _cut without feeding_ as raw data with `p._raw(GS + b'V' + six.int2byte(66) + b'\x00')` works perfectly with the Epson BA-T500II USB board.

Now i maybe have also a way to print pdf417 codes using escape sequences - you made me happy :-)

If i would have the skills to create a PR i would do so - maybe after some more practising python...

Have a nice day and thanks again!

**Comment by patkan** [comment]
You're welcome.
If you have any questions considering PRs, feel free to ask. Apart from that if you have worked out a good sequence, it also helps to create an issue with the sequence and describing the printer that it works with.
