### ISSUE TITLE
Image-too-large exception

### ISSUE THREAD

**Issue by patkan** [python-escpos/python-escpos#217]
[#58](https://github.com/python-escpos/python-escpos/issues/58#issuecomment-301299018) suggests that in WinBond/Zjiang 5890 images over a certain size will cause the print to fail.
For this case implementing an extra check with a new exception would be useful.
https://github.com/receipt-print-hq/escpos-printer-db could supply a property for maximum image size.
(#58)

**Comment by patkan** [comment]
@MicroJoe This is fixed by #226, isn't it?

**Comment by MicroJoe** [comment]
Yes (given that the ZJ5890 has a proper yml definition with pixel width)
