### ISSUE TITLE
Barcode software printing

### ISSUE THREAD

**Issue by patkan** [python-escpos/python-escpos#218]
Some printers like in #58 do not support barcode printing or only support a subset of barcodes (as the old Epson printers).

A possible enhancement would be finding a proper library for barcode-printing. ([python-barcode](https://bitbucket.org/whitie/python-barcode)?) With this barcode could be rendered in software and then printed as images.
Ideally a new capability in https://github.com/receipt-print-hq/escpos-printer-db would be used to determine whether software-rendering is needed. (See the QR-function as an example)

**Comment by icarolongo** [comment]
Anyone tried to print QR Code on POS-5890?
It uses python qrcode correctly?

**Comment by mike42** [comment]
This thread is about barcodes, not qrcodes. I tested the software qrcode
feature on a ZJ5890K (or similar) when I implemented it, please file a new
issue if you think you've found a bug or opportunity for improvement!

**Comment by MicroJoe** [comment]
Ok so #222 was merged.

I looked into the hardware barcode method for a possible merge with the software defined method. The hardware method has a lot of hardware-specific arguments such as font type, A or B barcode mode, etc..

So, the software render of barcodes is available but is not in the same method as the hardware barcode. Merging the two methods within one would using a `use_software` boolean argument is possible but needs some refactoring of the hardware method interface.

Maybe we can close this issue and create a new one if we want the two methods to be merged into one with a work on the method arguments.

**Comment by patkan** [comment]
I think the real task is splitting the library into low-level Escpos functions (or maybe also those emulating them) and highlevel "layout" functions.
Relevant issues are #176 and #96.

We would have to start with a concept and then implement it. But yeah, considering this issue I think we are done.
