### ISSUE TITLE
Exception for printer-specific unsupported features

### ISSUE THREAD

**Issue by MicroJoe** [python-escpos/python-escpos#221]
I have:
- [x] searched open and closed issues for duplicates

### Feature description

As an user, I want the library to throw me an exception if I use a specific POS printer that cannot handle some features.

For example, if I am using the WinBond/Zjiang 5890 printer that cannot handle native barcodes (see #58), as a contributor I want to write in the printer's file explicitly that this feature wont work with this printer, and as an user I want to get a FeatureNotSupportedError if I try to print native barcode on the printer.

**Comment by patkan** [comment]
While I do not want to immediately discard this idea, I just want to note the current "philosophy".

This philosophy is not yet completely implemented. But in theory you would have a capability that tells you whether the printer can handle the barcode natively or not. In the latter case we could automatically switch to software rendering. This way you can write code that is device-agnostic after specifying your device.

**Comment by MicroJoe** [comment]
Barcode support is now registered in the receipt-print-hq repository: https://github.com/receipt-print-hq/escpos-printer-db/commit/e6ad724b45914fe815fa99f5301e55278423a95e

We have now a mean to check if we should use software or hardware rendering for barcodes.

The next step is to add an if inside the `barcode` method to check if it should use software or hardware rendering. However the options are very different between the two methods so I will need someone with hardware printer support to check if both software and hardware barcodes look the same or if there are big differences.

This is going to lead to fine tuning of the software barcode defaults so that it match the hardware barcode (size of barcode, text position, ...).

**Comment by mike42** [comment]
@MicroJoe - Happy to run off test prints on a TM-T20 as well. It supports hardware barcodes and images in all formats that this library can create, so if you end up with a binary file, upload it here and I'll reply back with an image.

**Comment by MicroJoe** [comment]
@mike42 Generating and sending you binary codes looks cumbersome.

One thing you can do is fine tune the software barcode settings so that the defaults look like the hardware bar codes. You can modify the arguments of `soft_barcode` to achieve that and compare output with hardware barcodes.

This will definately help by setting up good defaults before moving on automatic software rendering if hardware is not supported.

**Comment by patkan** [comment]
How about putting together a script with software and hardware barcode alongside?
This could be a good start for tuning.

**Comment by MicroJoe** [comment]
I have created pull request for this.

Once it is merged one can run the example and tweak the default values of the software barcode method so that the size is almost the same as the hardware barcodes.

**Comment by MicroJoe** [comment]
I have created #245 that summarize barcode merge betwen software and hardware in order to continue the discussion here because the content of this issue has derived from its content.

The spirit for the question I asked is that the printer should fail if no backup worked. Since software barcodes are going to be a backup for the hardware barcodes the barcode method should not raise something like `HardwareBarcodeNotSupported`.
