### ISSUE TITLE
Convert Raw Binary to commands

### ISSUE THREAD

**Issue by AlphaWarrioR** [python-escpos/python-escpos#223]
I'm working on a project where i need to intercept data sent to an esc/pos printer, extract info and print the original reciept. 
So i have opened a port on 9100, and was able to capture a data stream.
Is there any way to convert this back into a usable format using this lib ?
Eg.: Printing it to a file / dummy printer ?

Thanks

**Comment by patkan** [comment]
Hi!
What do you mean by usable format?
The library does not contain a direct method for interpretation of escpos commands.

**Comment by mike42** [comment]
@AlphaWarrioR - Maybe relevant- I'm working on [receipt-print-hq/escpos-tools](https://github.com/receipt-print-hq/escpos-tools), which aims to produce command-line tools to work with binary ESC/POS.

We are nowhere near "usable format" stage, but the `esc2text` utility can recover ASCII from an ESC/POS stream.

**Comment by AlphaWarrioR** [comment]
@mike42 That is exactly what i'm looking for 👍 Thanks
