### ISSUE TITLE
Merge software and hardware barcodes to a same method

### ISSUE THREAD

**Issue by MicroJoe** [python-escpos/python-escpos#245]
I have:
- [x] searched open and closed issues for duplicates

### Bug description
This issue continues discussion started in #221 about barcode generation.

Currently the hardware and software barcodes are implemented in two separated methods for the sake of simplicity. However we want to merge the user call to the `barcode` method, with an optional boolean argument named `force_software=False` than allow users that have hardware barcode capabilities to force software rendering.

If your printer does not support hardware rendering according to the printer database then software barcodes are going to be used automatically.

**Comment by MicroJoe** [comment]
Issue dependency: we should close #244 before moving on the code refactoring.

As a side task one has to test and tweak the `soft_barcode` default values once #243 gets merged so that hardware and software barcodes have more or less the same size.

**Comment by belono** [comment]
Hello everybody!

I just wanted to share with you that I've been (slowly) working on this feature for a few months now and it looks like I could have a PR in a few days that should close both #244 and #245.

Stay tuned for the news ;)

**Comment by patkan** [comment]
Great, thank you!
If you want to, you could already create a PR for the draft version. Nevertheless, whether now or later, I am looking forward to you PR :)
