### ISSUE TITLE
Consider software QR code centering

### ISSUE THREAD

**Issue by MicroJoe** [python-escpos/python-escpos#248]
I have:
- [x] searched open and closed issues for duplicates

### Bug description

Software QR codes are currently left-aligned. Using the centering command before printing the software QR has no effect.

### Proposed solution
One solution is to modify the generated image in order to add left margin by deducing it from the device image width that we can access and the QR width. Something like this:

```
left_spacing = printer_width / 2 - qr_width / 2
```

We can then add white pixels on the left using Pillow.

**Comment by patkan** [comment]
What is the behavior of the hardware-QR-Codes? Are they always centered?

**Comment by MicroJoe** [comment]
I cannot test on my ZJ-5890. Maybe someone with hardware supported QRs can test and answer.

**Comment by patkan** [comment]
@mike42 Do you have a printer that is capable of native QR-code printing?

**Comment by MicroJoe** [comment]
Whoops seems that this is fixed now by #250. Closing.
