### ISSUE TITLE
Losing prints when the device will be powered down

### ISSUE THREAD

**Issue by Simonefardella** [python-escpos/python-escpos#253]
I have:
- [x] searched open and closed issues for duplicates

### Steps to reproduce
- Create a new python file, paste and adapt the lines below:
```
from escpos import printer as escpos_printer
from escpos.escpos import EscposIO
import time

with EscposIO(escpos_printer.Network(192.168.1.1, port=9100), autocut=True) as printer_socket:
    printer_socket.writelines('Test Line 1')
    time.sleep(5) #Here i'm simulating a long-running print -> Turn-off the printer
    printer_socket.writelines('Test Line 2')
    printer_socket.writelines('Test Line 3')
    printer_socket.writelines('Test Line 4')  -> Turn-on the printer
    printer_socket.writelines('Test Line 5')
```
- Try to print launching the script
- When the execution will hit the sleep line, turn-off the printer and keep it turned-off (simulating a power failure)...no exception at all.
- Turn on the printer (on the line that prints: "Test Line 4") , as you can see, the printer will not print anything, losing, in fact, everything.

### The question is:
How i can do a sort of retry if no exception will be raised? maybe i have to check for every line that i'm printing if the printer it's online? (but it's not a good solution, in my opinion...)

Thanks,

Simone.

### Device info

 **Printer:** HOIN 80mm ESC/POS (Generic printer)

 **python-escpos version:** 2.2.0

 **python version:** 3.5

 **operating system:** Ubuntu Server 16.04 LTS

**Comment by patkan** [comment]
Hi @Simonefardella, thanks for the issue.
This seems a bit constructed to me. When should the printers power fail, but not the power of the computer running the application?

But well, let's have a look at the issue:
I think the most sensible way would be to rely on the underlying communication library to raise an exception. For the USB-printer this should work. We do not catch the exception, so it would be a bit raw, but all in all it should fail.

The `socket`-library seems also to be able to raise an exception if bytes could not be sent. I had a quick try but could not get it to fail (just by playing with sockets). (I created a socket, then sent bytes through that socket. Then turned off my network to that remote point and tried sending again, which did curiosly not fail. I am however not completely sure, if we have a connection state in a socket at all.) Unfortunately, I currently do not have the time to check this further.

If you want to, you could try to implement this for the library. You could implement a parameter for the printer-class that enables or disables that feature. The printers that do not support this feature should raise an NotImplementedError-exception.

**Comment by Simonefardella** [comment]
How I can implement this?
I'll be glad to do that, can you give me a starting point (snippet or documentation links will be fine) to make some tests?

Thanks

**Comment by patkan** [comment]
You could start with the [socket-howto](https://docs.python.org/3.6/howto/sockets.html#socket-howto) and see if there is a way to check that the recipient does not receive the bytes. If you have found something there you can patch the Network-printer.

**Comment by belono** [comment]
Hi @Simonefardella.
I don't have access to a network printer so this is not tested, at least by me ;)

The `escpos.printer.Network` constructor has a `timeout` param that defaults to 60 seconds.
You can pass a different value and wait for the timeout to expire, then an exception must be raised by the `socket` library.

So please try:
```
from escpos import printer as escpos_printer
from escpos.escpos import EscposIO
import time

with EscposIO(escpos_printer.Network(192.168.1.1, port=9100, timeout=10), autocut=True) as printer_socket:
    printer_socket.writelines('Test Line 1')
    time.sleep(5)  # Turn-off the printer and wait for at least 10 secons, an exception must be raised.
    printer_socket.writelines('Test Line 2')
    printer_socket.writelines('Test Line 3')
    printer_socket.writelines('Test Line 4')
    printer_socket.writelines('Test Line 5')
```
Let us know if it worked or no exception is raised at all.

**Comment by Simonefardella** [comment]
@belono, no exception at all!

By the way, I'm trying to do something different...i know, it's tricky, but it's working (this snippet will slightly slow the print process), basically, the inherited class (EscposIO), redefines the constructor method and the writelines method.
The writelines methods: every two lines will close the socket, wait 100ms and tries to reopen it; if something will fail, the exception will be catched and using a recursive call to the same method the lines queue will be consumed.

All suggestions are welcome!


```

from queue import Queue
from escpos.escpos import EscposIO, six
import time


class CustomEscPosIO(EscposIO):
	def __init__(self, printer, autocut=True, autoclose=False, **kwargs):

		self.text_queue = Queue()
		super(CustomEscPosIO, self).__init__(printer=printer, autocut=autocut, autoclose=autoclose, **kwargs)

	def writelines(self, text, reprint_exception=False, check_alive=True, **kwargs):

		try:
			params = dict(self.params)
			params.update(kwargs)

			if isinstance(text, six.text_type):
				lines = text.split('\n')
			elif isinstance(text, list) or isinstance(text, tuple):
				lines = text
			else:
				lines = ["{0}".format(text), ]

			#If the chesk alive it's enabled and the reprint_exception flag is false
			if check_alive and not reprint_exception:
				self.text_queue.put({'text': lines, 'params': params})
			#Close and reopen the connection, checking if the device it's still online
			for line in lines:
				if self.text_queue.qsize() % 2 == 0:
					self.printer.close()
					time.sleep(0.1)
					self.printer.open()
					params.update(kwargs)

				self.printer.set(**params)
				if isinstance(text, six.text_type):
					self.printer.text(u"{0}\n".format(line))
				else:
					self.printer.text("{0}\n".format(line))
		except Exception as ex:
			self.printer.close()
			time.sleep(5)
			self.printer.open()

			#Tries to flush the queue, reprinting everything
			while not self.text_queue.empty():
				data = self.text_queue.get()
				self.writelines(data['text'], reprint_exception=True, **data['params'])



```

**Comment by belono** [comment]
Ok  @Simonefardella.

Maybe the most common scenario where the printer can stop during the job is the end of the roll paper, another one is a printer malfunction. A power failure of the printer and not the computer could be possible if the computer is a battery powered device or is connected to an uninterruptible power supply.
Anyway, I had a problem some time ago with a parallel printer using the `escpos.printer.File` under linux quite similar to yours. and the module [stopit](https://pypi.python.org/pypi/stopit) helped me.

My problem was that the printer was often blocked due to a malfunction of the print head. So, after a couple of lines, the printer stopped, blocking my application indefinitely, because the connection (/dev /lpt1) could not be closed. Many times the print head blocked again and again after a printer restart so I had to implement a solution on my program to timeout the print job.

You can use `stopit` as a decorator or as a context manager, if the execution takes too long and the timeout expires a `stopit.TimeoutException` is raised and the process stopped. There is a `stopit.async_raise` to raise the exception in another thread so your process will continue.

An example of how I test if the connection to the printer can be opened and closed:

```
import sys

import escpos.printer as printer
if sys.platform.startswith('win'):
    from stopit import threading_timeoutable as timeoutable
else:
    from stopit import signal_timeoutable as timeoutable

class escpos_Printer(object):
    def __init__(self):
        self.epson = printer.File(devfile='/dev/lpt1')

    def check_printer(self):
        return self._test_conn(timeout=5)

    @timeoutable('Timeout Error')
    def _test_conn(self):
        self.epson.hw('SELECT')
        self.epson = None
```

**Comment by patkan** [comment]
Hi, any updates on this issue? Otherwise I would close it. :-)
