### ISSUE TITLE
Printer Unresponsive

### ISSUE THREAD

**Issue by devdevnullnull** [python-escpos/python-escpos#256]
I have:
- [x] searched open and closed issues for duplicates

### Bug description
I've install both the development version cloning the repo and the stable one (in different enviroments). I'm using an epson stylus c63. The printer is correctly detected o both oses, and I've also got some info from the printer (paper status for example).
I've tested own code, some examples of the "examples" directory and the example of the README.md. No error is outputed, only unresponsivness from the printer. 
Since there is no error, is hard to know where is the problem. And since de printer is correctly detected by the library, is hard to know if it is actually supported (according to the ESC/P manual, it is...)

**Comment by patkan** [comment]
Hi @devdevnullnull,
are you sure that your printer ist compatible? This seems to be a inkjet printer that is possibly controlled by the ESC/P protocol.
This library is intended for (mostly) thermoprinters controlled by ESC/POS.
As far as I see it those two protocols only have the ESC symbol as escape-sequence in common.

**Comment by devdevnullnull** [comment]
Yeah, you're right. I didn't know that ESC/P and ESC/POS where completely different protocols. 
I'm closing the issue.
