### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Error' on Python 2.7

### ISSUE THREAD

**Issue by mashedkeyboard** [python-escpos/python-escpos#257]
I have:
- [x] searched open and closed issues for duplicates

### Bug description

Python 2.7 breaks the "escpos.Error" functionality. Whereas on Python 3 I can do `raise escpos.Error("whatever I want to raise")`, the same on Python 2 results in `AttributeError: 'module' object has no attribute 'Error'`.

### Steps to reproduce
Reproduction is visible by running the printer test of my app, [Headlights](https://github.com/mashedkeyboard/Headlights), on Python 2.7. It's also visible here: https://travis-ci.org/mashedkeyboard/Headlights/jobs/274772729

### Device info

 **Printer:** N/A

 **python-escpos version:** 2.2.0

 **python version:** 2.7

 **operating system:** N/A

**Comment by patkan** [comment]
I don't quite understand why this works with python3 for you.
However, this should work in all versions of python when you use the following import:

```python
import escpos.exceptions

raise escpos.exceptions.Error("somethingsomething Error")
```

I have added a test to verify this.
