### ISSUE TITLE
How can I print image and text in the same line?

### ISSUE THREAD

**Issue by jariberi** [python-escpos/python-escpos#258]
I need to print a text image on the same line, how can I print it? Thank you!

**Comment by patkan** [comment]
As far as I know: you can't. At least not with the commands implemented in the current version.
You could read in the ESCPOS-manuals if there is a possibility to do this with page-mode. (With this you can print into a buffer and the print a whole page at once)

**Comment by patkan** [comment]
In case somebody finds a way to achieve this, feel free to comment here so we can reopen the issue.

**Comment by larssn** [comment]
It should be possible using `Page Mode`: https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=193
Afraid that's all I know, and the docs are as sparse as ever on... everything.
