### ISSUE TITLE
Resource Busy

### ISSUE THREAD

**Issue by StormSpirit1996** [python-escpos/python-escpos#259]
When I use python-escpos(2.2.0) on a Debian system：
（python 2.7）
>>>from escpos.printer import Usb
>>>p = Usb(0x6868, 0x0500, 0 ,0x84, 0x03)
There comes an error：
    errno[16]: Resource Busy
I'd like to know how to solve it.
Thanks!

**Comment by patkan** [comment]
Hi @StormSpirit1996 have you found a solution to your problem?
