### ISSUE TITLE
How to print a qr code with right justification？

### ISSUE THREAD

**Issue by JunweiSUN** [python-escpos/python-escpos#260]
Hi， this project is really useful， but I need to know how to print a qr code with right justification.  Thanks!

**Comment by StormSpirit1996** [comment]
Use the set() function. Find it in  escpos.py.

**Comment by patkan** [comment]
#250 included a fix for this, but it is currently not yet in a released version. You can test this by using the current version of the development branch.
I will try to release a new preview-version asap.

**Comment by patkan** [comment]
Sorry, I misread your message. You want to have the code on the right side, not in the center. You can nevertheless have a look at the mentioned PR to see a possible solution for your problem.
