### ISSUE TITLE
Clear text on pole display

### ISSUE THREAD

**Issue by elachere** [python-escpos/python-escpos#270]
Hi,

I'm able to display text on a serial pole display (bixolon bcd-1100), but I can't figure out how to clear what's already displayed on the screen ?
When I call my_printer.text('some text') 2 times or more, the text is just added after.

Thank's

**Comment by patkan** [comment]
Hi, I'm sorry but I do not have a display. So I can't really test anything.
But you could check the manual of the display: http://www.bixolon.com/upload/download/bcd-1100_command_manual_english_rev_1_00.pdf
There are some commands that should be the same as normal escpos. If you have found a command that you want to try and that is not implemented yet, you can send it to the printer with the _raw-method.
