### ISSUE TITLE
Magic encoding broken on second call of the same script

### ISSUE THREAD

**Issue by giggls** [python-escpos/python-escpos#272]
### Bug description
Automatic encoding does not work on second call of the same script

### Steps to reproduce
Start the provided script twice. Character encoding is broken on the second call.
Here is the script:
The Euro and German umlaut symbols are working fine on first call after device reset but are broken on subsequent calls of the script.

Unfortunately it will sometimes need a few more tries before it will get broken.

```python
from escpos.printer import Usb
p = Usb(0x0416, 0x5011,0, profile="POS-5890")
p.text("\n")
p.set(align=u'left', custom_size=True, width=2, height=2, font=1)
p.text("SUMME          €10,47\n\n")
p.text("Bar:           €15,00\n")
p.text("Rückgeld:       €4,53\n")
p.cut()
```

### Device info
 **Printer:** Excelcan ZJ-5890K
 **python-escpos version:** 3.0a3
 **python version:** 3.5.3 (distro version)
 **operating system:** Debian 9.x

**Comment by mike42** [comment]
Thanks for posting. It's not obvious to me whether this is the cause, but can you try again with this code and see if the problem persists?

```python
from escpos.printer import Usb
p = Usb(0x0416, 0x5011,0, profile="POS-5890")
p._raw(b'\x1b@');
p.text("\n")
p.set(align=u'left', custom_size=True, width=2, height=2, font=1)
p.text("SUMME          €10,47\n\n")
p.text("Bar:           €15,00\n")
p.text("Rückgeld:       €4,53\n")
p.cut()
```

I can't see `python-escpos` setting the character encoding back to default at the start of the print, so this issues the `ESC @` command manually, which may help.

**Comment by giggls** [comment]
Hm looks like this mitigates the bug somewhat to make it appear less frequently (at least I got the impression).
Can I set the encoding manually as a workaround? If so, is there a codepage which has German umlauts and Euro symbol?

**Comment by patkan** [comment]
You can pass on arguments that control magic_encode when you are creating the instance of your printer.
Issue something like `Usb(0x0416, 0x5011,0, profile="POS-5890", magic_encode_args=PUT THEM HERE)`

You can put there a dictionary with the arguments for magic_encode. The class is described [here](https://python-escpos.readthedocs.io/en/latest/api/magicencode.html#escpos.magicencode.MagicEncode).

If you set `encoding` to a suitable codepage and `disabled` to True, then it will print just in this codepage. The rest (unicode-input, automatic encoding into the set codepage) remains unchanged.

You can also call `p.magic.force_encoding(encoding)` for the same result. `encoding` is the name of your codepage. In this case, please try "[CP858](https://en.wikipedia.org/wiki/Code_page_858)".

**Comment by giggls** [comment]
I wonder if my device is broken. Even this code will produce an invalid Euro sign roughly on every second call.

#!/usr/bin/python3

from escpos.printer import Usb
p = Usb(0x0416, 0x5011,0, profile="POS-5890")
p.magic.force_encoding("CP858")
p.set(align=u'left', custom_size=True, width=2, height=2, font=1)
p.text("Rückgeld:       €4,53\n")
p.cut()

**Comment by patkan** [comment]
But only the euro-sign is defective?

Does this occur between different calls of the script? Have you tried calling the line with the euro several times?

You could swap out your printer-object with the Dummy-printer. This way you can check the output, which should stay the same every time.

If you are sure that the output is the same then maybe it has to do something with a buffer. Maybe adding sleeps helps to reduce the problem. (Or at least to narrow the source of the problem down)

**Comment by giggls** [comment]
Do you have an example for dummy printer usage?

I just tried this:
```python
#!/usr/bin/python3

import time

from escpos.printer import Usb
p = Usb(0x0416, 0x5011,0, profile="POS-5890")
p.magic.force_encoding("CP858")
p.set(align=u'left', custom_size=True, width=2, height=2, font=1)
for i in range(1,10):
  p.text("ÄÖÜäöüß €\n")
  time.sleep(1)
```

Umlauts are fine, but the Euro sign changes to something else at some unpredictable stage.

**Comment by patkan** [comment]
Usage is something like this:
```python
#!/usr/bin/python3

import time

from escpos.printer import Dummy
p = Dummy(profile="POS-5890")
p.magic.force_encoding("CP858")
p.set(align=u'left', custom_size=True, width=2, height=2, font=1)
for i in range(1,10):
  p.text("ÄÖÜäöüß €\n")
  time.sleep(1)

print(p.output)
```
`output` contains the output. The newest version in development contains also the method `Dummy.clear()` if you need to clear the content of the Dummy-printer.
This way you could print to Dummy, save to an array, clear, repeat and afterwards if every array entry contains the same.
Or you just copy the output to a file and have a look at it with a hex-editor.

**Comment by giggls** [comment]
Hm looks like some USB bus timing problem and or broken printer firmware. Files generated this way by python escpos are identical. Printing a file written using sys.stdout.buffer.write(p.output) using "cat file >/dev/usb/lp0" is producing the same Euro sign errors. Does anybody have a ZJ-5890K device where this code works? I wonder if there is a firmware update for the device.
