### ISSUE TITLE
tpm of conditionally dependent system

### ISSUE THREAD

**Issue by ZHam2012** [python-escpos/python-escpos#276]
Hello,
I am using pyphi on windows 10. 
I am trying to create a tpm of 2 element (A,B) system which is not conditionally independent. 
The system is as follows, 
AB    00   10   01  11
00     0     .5    .5    0
10     0    .5    .5    0  
01     0    .9    .1    0
11     0    .5    .5    0
I have created tpm (state by state form) as follows
tpm = np.array([
	[0,0.5,0.5,0],
	[0,0.9,0.1,0],
	[0,0.5,0.5,0],
	[0,0.5,0.5,0]
	])
To make it conditionally independent, I have Introduced another node and created a tpm. As follows, (state by state form)
tpm2 = np.array([
	[0,0.5,0,0,0,0.5,0,0],
	[0,0.5,0,0,0,0.5,0,0],
	[0,0,0.1,0,0,0,0.1,0],
	[0,0,0.5,0,0,0,0.5,0],
	[0,0,0.5,0,0,0,0.5,0],
	[0,0,0.5,0,0,0,0.5,0],
	[0,0.9,0,0,0,0.9,0,0],
	[0,0.5,0,0,0,0.5,0,0]
	])
But when I convert this to state by node and reconvert to state by state, it gives me a different system than original. It gives me, 
>>> sbn_tpm2 = pyphi.convert.state_by_state2state_by_node(tpm2)
>>> sbs_tpm2 = pyphi.convert.state_by_node2state_by_state(sbn_tpm2)
>>> print(sbs_tpm2)
[[ 0.    0.5   0.    0.    0.    0.5   0.    0.  ]
 [ 0.    0.5   0.    0.    0.    0.5   0.    0.  ]
 [ 0.72  0.    0.18  0.    0.08  0.    0.02  0.  ]
 [ 0.    0.    0.5   0.    0.    0.    0.5   0.  ]
 [ 0.    0.    0.5   0.    0.    0.    0.5   0.  ]
 [ 0.    0.    0.5   0.    0.    0.    0.5   0.  ]
 [-0.08  0.18 -0.    0.   -0.72  1.62 -0.    0.  ]
 [ 0.    0.5   0.    0.    0.    0.5   0.    0.  ]]

How do I correctly create a tpm of the system? 
Can you please help me out?

**Comment by patkan** [comment]
Sorry, but you created an issue in the wrong project. This is the repository for python-escpos, a library for printing with receipt printers.
