### ISSUE TITLE
How to rewind the paper

### ISSUE THREAD

**Issue by JunweiSUN** [python-escpos/python-escpos#277]
Hello, thanks for seeing my question. I'm using the python-escpos2.2.0 now and it worked well. But I want to know if here is a function in it that can rewind the paper? Because sometimes I want the paper rewind automatically. If there is any solution, please let me know. Thanks!

**Comment by patkan** [comment]
Hello,
there is nothing implemented at the moment.
Depending on your printer and use case you could assemble a page in page-mode and then print afterwards or use a backwards feeds command.
On which printer are you trying to realise this and could you maybe put together a example of what you are trying to achieve?
