### ISSUE TITLE
Pip installing older 2.2 not 3

### ISSUE THREAD

**Issue by abulka** [python-escpos/python-escpos#284]
### Bug description

pip install python-escpos results in version 2.2.0 being installed not the latest 3.0a3 that clearly exists on pypi [https://pypi.python.org/pypi/python-escpos/3.0a3](url)

### Steps to reproduce
- activate python 3.6
- pip install python-escpos
- pip list | grep escpos

Shows 2.2.0 not 3.0a3
I've even tried with a python 2.7.13 environment - same thing, I get the older version.

 **python version:** 3.6

 **operating system:** Mac

From the output below, it seems that pip is finding the later versions but somehow ignoring them?

`
  Analyzing links from page https://pypi.python.org/simple/python-escpos/
    Found link https://pypi.python.org/packages/02/f6/05f14496229c913507ea7220f655f349b7736ac9b104e18cf66417fb29f1/python-escpos-2.1.2.tar.gz#md5=fdf842f293ce67cdffa3c9616b958ae5 (from https://pypi.python.org/simple/python-escpos/), version: 2.1.2
    Found link https://pypi.python.org/packages/15/74/16dfdeb43b3df15a803cb7eed853353505ec597601e01df6f43683bd05da/python-escpos-1.0.6.tar.gz#md5=3b56a0fc7a8baa797b05a1d5b7c6c4a4 (from https://pypi.python.org/simple/python-escpos/), version: 1.0.6
    Found link https://pypi.python.org/packages/1f/1c/463e46d1e80dd3666cbebdaf0f0fcb444c58a60264730533ccb3fd52fb38/python-escpos-1.0.5.tar.gz#md5=e240059274d723d97cc4ca667d55a850 (from https://pypi.python.org/simple/python-escpos/), version: 1.0.5
    Found link https://pypi.python.org/packages/23/23/50a0c86473adf97e97a77881a1a1873093296cd5c2b66905f82a805afb97/python_escpos-3.0a3-py2.py3-none-any.whl#md5=4b011b3c15df057f4d11e47aaa803e42 (from https://pypi.python.org/simple/python-escpos/), version: 3.0a3
    Found link https://pypi.python.org/packages/24/20/ccfbb4cb44c80e0f2157094dee46b812555d8623a65555dd9466ccc63779/python-escpos-2.2.0.tar.gz#md5=50e62711bdfdfad4fee10aebd46b161c (from https://pypi.python.org/simple/python-escpos/), version: 2.2.0
    Found link https://pypi.python.org/packages/27/10/81b048e66fba78a2367789ef6baf9e3ac0ff18c34dcafd6b94086dc597fc/python-escpos-3.0a2.tar.gz#md5=56d71bcf36105de11c94205a3b300e1c (from https://pypi.python.org/simple/python-escpos/), version: 3.0a2
    Found link https://pypi.python.org/packages/32/1e/71f74bc861caa5b207ae1146febd9e12f15f5d045ce357bc17cb3e248dd0/python-escpos-1.0.2.tar.gz#md5=ea78287f6f8f695adc9a1b554b7e65d5 (from https://pypi.python.org/simple/python-escpos/), version: 1.0.2
    Found link https://pypi.python.org/packages/34/58/d50b59d3b3ba0b7ac3a5520e06a70015764e9869eeb8e8d03537f869df87/python_escpos-2.1.0-py2.py3-none-any.whl#md5=b3159cfa2c59bad00a000d41d4db5aa5 (from https://pypi.python.org/simple/python-escpos/), version: 2.1.0
    Found link https://pypi.python.org/packages/3b/a8/e6b18e688a68033b9546c39d056ebcedfdabd504e8f8471389893111e3a0/python-escpos-3.0a1.tar.gz#md5=bf98d39d13a951b9c1d1809f16c015ff (from https://pypi.python.org/simple/python-escpos/), version: 3.0a1
    Found link https://pypi.python.org/packages/41/71/e8098653b9d0bb46b568e387012d20b7119b281ad3f8096b977cdd8e9895/python-escpos-2.1.0.tar.gz#md5=13e32bdd8963e478bbec375fcfe78f96 (from https://pypi.python.org/simple/python-escpos/), version: 2.1.0
    Found link https://pypi.python.org/packages/4b/03/320c807328eb53d82baa0ee881553ea4649c6ca38ed1c047e6d31ffa09cd/python-escpos-2.1.1.tar.gz#md5=2944cc0fce799126ef724e4a258b4310 (from https://pypi.python.org/simple/python-escpos/), version: 2.1.1
    Found link https://pypi.python.org/packages/4b/25/93fbed8dfcba5f06b59b07bf09a147dbf0de6829add57928336081220b72/python-escpos-1.0.4.tar.gz#md5=bec6c14df1ac20e72a666cda4d58f0ae (from https://pypi.python.org/simple/python-escpos/), version: 1.0.4
    Found link https://pypi.python.org/packages/4c/e3/affa75687171b17b22dd709776af1322c05dd584cd75c345062a2e61a59f/python-escpos-3.0a0.tar.gz#md5=795513d13c1aa29519fa396aa78a82bb (from https://pypi.python.org/simple/python-escpos/), version: 3.0a0
    Found link https://pypi.python.org/packages/55/4c/a330138fcf09b2d9194c23b02804778be83b44851b9c785b59756b23e913/python-escpos-1.0.3.tar.gz#md5=795d15b43158a322be0f8f005de27cff (from https://pypi.python.org/simple/python-escpos/), version: 1.0.3
    Found link https://pypi.python.org/packages/55/b6/22f956424218c510e2f421207f32861327ae5f972520e6bd0b1975f59135/python_escpos-2.1.3-py2.py3-none-any.whl#md5=849eaf991fd3f9067cc3e4ccfe2679d8 (from https://pypi.python.org/simple/python-escpos/), version: 2.1.3
    Found link https://pypi.python.org/packages/6c/76/6bf13f046c07803b4bc72f17ace55708d670869ed897fdef62a6f5b5995b/python-escpos-2.0.0.tar.gz#md5=3262cc83ba7694b15de4e46e0babc18d (from https://pypi.python.org/simple/python-escpos/), version: 2.0.0
    Found link https://pypi.python.org/packages/6d/91/6be90920aab6422f3c74efb7c0b35d83b9c9ddf8e14c74d31f4926e63096/python-escpos-1.0.6b.tar.gz#md5=a363af9ca65bf8e3cd04a4f52adb9884 (from https://pypi.python.org/simple/python-escpos/), version: 1.0.6b
    Found link https://pypi.python.org/packages/71/3a/5307a5bcc7f4b43cb620c7ade63b74795eb354aee3040d659daf402d4bf4/python_escpos-3.0a0-py2.py3-none-any.whl#md5=50464f06fa9dc906d7710db55ddb121d (from https://pypi.python.org/simple/python-escpos/), version: 3.0a0
    Found link https://pypi.python.org/packages/82/63/901324c6f808dc2a20d51233445f5b040035ef714a9ba5f9ccc8a0733b7c/python-escpos-1.0.9.tar.gz#md5=0f013f12d6317399e38890af146295fa (from https://pypi.python.org/simple/python-escpos/), version: 1.0.9
    Found link https://pypi.python.org/packages/87/94/307a7f7a7a230cc9ab057eb193d5deaa64db84cece16fed5aea70ff6484c/python_escpos-2.2.0-py2.py3-none-any.whl#md5=169a0f129e343a657fcf56a7db5cf88c (from https://pypi.python.org/simple/python-escpos/), version: 2.2.0
    Found link https://pypi.python.org/packages/91/7d/4c1837a1f2c2969acd3e8d3280f0d60a2b0455631f5fc70ca5b41c703716/python-escpos-1.0.1.tar.gz#md5=b7ba15251062bc5b9dfae370a151d579 (from https://pypi.python.org/simple/python-escpos/), version: 1.0.1
    Found link https://pypi.python.org/packages/98/d4/fc8f3157f77235a5fadb779820464fb6b5e6b5d9b78d2e50a4951c70f73a/python-escpos-2.1.3.tar.gz#md5=e3597b0cdcd3104668921c9c1a9ab5e6 (from https://pypi.python.org/simple/python-escpos/), version: 2.1.3
    Found link https://pypi.python.org/packages/b9/4a/bb0525e3279615356ac2fc71fb3d2130723c0382ace592fbb891de6f30ce/python_escpos-2.0.0-py2.py3-none-any.whl#md5=f67e824ab920ad7a74a7768818bb65c4 (from https://pypi.python.org/simple/python-escpos/), version: 2.0.0
    Found link https://pypi.python.org/packages/bf/1d/b15ad9dbce20b4a244350d9c6ddbce2e1ccd408ef821ad8b72a6edc28a7f/python-escpos-1.0.7.tar.gz#md5=9fb5cce5bc1f1c55b776f7749db4fb25 (from https://pypi.python.org/simple/python-escpos/), version: 1.0.7
    Found link https://pypi.python.org/packages/c1/42/949ccc7d962b0ecc7fac5cb091b7e3e7c1f877e385df79a07deb73d5d1dc/python_escpos-3.0a1-py2.py3-none-any.whl#md5=14898a79852843196c6ee1a7ba0d517f (from https://pypi.python.org/simple/python-escpos/), version: 3.0a1
    Found link https://pypi.python.org/packages/c5/f4/2ea408c40a30b68a8fc4e9282017387ca90b4fda2d549c7fb2d4d22ae0f1/python_escpos-2.1.2-py2.py3-none-any.whl#md5=3239175a2368b27679f36c154ffc9740 (from https://pypi.python.org/simple/python-escpos/), version: 2.1.2
    Found link https://pypi.python.org/packages/d5/af/03655371bcfb69b060aa9b73eb412b5c78cb10fb7f95bbbeacabf7719e77/python-escpos-1.0.8.tar.gz#md5=3d925fe6063f9f0412e9b213fba96187 (from https://pypi.python.org/simple/python-escpos/), version: 1.0.8
    Found link https://pypi.python.org/packages/df/90/54dd7fb2b31c7890ea14f730b99b3b03f64459252e676a74de4e01cf4b39/python-escpos-1.1.0.tar.gz#md5=bc06d77e5415bc5eda0f134e291e7540 (from https://pypi.python.org/simple/python-escpos/), version: 1.1.0
    Found link https://pypi.python.org/packages/e1/86/ece8c572cdf30c57d4119b204ae805f27f25c4b37a94e3cfac2087a5a04d/python_escpos-3.0a2-py2.py3-none-any.whl#md5=e6e24175e040fa035d1dea9c3ff3c73e (from https://pypi.python.org/simple/python-escpos/), version: 3.0a2
    Found link https://pypi.python.org/packages/ef/ef/f3a63e50b14f895b0d2d2f837cdd034f3e9e32d5f730c135b89b313fba42/python_escpos-2.1.1-py2.py3-none-any.whl#md5=a8d1aba512e9acfef7d92fea35c8d3fd (from https://pypi.python.org/simple/python-escpos/), version: 2.1.1
    Found link https://pypi.python.org/packages/fe/34/4af80c2cd89d72ffd50e7acbeb63077af4817308acbda37b68966af55898/python-escpos-1.0.10.tar.gz#md5=e4a1c9fc517d5628316ea7a10ec55cf5 (from https://pypi.python.org/simple/python-escpos/), version: 1.0.10
  Using version 2.2.0 (newest of versions: 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.10, 1.1.0, 2.0.0, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0)
`

**Comment by patkan** [comment]
Hi @abulka, thank you for posting.
This is a feature of pip. It will by default not install pre-releases. You can change this behaviour by setting the `--pre`-option.

The version 3 is unfortunately still in alpha since there has not been the time yet for the refactoring of the API that is planned for version 3.

**Comment by abulka** [comment]
Aha, I see.  Adding --pre let me use the latest version.  Thank you.
