### ISSUE TITLE
How to get paper_status command working

### ISSUE THREAD

**Issue by bthai** [python-escpos/python-escpos#286]
I am trying to check for the printer status but does not seem to be working. I have a printer I can connect to in my local network and all the commands below works except the last two `printer.paper_status()` and `printer.is_online`. Can anyone give me some guidance? Not a python guy by trade. I believe these commands should be available in the Network class as they are inherited from Escpos, but getting traceback messages like the one below.

AttributeError: 'Network' object has no attribute 'paper_status'

My script is provided here
```
#!/usr/bin/python

import sys

from escpos.printer import Network


""" Seiko Epson Corp. Receipt Printer M129 Definitions (EPSON TM-T88IV) """
printer = Network("192.168.10.166", port=9100, timeout=60)
# Print text
printer.text("Hello World\n")
# Print image
#Epson.image("logo.gif")
# Print QR Code
printer.qr("You can readme from your smartphone")
# Print barcode
printer.barcode('1324354657687','EAN13',64,2,'','')
# Cut paper
printer.cut()

# paper_status not working
printer.paper_status()
```

**Comment by jeffreyworsley** [comment]
so im working on this with the DLE EOT commands using serial, im just getting an issue with how to read the data back in 8bit, but it some what works...

[stackoverflow link](https://stackoverflow.com/questions/49186670/esc-pos-dle-eot-printer-status-escpos)

**Comment by jeffreyworsley** [comment]
I have this working with bits not int which I feel is better anyway since it reads the whole reason its offline

**Comment by MeritEhab** [comment]
Hello @jeffreyworsley I still can't get this working
can you please put a code snip showing us what you did before making a network pr usb object from escops and how did you call paper_status
Thank you 

@bthai did you mange to get this command working ?!

**Comment by diveinsky** [comment]
Did anybody managed to get the ouput

**Comment by alexdebiasio** [comment]
I managed to query the printer status, using the version *3.0a4*.
The problem is that the Network class does not implement the _read method, thus raising a NotYetImplementedError. By adding the following _read method I was able to correctly querying the paper and the printer status on a Citizen CTS310II-LAN:

```
class Network(Escpos):
  def _read(self):
    return self.device.recv(16)
```

I'm preparing a pull request so you can test if that works also for you.

**Comment by patkan** [comment]
Feel free to comment or reopen if it is not fixed yet

**Comment by alesof** [comment]
I’m working on a script using an Epson printer (TM-T88V). I’m able to print and all but I’m facing the same issue reported here.
‘Network’ object has no attribute ...
