### ISSUE TITLE
/dev/null for windows

### ISSUE THREAD

**Issue by jeffreyworsley** [python-escpos/python-escpos#288]
I have:
- [ /dev/null ] searched open and closed issues for duplicates

### Bug description
/dev/null does not exist in windows

FIX: src/escpos/escpos.py
```
LINE 24  +import os.devnull
LINE 494 +nullfile = open(os.devnull,"w")
                  my_code.write(nullfile, { ....

```
I don't have commint push access... 

### Steps to reproduce
- run in windows
- init escpos

### Device info

 **python-escpos version:** all

 **python version:** 3.7.0b1

 **operating system:** Windows 10

**Comment by patkan** [comment]
@jeffreyworsley thank you for the improvement! Could you please create a Pull Request?
