### ISSUE TITLE
python-escpos prevents Flask web server from logging

### ISSUE THREAD

**Issue by eliaperantoni** [python-escpos/python-escpos#292]
I have:
- [x ] searched open and closed issues for duplicates

### Bug description
Flask and python-escpos seems not to be working well together. I have created a simple script that creates a flask web server and imports the `Network` class from `escpos.printer`. The web server seems to be working fine but I get no logging whatsoever on the console like Flask usually does.

Here's the script
```
from flask import Flask
from escpos.printer import Network

app = Flask(__name__)

@app.route("/")
def index():
    return "hello world"

if __name__ == '__main__':
    app.run()
```

I've found that when commenting out `from escpos.printer import Network` Flask runs perfectly fine, and logs to the console like this

```
    * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

But when it's not, the web server seems to be running still, but the problem is that it can't log to the console which is a feature I would need.

I've digged into Flask source code and found out that it uses `werkzeug.serving._log()` to do its logging but I don't see how this would be affected by python-escpos. Also, normal prints work.

### Steps to reproduce
- Create script like above
- Run with `python p.py`

 **python-escpos version:** 3.0a3

 **python version:** 3.6.4

 **operating system:** Windows 10

**Comment by patkan** [comment]
Thank you very much for the post.
This might be related with the use of logging in capabilities.py. (https://github.com/python-escpos/python-escpos/blob/d1e7052fa11172906fb081ef401313aa70a4111d/src/escpos/capabilities.py#L4)
If you want to you can try to remove all calls and imports of logging in python-escpos and then test it. I will try this when I have the time for this, but this could take a while.

**Comment by eliaperantoni** [comment]
Thanks! I will definitely give it a shot and let you know

**Comment by eliaperantoni** [comment]
For some reason this doesn't happen anymore, even without doing what you suggested @patkan

**Comment by patkan** [comment]
OK, so I'll close this one. Feel free to write if anything changes.
