### ISSUE TITLE
set() method problem

### ISSUE THREAD

**Issue by bima-joe** [python-escpos/python-escpos#293]
hi, how to fix this Error
i can't use bold, custom_size, etc, in set(), but there is no proble if i just use align,font,or height

TypeError: set() got an unexpected keyword argument 'bold'

**Comment by patkan** [comment]
Hi @bima-joe thanks for the issue. Could you please name the version that you have installed and post a short script that reproduces the problem?

**Comment by patkan** [comment]
Closed due to missing information.
I will reopen this issue if you provide more information.
