### ISSUE TITLE
Is windows 10 supported - getting usb_detach_kernel_driver_np error

### ISSUE THREAD

**Issue by abulka** [python-escpos/python-escpos#299]
Is it true that python-escpos 3.0a3 is not compatible with windows 10 - as [this stackoverflow comment ](https://stackoverflow.com/questions/35248718/attributeerror-function-usb-detach-kernel-driver-np-not-found) suggests?  And as suggested by the [python-escpos todo readme](http://python-escpos.readthedocs.io/en/latest/user/todo.html)?

```
from escpos import *
Epson = printer.Usb(0x04b8, 0x0e03)
```

I get the error `function 'usb_detach_kernel_driver_np' not found`.  

Am running Python 3.6.  Printer Epson TM-TS20.  Am running in vmware, windows 10 (hosted by a mac).  I can attatch the Epson printer to the windows virtual machine ok and print to it using the official Epson drivers etc.

Re python-escpos on windows 10, I worked around the lack of /tmp directory (saw there was a fix for this recently merged - nice) by simply creating a c:/tmp directory.  Then I ran into missing backend issues, and as I couldn't find libusb on the system after `pip install pyusb` thus assumed that I needed to find and install these backend dlls myself.  There are several confusing choices as to where to get these dlls from and how to install them.  I copied libusb dlls into windows/system32 using both the zadig installer and also by copying in the dlls downloaded from https://libusb.info/.
My normal Epson TM-TS20 driver (via ESDPRT001) seems to have been broken by the zadig step (which created a printer on port USB001). I currently have these dlls: (list made using git bash shell which is why it look Linux-like):

```
-rwxr-xr-x 1 Andy 197121  76384 May 17 19:06 /c/windows/system32/libusb0.dll*
-rwxr-xr-x 1 Andy 197121 121856 Mar 25 12:00 /c/windows/system32/libusb-1.0.dll*
-rw-r--r-- 1 Andy 197121  46686 Mar 25 12:00 /c/windows/system32/libusb-1.0.lib
-rw-r--r-- 1 Andy 197121 904192 Mar 25 12:00 /c/windows/system32/libusb-1.0.pdb
-rwxr-xr-x 1 Andy 197121  99128 May 17 19:06 /c/windows/system32/libusbk.dll*
```

So do I have a bad dll situation or is it simply that python-escpos 3.0a3 is not currently compatible with windows 10 and I should stop wasting my time trying to get this to work, till windows 10 is officially supported?

**Comment by patkan** [comment]
Hi @abulka thank you for your question.
I am not 100% sure, since I am developing and testing on a Linux-environment. As of 3.0a4 things like usage of /tmp should be done. @juanmitaboda looked into further improvements and it seems that the usb-backend has to be replaced. His work can be found #274.
I haven't merged it yet since I don't like to completely replace the backend, but rather prefer to support both backends.

If you find out anything more, feel free to add it to the discussion. You could try to use the changes in #274. Once I (or somebody else) had the time to change this PR to support both usb-libraries I will happily merge it and then it can also be included in a release.

**Comment by tcab** [comment]
Note here are some helpful tips on getting python-escpos working on windows 10
https://github.com/pyusb/pyusb/issues/200

**Comment by kabindra-kc** [comment]
I am developing the hotel billing system but stuck on receipt printing, i used escpos library
installed the required package and library but it shows [Errno None] Other error while trying to print the text
p = Usb(0x0416, 0x5011)
            p.text("Hello World\n")
            # p.image("logo.gif")
            # p.barcode('1324354657687', 'EAN13', 64, 2, '', '')
            p.cut()
i am testing on windows 10 , can anybody solve this problem?

**Comment by patkan** [comment]
Hi @kabindra-kc, it looks to me as this is not related to the issue in which you are posting. Could you please create a new issue and add full information: the version of python-escpos, your system version, (and the other information requested in the issue-template), the full stack-trace, your type of printer?

**Comment by gabri3l0** [comment]
> I am developing the hotel billing system but stuck on receipt printing, i used escpos library installed the required package and library but it shows [Errno None] Other error while trying to print the text i have installed pyusb 1.1.0, libusb 1.0.23b6, copied libusb-1.0.dll to system32,
> 
> p = Usb(0x0416, 0x5011) p.text("Hello World\n") # p.image("logo.gif") # p.barcode('1324354657687', 'EAN13', 64, 2, '', '') p.cut() i am testing on windows 10 , can anybody solve this problem?

did you solve the issue? im stuck as well

**Comment by belono** [comment]
Hi @gabri3l0 !

Did you install zadig?
Some users found the solution by installing the usb driver via the zadig installer on Windows at this [issue](https://github.com/python-escpos/python-escpos/issues/583#issuecomment-1768041468).

**Comment by gabri3l0** [comment]
> Hi @gabri3l0 !
> 
> Did you install zadig? Some users found the solution by installing the usb driver via the zadig installer on Windows at this [issue](https://github.com/python-escpos/python-escpos/issues/583#issuecomment-1768041468).

Yes it works! thanks! i install libusbk driver and it works! thanks!
