### ISSUE TITLE
set() got an unexpected keyword argument 'bold'

### ISSUE THREAD

**Issue by av01d** [python-escpos/python-escpos#300]
I'm running python-escpos on a Raspberry Pi, and I'm able to print stuff on a networked EPSON TM-T88V-i thermal printer. So far, so good!
I am in the early stages of using this python lib, am just trying the various examples and tests I can find.
Here is my test.py script:

```
from escpos.printer import Network

p = Network("192.168.1.133")
p.set(align='center')
p.text("Hello World\n")
p.image("smurf.png")
#p.barcode('1324354657687', 'EAN13', 64, 2, '', '')

p.qr('Test QR code')

p.set(
   font='a',
   height=2,
   align='left',
   bold=False) # If I remove this, everything works

p.text("Another line of text")

p.cut()
```

This script works, except for setting 'bold' to False. Then I run into: TypeError: set() got an unexpected keyword argument 'bold'. Same problem when I try to set double_height.
What am I missing?

 **python-escpos version:** 2.2.0
 **python version:** 2.7.9
 **operating system:** Raspbian GNU/Linux 8 (jessie)

**Comment by patkan** [comment]
Hi,
The API of `set` will change in version 3. You should therefore check the documentation for v2.2.0.
You can find it here: https://python-escpos.readthedocs.io/en/v2.2.0/api/escpos.html#escpos.escpos.Escpos.set

**Comment by RainDV** [comment]
How can I install escpos using Python 2 in Raspberry Pi? I have an error in line import escpos.
