### ISSUE TITLE
Not printing

### ISSUE THREAD

**Issue by arborin** [python-escpos/python-escpos#301]
Hello I have printing problem.

I have raspberry pi 3 (Linux raspberrypi 4.9.80)
and Seiko RP B10 RS232s interface printer, with comport serial adapter cable.

other information: 

lsusb:
---------------------------------------------------
Bus 001 Device 010: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial Port

lsusb -v -d 067b:2303
---------------------------------------------------
Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0

ls /dev/tty*
---------------------------------------------------
/dev/ttyUSB0

pi@raspberrypi:~ $ pip freeze | grep pos
---------------------------------------------------
python-escpos==3.0a3

script:
---------------------------------------------------
>>> from escpos import *
>>> Epson = printer.Usb(0x067b,0x2303,0,0x83,0x02)
>>> Epson.text("Hello\n")
>>> Epson.cut()

There is no error but nothing is happening.
After checking ls /dev/tty*,  /dev/ttyUSB0_is disappeared..

**Comment by belono** [comment]
Hi @arborin .

You are connecting to the printer via a USB to Serial adapter that creates a virtual serial device in your system. So I think you should use the python-escpos serial printer initialization:

`Epson = printer.Serial("/dev/ttyUSB0")`

**Comment by arborin** [comment]
Hello, thank you for your answer.
I checked it, but it is not working...

pi@raspberrypi:~ $ ls /dev/ttyUSB0
/dev/ttyUSB0

There is not an error but printer doesn't make anything.
------------------------------------------------------
pi@raspberrypi:~ $ sudo python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170124] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from escpos import *
>>> Epson = printer.Serial("/dev/ttyUSB0")
Serial printer enabled
>>> Epson.text("Hello\n")
>>> Epson.cut()
>>>

**Comment by mike42** [comment]
@arborin - This looks like a transport issue. Have you configured the serial port speed, parity, etc to match something that the printer understands? Correct serial port settings should be listed in the vendor manual.

Once you use `stty` to apply the correct settings, you should be able to send text:

```bash
stty ...
echo "Hello World" >> /dev/ttyUSB0
```

See "[What is the easiest way to configure serial port on Linux?](https://unix.stackexchange.com/questions/242778/what-is-the-easiest-way-to-configure-serial-port-on-linux)" on Unix StackExchange for usage. Once it works on the command-line, you should be able to do the same thing using [the available Printer.serial()](https://github.com/python-escpos/python-escpos/blob/development/src/escpos/printer.py#L110) from python.

**Comment by pisua** [comment]
Hi, 
i'm using the lib version 3.0a9.dev26+g84a97e5-py3.6.egg. And i have the same kind of issue using a PL2303 USB to Serial port Adapter. 
In my case even if the is_online() methoid return correctly True, when i use another method like text to send a string. Nothing happens and no error is return. 

Do you have any clue to solve my issue ? 
I'm connection using this command : 
```
from escpos import *
p = printer.Usb(0x067b,0x2303,None,0,0x83,0x02)
p.text("anefoanefan")
```
