### ISSUE TITLE
IMPORT ERROR: NO MODULE NAMED ESCPOS

### ISSUE THREAD

**Issue by RainDV** [python-escpos/python-escpos#302]
I have:
- INSTALLED PYTHON ESCPOS USING PYTHON3.
-Run the code using python 3

But, when I tried to install it using python 2, There's a warning saying "your setup tools is too old"

Then when I run my python script, there's the importError: No module named escpos

## Device info:
Device: Raspberry Pi 2 Model B
Printer: Epson TM-T70 Thermal Printer
Connected using serial(db25)> VGA > USB > RPi Usb port

 **python-escpos version:** 2.2.0

 **python version:** 2.0

 **operating system:**
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian

**Comment by patkan** [comment]
Have you tried updating your setuptools?

**Comment by jeffreyworsley** [comment]
over the last few days reading the issues,I feel "gone are the days of
script kiddies, and way gone are the days of programmers that solve
problems with critical thinking solutions, nope... these are the days of
spoon fed copy pasta kids." it's not there fault, we made it to easy for
them that they don't "learn" they just Google and copy pasta until it
works, not even looking at the methodology behind it to apply to other
issues.    I've always encouraged learning and helping others but lately
it's come to this... this world... ok that's my rant for the week

**Comment by RainDV** [comment]
I have removed and then installed setuptools and an error occured again, now it from the line "from escpos import *" TypeError: Item in ``from list' ' not a string

**Comment by RainDV** [comment]
I think we are learning by asking. So that next time I encounter the problem, I know what to do :)

**Comment by mike42** [comment]
For reference, on Debian, I can follow the installation and basic examples in the README without errors.

```bash
$ cat /etc/debian_version 
9.4
$ python --version
Python 2.7.13
$ pip install python-escpos
$ python 
>>> from escpos.printer import Usb
... etc
```

**Comment by RainDV** [comment]
I tried following the steps here: https://python-escpos.readthedocs.io/en/v2.2.0/user/raspi.html

When I use: from escpos import *
I recieved error: TypeError: Item in ``from list' ' not a string

When I use: from escpos.printer import Usb
I recieved error: IOError: [Errno 2] No such file or directory: 'usr/local/lib/python2.7/dist-packages/python_escpos-3.0a4-py2.7.egg/escpos/capabilities.json'

**Comment by patkan** [comment]
The steps on readthedocs are outdated. As @mike42 wrote, using pip should suffice.

Also, when using pip use the flag `--pre` in order to install the newest pre-release.

**Comment by RainDV** [comment]
I tried pip install python-escpos --pre

And then it requires numpy 1.11.0 & Pillow 3.1.0

And then I installed numpy

But it gets stucked at 'Running setup.py bdist_wheel for numpy'

**Comment by patkan** [comment]
Normally pip should install all the dependencies automatically. Did you have to install numpy manually?

If you have problems with specific dependencies, you should also be able to use older versions of e.g. numpy.

**Comment by diveinsky** [comment]
in case anybody gets this error, try this ; your python app name should not be same as any files in  "/usr/local/lib/python3.6/dist-packages/escpos/"
