### ISSUE TITLE
documentation is broken

### ISSUE THREAD

**Issue by patkan** [python-escpos/python-escpos#309]
The documentation does not show the code snippets anymore. (The ones imported by automethod and such)

**Comment by mike42** [comment]
Possibly the same issue, browsing readthedocs shows that our `autodoc` disappeared between [v3.0a1](https://python-escpos.readthedocs.io/en/v3.0a1/user/methods.html) and [v3.0a2](https://python-escpos.readthedocs.io/en/v3.0a2/user/methods.html), which contains [quite a number](https://github.com/python-escpos/python-escpos/compare/v3.0a1...v3.0a2) of commits.

The inclusion of `viivakoodi` in `doc/requirements.txt` is the only change to the `doc/` folder. Changes on the readthedocs side are also a possible cause.

Have not attempted to build locally.

**Comment by patkan** [comment]
I fixed it these days: The current issue was that readthedocs could not find the capabilities file and as a consequence autodoc did not function. I have added the path to the capabilities file as an environment variable
