### ISSUE TITLE
Print image limited to 255px height

### ISSUE THREAD

**Issue by GoogleCodeExporter** [python-escpos/python-escpos#31]
```
Hello there,

I am trying to print images that are bigger than 255px in height but it throws 
ImageSizeError(). Is there any reason to limit the image size in hieght ? 

Thanks



```

Original issue reported on code.google.com by `benoit.g...@gmail.com` on 23 May 2014 at 6:06

**Comment by giorgoc** [comment]
Sorry but, since i have the same annoying issue, could you help guide us how to resolve the issue? What limes of code shall i change and where?

Thank you for your precious help!

**Comment by cod3monk** [comment]
How about a simple workaround and split the image into stripes of 255px? I can prepare a patch if you would consider merging it.
