### ISSUE TITLE
'Usb' object has no attribute

### ISSUE THREAD

**Issue by KakarN** [python-escpos/python-escpos#313]
I have:
- [ Yes] searched open and closed issues for duplicates

### Bug description
I have an Epson thermal printer (TM-82), connected via USB. I am trying to run some of Escpos module's methods such has `ln`, `textln`, etc. But none of these commands work, and I get an error `'Usb' object has no attribute <method_name>`. The only commands that work are `text`, `qrcode `, `barcode`, `image` and `cut`.

Can you guys please tell me what's wrong?

### Steps to reproduce
```
>>> from escpos import printer
>>> p = printer.Usb(0x04b8, 0x0e11, 0)
>>> p.text('hello')
>>> p.ln()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Usb' object has no attribute 'ln'
>>> p.is_online()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Usb' object has no attribute 'is_online'
```

### Device info

 **Printer:** Epson  TM-T82

 **python-escpos version:** 2.2.0

 **python version:** 2.7.10
 **operating system:** macOS High Sierra (10.13.6)

**Comment by patkan** [comment]
The version 2.2.0 that you installed does not have the methods that you are searching.
If you need them, you could tell pip to install pre-releases (--pre) in order to get an alpha release of v3 or you could build a package yourself from the current master.
