### ISSUE TITLE
EPSON TM-T20II 58mm

### ISSUE THREAD

**Issue by finnwoodman** [python-escpos/python-escpos#315]
I have:
- [x] searched open and closed issues for duplicates

### Steps to reproduce
- add your steps here
- as a list
- using hyphens

### Device info

 **Printer:** Manufacturer Model XVI

 **python-escpos version:** 0.0.0

 **python version:** 0.0

 **operating system:**

**Comment by patkan** [comment]
Could you please describe the issue?
