### ISSUE TITLE
How to work with windows 7

### ISSUE THREAD

**Issue by KakarN** [python-escpos/python-escpos#316]
I have:
- [x ] searched open and closed issues for duplicates

### Bug description
I am trying to work with Epson POS TM-82 printer on windows 7 (64 bit). I have installed the printer's driver. I have python 2.7.15 (64 bit) installed. To work with python I am using this package, python-escpos.

### Steps to reproduce
After I have installed python-escpos, and try to run as documented, I am getting an error:

```
from escpos.printer import Usb
Usb(0x04b8, 0x0e11)
```

> usb.core.NoBackendError: No backend available

1. After some more digging, I found [this wiki page](https://github.com/libusb/libusb/wiki/Windows), according to this I need to Use the most recent version of Zadig, an Automated Driver Installer GUI application for WinUSB, libusb-win32 and libusbK.

    So, I downloaded Zadig; from the drop-down menu selected TM-82, and chose WinUSB to replace the driver and installed the driver succesfully.

    After that again I ran the same python-escpos documented command from above, and got the same error:

    > usb.core.NoBackendError: No backend available

2. After some more research I found [this answer on stackoverflow](https://stackoverflow.com/questions/33972145/pyusb-on-windows-8-1-no-backend-available-how-to-install-libusb/34720024#34720024). 
    So following the answer, I downloaded the libusb zip file, and copied `libusb-1.0.20_2\MS64\dll\libusb-1.0.lib` to my `C:\Windows\System32`. And finally copied` libusb-1.0.20_2\MS64\static\libusb-1.0.lib` to `C:\Python27\libs\`

    After that again I ran the same python-escpos documented command from above, and this time I got a different error:

    > NotImplementedError: Operation not supported or unimplemented on this platform

What am I missing here? Could you please help me. Thank you.

### Device info

 **Printer:** Epson POS TM-82

 **python-escpos version:** 2.2.0

 **python version:** 2.7.15 (64 bit)

 **operating system:** windows 7 (64 bit)

**Comment by fnlnfv** [comment]
I had the same error on Python 3.7 with Windows 10 64 bit.
This worked for me: https://stackoverflow.com/a/31332121

**Comment by patkan** [comment]
Thank you for the thorough writeup! Indeed, Windows support is not really existing at the moment. A first fix is probably to exclude this piece of code from execution on windows.
