### ISSUE TITLE
Printing a GIF 

### ISSUE THREAD

**Issue by eloydegen** [python-escpos/python-escpos#317]
**Printer:** Wincor Nixdorf TH230+
 **python version:** Python 3.6.3
 **operating system:** Xubuntu

I'm trying to print a GIF, but the it is printing garbage characters when I try to print a GIF with this code snippet. Regular text output works fine. 

```from escpos import *
p = printer.File("/dev/usb/lp1")
p.image("logo.gif")
p.cut()
```

The printer is initialized as USB (not with a serial adapter!), with the following code: 

```
p = printer.Usb(0x0AA7, 0x0304, 5, profile="Default")
p.image("logo.gif")
```

But it prints this error:
```Traceback (most recent call last):
  File "./ser.py", line 10, in <module>
    p = printer.Usb(0x0AA7, 0x0304, 5, profile="Default")
  File "/home/eloy/.local/lib/python3.6/site-packages/escpos/printer.py", line 45, in __init__
    Escpos.__init__(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'profile'
```

Yes, the iInterface seems to be 5 according to lsusb, but loading a generic profile does not seem to work. 

I am not sure what I am doing wrong, any help would be appreciated!

**Comment by patkan** [comment]
Could you tell me please which version of python-escpos you have installed. I suspect that this is an older version that does not support the profile argument.

**Comment by eloydegen** [comment]
It seems that all versions newer than 2.2.0 are marked as pre-release in PiPy, that's why `pip3` installed 2.2.0 from 2016. My problem is solved now, but maybe these newer packages should be marked as a release because the documentation is updated for newer versions.

**Comment by eloydegen** [comment]
Actually, the problem is not solved and the printer is still printing garbage when I try to print a GIF. Any clue what the cause could be? I'm now using the default profile from the escpos-printer-db. I also tried using a different profile, that had the same effect.

**Comment by patkan** [comment]
Version 3 has no release yet, because the API is not cleaned up and I would prefer to not make breaking API changes. But definitely, you are right, the mismatch between documentation and default package is not nice.

Have you already tried the three available implementations for image?
```
impl="bitImageRaster"
impl="graphics"
impl="bitImageColumn"
```
Apart from that I know that some images cause erroneous output. I could not compare yet what exactly is the problem with some images, so I can only say that a problem exists.
You could try to boil your GIF down to a minimal example.

**Comment by eloydegen** [comment]
Thanks! `bitImageColumn` fixed it, I can now print images. I will try to make a pull request for the `escpos-printer-db` project so a profile for the Wincor Nixdorf TH230+ will be added.
