### ISSUE TITLE
Question: Implementing a win32printer based front  

### ISSUE THREAD

**Issue by ramonpoca** [python-escpos/python-escpos#319]
Hi there,

I've been glancing over the source code, and wondering if another front-end using win32printer would be possible. Setting up the printer in windows accepting RAW input, we could do:

```
printer = Win32("My Printer queue")
```

Obviously this would imply a dependency on pywin32 (just on Windows).

What methods should be overriden from escpos for that?

**Comment by ramonpoca** [comment]
I've implemented support for it on #320. Tested on simulator.

**Comment by om26er** [comment]
Lets close this one as https://github.com/python-escpos/python-escpos/pull/320 landed a few days ago.
