### ISSUE TITLE
how to implementation in programming lazarus ?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [python-escpos/python-escpos#32]
```
os : linux

```

Original issue reported on code.google.com by `ali.ferd...@gmail.com` on 14 Jun 2014 at 7:55

**Comment by patkan** [comment]
Lazarus seems to be an IDE for Free Pascal. (http://wiki.freepascal.org/) I don't think that this issue is of any use and I also don't think that this will ever reach the original poster.
Closing this...
