### ISSUE TITLE
Epson TM-20II characterset

### ISSUE THREAD

**Issue by Cuningan** [python-escpos/python-escpos#321]
Hello.

I am trying to print an € symbol but I am unlucky.

I am just issuing to the printer this code:

P.characterset("EURO")
P.text(" €\n")
P.cut()

And I am obtaining a different character, like a dot.

I have also tried p.text(chr(213)) with and results.

Where can I find the character tables used by the library?

Any of you knows what I am doing bad?

**Comment by patkan** [comment]
Are you sure that your printer supports this character? And if yes, you could find out which sequence you have to send and send it with the `._raw()`method.

The encoding is handled by the `magic_encode` module. The character tables are defined in profiles in this project: https://github.com/receipt-print-hq/escpos-printer-db.
If you select the appropriate profile in your constructor, it should automatically handle the encoding.

**Comment by patkan** [comment]
Have you found a solution to your issue?

**Comment by Cuningan** [comment]
Yes, I found a solution.

I needed to fix the character set of the Linux box.

The problem is that python interpreter tries to parse the string using the Linux box character set if the character set does not support the symbol it fails.
