### ISSUE TITLE
There is some wheel package of this repository

### ISSUE THREAD

**Issue by hitokiri** [python-escpos/python-escpos#323]
Hello, I would like to know if there is a distribution wheel package for this repository, since I try to generate it but I get the following error.

FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/folder/lib/python3.5/site-packages/escpos/capabilities.json'

**Comment by patkan** [comment]
Hello,
your original problem is probably that you did not do a recursive clone. (`git clone --recursive`) Consequently, the capabilities submodule is not initialized. You should be able to fix this with `git submodule init` and `git submodule update`.

Apart from that, the project is available from pypi: https://pypi.org/project/python-escpos/3.0a4/ So you should be able to do a normal install with pip.
