### ISSUE TITLE
USB printer not printing on Respbian on respberry pi zero.

### ISSUE THREAD

**Issue by DrakeAaditya** [python-escpos/python-escpos#324]
I have:
- [x] searched open and closed issues for duplicates

### Bug description
Working fine on ubuntu 18.10 but does not work on respbian
giving no error on respbian but not printing anything on paper

 **python-escpos version:** latest

 **python version:** 3.6

 **operating system:** Respbian

**Comment by patkan** [comment]
Could you please provide more information? How is the printer connected, what kind of printer do you have? Do have the same rights considering hardware access as on your Ubuntu-machine?

**Comment by DrakeAaditya** [comment]
Yeah sure,
The printer is connected with usb B to usb A connector, with usb A to Respberry and USB B in printer

And Yes i have all the rights as the printer sometimes works and sometime it doesn't.

Working to not working ratio is on 1:4

**Comment by patkan** [comment]
Where you able to solve your problem?
If not, have you checked your dmesg, if there are any issues? Maybe your power supply is failing when printing? What kind of printer is this?

**Comment by DrakeAaditya** [comment]
Thanks for replying, the only issue was that, i was having issue with printing 1 or 2 words. but worked fine with couple paras.
