### ISSUE TITLE
Heating settings

### ISSUE THREAD

**Issue by aleray** [python-escpos/python-escpos#326]
Hi,

this is more a question: I got a H58 Printer USB which I use to print bitmap images. Unfortunately the quality is bad because the paper is overheated at the moment.

Is there some way in python-escpos or ecspos itself to set the heating values? I have used Adafruit minithermal printer before and this was something possible.

thanks for your answer,

Alex

**Comment by patkan** [comment]
Hi,
your first step should be to check if there is a manual describing the supported escpos commands. There is no definitive standard, so it is difficult to say if your device supports such a configuration.
If you know a sequence that has to be sent, this should not be an issue. Even if there is no such feature implemented, you could just send raw data. (method `_raw()`)

**Comment by patkan** [comment]
Where you able to find a solution to your problem?

**Comment by patkan** [comment]
You could check if your printer supports any ESC ( K commands.
