### ISSUE TITLE
Printer.text() method, no errors, no print

### ISSUE THREAD

**Issue by lingtjien** [python-escpos/python-escpos#327]
### Bug description
Printer.text() method gives no errors but the printer does not print either

### Steps taken
1. `echo hi > /dev/usb/lp0`
2. execute the script
```
#!/bin/python

from escpos import printer as Printer

printer = Printer.Usb(0x0483,0x5743) # lsusb

printer.text("hi")
```
3. check usb devices `ls /dev/usb`

### Observed
- In step 1 everything goes as expected and the printer prints the text.
- In step 2 nothing is printed by the printer, the printer seems to ignore the text.
- In step 3 observe that the printer is no longer available as `/dev/usb/lp0` is this normal? Because when I try `printer.cut()` instead of `printer.text()` the printer does cut the paper but it's also removed from `/dev/usb`

### Device info
Archlinux latest packages,
printer by STMicroelectronics, some generic Chinese 80mm POS printer (I don't know the exact number but I do have access to the programmer manual)

**Comment by patkan** [comment]
Have you tried sending a newline to the printer? Typically, a printer will only print full lines.

Apart from that, if you know a certain sequence of symbols that should definitely work, you can try to send them with `printer._raw()`.

**Comment by lingtjien** [comment]
I didn't think of that but that's a very good point and after trying it with a newline it seems to work fine so thank you.
