### ISSUE TITLE
black mark setting

### ISSUE THREAD

**Issue by rnnu08** [python-escpos/python-escpos#334]
I have: I need to implement the black mark cutting function. and i found that i need to set the parameters related to the black mark in advance to achieve.I found software on the Internet that does this, but it is not suitable for my device.

Its setting is as follows：
![](https://i.loli.net/2019/06/10/5cfe13ccdded485493.png)

How to achieve this function

- [ ] searched open and closed issues for duplicates

### Device info

 **Printer:**  EPSON TM-T88IIIP

 **python-escpos version:** 2.2.0

 **python version:** 3.6

 operating system:ubuntu

**Comment by patkan** [comment]
Dear @rnnu08 thank you for the issue.
I am not aware that this printer is capable of cutting at a mark. If you are sure that your printer is able to perform this action, you can try to obtain the set of commands that are needed from the manufacturer of the printer. If this is not possible you could sniff the communication between printer and PC.

If you have a set of commands, I can help you through implementing this as a function.

**Comment by rnnu08** [comment]
> Dear @rnnu08 thank you for the issue.
> I am not aware that this printer is capable of cutting at a mark. If you are sure that your printer is able to perform this action, you can try to obtain the set of commands that are needed from the manufacturer of the printer. If this is not possible you could sniff the communication between printer and PC.
> 
> If you have a set of commands, I can help you through implementing this as a function.

thank you for your reply
My device seems to support black mark，Can see that it has BM：
![IMG_20190612_002723.jpg](https://i.loli.net/2019/06/12/5cffd87ba00de13658.jpg)
and  I found a solution like mike42/escpos-php#284,but it not work in my device,
I tried the use esc/pos command,but I failed.


that is esc/pos commands:
![DevGuide_page-0041.jpg](https://i.loli.net/2019/06/12/5cffdbf43446d81970.jpg)
![DevGuide_page-0039.jpg](https://i.loli.net/2019/06/12/5cffdbf47847b96522.jpg)
![DevGuide_page-0042.jpg](https://i.loli.net/2019/06/12/5cffdbf48bb4f73207.jpg)
![DevGuide_page-0038.jpg](https://i.loli.net/2019/06/12/5cffdbf49e22751269.jpg)
![DevGuide_page-0040.jpg](https://i.loli.net/2019/06/12/5cffdbf4b22cd42354.jpg)
![DevGuide_page-0043.jpg](https://i.loli.net/2019/06/12/5cffdbf4b4b7313721.jpg)

**Comment by patkan** [comment]
Thank you for the information. Since I can't find information on your TM-T88IIIP, I can't check it, but to me this seems like the normal paper sensor and not a cut mark sensor.

Nevertheless, if you can put together the command sequence that you assume your printer needs, you could send it with the `._raw()`-function of the printer object. If you need help with this step, put together the ASCII sequence and I will show you how to call raw with this information.

**Comment by rnnu08** [comment]
all right,do you konw which model support black mark cutting and paper is 80mm, i can try to buy that.

**Comment by patkan** [comment]
I am sorry, but I can't help you with that - I don't know any.

**Comment by patkan** [comment]
Feel free to reopen or comment should there be anything that I can help you with.
