### ISSUE TITLE
Printing Image

### ISSUE THREAD

**Issue by jwhit265** [python-escpos/python-escpos#337]
I have:
- [x] searched open and closed issues for duplicates

### Bug description
When attempting to send a receipt with an image to my receipt printer via network an error is received.

The following error is received:
TypeError: 'float' object cannot be interpreted as an integer

### Steps to reproduce
The following code is sent to the printer:
```Epson = printer.Network(printerip)
Epson.image("escpos-php.png")
Epson.cut()
```

### Device info
 **Printer:** TM-L90 LFC

 **python-escpos version:** 2.2.0

 **python version:** 3.6.8

 **operating system:** Windows 10 (1809)

**Comment by patkan** [comment]
Hello,
* when exactly does this happen? Which statement are you calling?
* could you please provide the stack traceback that should be printed when this error occurs?

Thank you!

**Comment by jwhit265** [comment]
Hi patkan,

This is the traceback I get back.

> Traceback (most recent call last):
  File ".\app\imagetest.py", line 6, in <module>
    Epson.image('escpos-php.png')
  File "C:\Users\whitakerj\receipt\WPy64-3680\python-3.6.8.amd64\lib\site-packages\escpos\escpos.py", line 110, in image
    self._convert_image(im)
  File "C:\Users\whitakerj\receipt\WPy64-3680\python-3.6.8.amd64\lib\site-packages\escpos\escpos.py", line 74, in _convert_image
    for i in range(im_border[0]):
TypeError: 'float' object cannot be interpreted as an integer

**Comment by mike42** [comment]
@jwhit265 - How did you install this?

A quick browse of our [releases](https://github.com/python-escpos/python-escpos/releases) shows that 2.2.0 refers to commit cbe3864, which [does not contain the `_convert_image` method referenced in your stack trace](https://github.com/python-escpos/python-escpos/blob/cbe38648f50dd42e25563bd8603953eaa13cb7f6/src/escpos/printer.py).

The newer implementation is quite different, so you may get different behaviour if you upgrade (see also: 59afcf778f34d52815954c603ef6740acc5dd8b2 / b45afbb29772d7eb040ce74df5d1887c652a06a1, which are the commits which replaced this back in April 2016).

**Comment by jwhit265** [comment]
@Mike42 - when installing didn’t specify version so I’m guessing it defaulted to the stable 2.2.0.

I have since upgraded to 3.0a4 and can now print images but now facing a strange delay in printing. If I send one command it prints immediately, but sending another a second later ends up in a 1 minute+ delay in printing. Is there a specific version of python that works best with 3.0a4

**Comment by patkan** [comment]
The library should work well with any recent version of python (2.7 and 3.4+).

Does this delay happen with any command? Could you please provide code that reproduces this issue?

**Comment by belono** [comment]
@jwhit265 you can try preprocessing the data with the Dummy printer:

```python
dummy = printer.Dummy()
epson = printer.Usb(your_args)  # or your real connection

dummy.image("escpos-php.png")
dummy.cut()

epson._raw(dummy.output)
```
Seems to speedup things, sometimes.

**Comment by jwhit265** [comment]
Never mind I think there seems be an issue with the way I'm running it through python flask.

**Comment by patkan** [comment]
OK, then I am closing this.
