### ISSUE TITLE
Delay with printing within python-flask app route

### ISSUE THREAD

**Issue by jwhit265** [python-escpos/python-escpos#344]
### Bug description
Running python-escpos functions within python-flask web application causes delay of 2+ minutes when printing receipt.

### Steps to reproduce
- create flask route containing basic python-escpos function
- run flask application and visit route
- receipt prints immediately on first and sometimes second visit to route
- subsequent prints results in 2+ minute delay
- receipt backlog will print immediately if flask app is stopped.
- If route is visited 10 times, 10 receipts will print immediately without delay if flask app is stopped
- this behavior does not occur with the stable version of python-escpos (2.2.0), the version where the delay occurs is only with 3.0a4. I require 3.0a4 to take advantage of text and image processing.

### Minimal Example

``` python
from flask import Flask, flash
from escpos import *
import PIL

app = Flask(__name__, template_folder='.')

@app.route('/')
def homepage():
  printerip = "192.168.3.197"
  Epson = printer.Network(printerip)
  Epson.text('CHARGING')
  Epson.cut()
  return 'printed'

if __name__ == '__main__':
  app.run(host='0.0.0.0', debug=True, port=80)
```

### Device info
 **Printer:** TM-L90 LFC

 **python-escpos version:** 3.0a4

 **python version:** 3.6.8

 **operating system:** Windows 10

**Comment by patkan** [comment]
Are there any features in flask that help tracking where something is hanging?
Apart from that this sounds to me as there is some issue with the network-printer-driver. It would be good if we can narrow this down a bit.

**Comment by jwhit265** [comment]
@patkan 
1. Not sure with the tracking will have to do some research.
2. I ran the following in a loop as you suggested:
```python
from escpos import *
import PIL
import time
t_end = time.time() + 60 * 15
while time.time() < t_end:
  printerip = "192.168.3.197"
  Epson = printer.Network(printerip)
  Epson.text('CHARGING')
  Epson.cut()
```
The first receipt printed immediately, the rest of the receipts were delayed by 20 seconds but all printed 1 after another. I received the following trackback when the look finished (something I didn't receiving with flask):

```
Traceback (most recent call last):
  File ".\app\main - Copy.py", line 7, in <module>
    Epson = printer.Network(printerip)
  File "C:\Users\whitakerj\receipt\WPy64-3680\python-3.6.8.amd64\lib\site-packages\escpos\printer.py", line 203, in __init__
    self.open()
  File "C:\Users\whitakerj\receipt\WPy64-3680\python-3.6.8.amd64\lib\site-packages\escpos\printer.py", line 209, in open
    self.device.connect((self.host, self.port))
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
Exception ignored in: <bound method Escpos.__del__ of <escpos.printer.Network object at 0x000002C974444748>>
Traceback (most recent call last):
  File "C:\Users\whitakerj\receipt\WPy64-3680\python-3.6.8.amd64\lib\site-packages\escpos\escpos.py", line 73, in __del__
  File "C:\Users\whitakerj\receipt\WPy64-3680\python-3.6.8.amd64\lib\site-packages\escpos\printer.py", line 225, in close
OSError: [WinError 10057] A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
```

**Comment by patkan** [comment]
You could add a call to the `close()`-method at the end of your statement. Otherwise I am not sure what happens when you continuously open new connections without closing them.

Also you can try reducing the timeout. Maybe your application is waiting the 60s timeout. While this does not fix your root issue, it might help reducing the hangup.

**Comment by patkan** [comment]
Where you able to solve your issue?

**Comment by jwhit265** [comment]
Hi patkan,

Sorry for the delay in responding! Yes I was able to use `close()` at the end of my code causing no delay. I however every so often receive the following errors:

> Exception ignored in: <bound method Escpos.__del__ of <escpos.printer.Network object at 0x0000025FDED3C208>>
Traceback (most recent call last):
  File "C:\WPy64-3680\python-3.6.8.amd64\lib\site-packages\escpos\escpos.py", line 73, in __del__
    self.close()
  File "C:\WPy64-3680\python-3.6.8.amd64\lib\site-packages\escpos\printer.py", line 225, in close
    self.device.shutdown(socket.SHUT_RDWR)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
Exception ignored in: <bound method Escpos.__del__ of <escpos.printer.Network object at 0x0000025FDEE735C0>>
Traceback (most recent call last):
  File "C:\WPy64-3680\python-3.6.8.amd64\lib\site-packages\escpos\escpos.py", line 73, in __del__
    self.close()
  File "C:\WPy64-3680\python-3.6.8.amd64\lib\site-packages\escpos\printer.py", line 225, in close
    self.device.shutdown(socket.SHUT_RDWR)
OSError: [WinError 10038] An operation was attempted on something that is not a socket

This however doesn't cause any problems with printing.

**Comment by sansal54** [comment]
> 
> 
> Hi patkan,
> 
> Sorry for the delay in responding! Yes I was able to use `close()` at the end of my code causing no delay. I however every so often receive the following errors:
> 
> > Exception ignored in: <bound method Escpos.**del** of <escpos.printer.Network object at 0x0000025FDED3C208>>
> > Traceback (most recent call last):
> > File "C:\WPy64-3680\python-3.6.8.amd64\lib\site-packages\escpos\escpos.py", line 73, in **del**
> > self.close()
> > File "C:\WPy64-3680\python-3.6.8.amd64\lib\site-packages\escpos\printer.py", line 225, in close
> > self.device.shutdown(socket.SHUT_RDWR)
> > OSError: [WinError 10038] An operation was attempted on something that is not a socket
> > Exception ignored in: <bound method Escpos.**del** of <escpos.printer.Network object at 0x0000025FDEE735C0>>
> > Traceback (most recent call last):
> > File "C:\WPy64-3680\python-3.6.8.amd64\lib\site-packages\escpos\escpos.py", line 73, in **del**
> > self.close()
> > File "C:\WPy64-3680\python-3.6.8.amd64\lib\site-packages\escpos\printer.py", line 225, in close
> > self.device.shutdown(socket.SHUT_RDWR)
> > OSError: [WinError 10038] An operation was attempted on something that is not a socket
> 
> This however doesn't cause any problems with printing.

in printer.py, socket close function is missing exception. I edited such and OSError disappeared :

def close(self):
        """ Close TCP connection """
        try: # connection may already be disconnected, so catch exceptions
            self.device.shutdown(socket.SHUT_RDWR) # a proper disconnect
        except socket.error:
            pass

        self.device.close()
