### ISSUE TITLE
ImportError: No module named usb.core

### ISSUE THREAD

**Issue by therealrobster** [python-escpos/python-escpos#347]
I have:
- [X ] searched open and closed issues for duplicates

### Bug description

Hi, I'm using Flask/Docker.  I add

`from from escpos.printer import Usb (as my line 2)`

the following error occurs:

```
web_1  |   File "/web/web/blueprints/webhook/views.py", line 2, in <module>
web_1  |     from escpos.printer import Usb
web_1  |   File "/usr/lib/python2.7/site-packages/escpos/printer.py", line 3, in <module>
web_1  |     import usb.core
web_1  | ImportError: No module named usb.core
```

### Device info
I have a printer called a POS-8250.  It's a cheapy from china and is epson compatible but I don't think this is a printer issue.

 **python-escpos version:** 0.0.0

 **python version:** 0.0
Python 2.7.16
AND
Python 3.6.8
(not sure why both are there in the docker image, but I'm targetting 3.x)

 **operating system:**
ubuntu 18.04

**Comment by therealrobster** [comment]
Just an update, this can be close.  I was not using the correct pip install.  In the end using the PROPER install via `python-escpos` in my requirements.txt solved this.

**Comment by patkan** [comment]
No problem, thank you for the update!
