### ISSUE TITLE
Print in italics

### ISSUE THREAD

**Issue by FrancoHawx** [python-escpos/python-escpos#355]
Hello, I would like to know if with ESC / POS it is possible to print a text in italics.
I know it can depend on the capabilities of the printer itself, but since this library does not support this particular style, I do not know how to implement it.
Is there a code in esc / pos in hexadecimal that can send the printer raw to generate italic text?

**Comment by lucasmyers97** [comment]
Was this ever addressed? Is there any way to print in italics using this API?

**Comment by belono** [comment]
Hi @lucasmyers97 .

Sadly, according to the official [documentation](https://download4.epson.biz/sec_pubs/pos/reference_en/escpos/esc_exclamation.html), the ESC/POS command set only supports bold (emphasis) and underline font styles. Therefore, python-escpos support the same font styles.

The only way to print in italics with this API would be to somehow render the desired text as an image and send it to the printer using the `image` command, but the result would likely not be as expected.

**Comment by lucasmyers97** [comment]
Thanks for the response! Does the `image` command allow one to print an image within a line of text? Or does it automatically start a newline?

**Comment by belono** [comment]
It starts and ends with a newline so, at least, you should render a complete line of text as image and then send it to the printer.
