### ISSUE TITLE
can't run the setup.py file 

### ISSUE THREAD

**Issue by trongnguyen1997** [python-escpos/python-escpos#357]
after doing all the set up of escpos in this tutorial https://python-escpos.readthedocs.io/en/latest/user/raspi.html
, I ran some examples program but didn't work.  
then I tried to execute the setup.py as in the install note said but I have faced the problem bellow.

pi@raspberrypi:~/battery/print/python-escpos-development $ sudo python3 setup.py build
Traceback (most recent call last):
  File "setup.py", line 109, in <module>
    'python-escpos = escpos.cli:main'
  File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 320, in __init__
    _Distribution.__init__(self, attrs)
  File "/usr/lib/python3.5/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 387, in finalize_options
    ep.load()(self, ep.name, value)
  File "/home/pi/battery/print/python-escpos-development/.eggs/setuptools_scm-3.3.3-py3.5.egg/setuptools_scm/integration.py", line 17, in version_keyword
  File "/home/pi/battery/print/python-escpos-development/.eggs/setuptools_scm-3.3.3-py3.5.egg/setuptools_scm/__init__.py", line 150, in get_version
  File "/home/pi/battery/print/python-escpos-development/.eggs/setuptools_scm-3.3.3-py3.5.egg/setuptools_scm/__init__.py", line 113, in _do_parse
LookupError: setuptools-scm was unable to detect version for '/home/pi/battery/print'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

**Comment by patkan** [comment]
Hi, thank you for your issue.
It seems to me that you are trying to build from a zip or something and not from a proper git repository (see the notice in your trace, which has been printed by setuptools_scm)

Also I don't quite see where you got the information, that you should run setup.py. Normally this should be possible with just installing from pypi. If you want to get the newest version, please install wiht `--pre`.

**Comment by trongnguyen1997** [comment]
thanks for your response,
I finally could make it through by installing from pypi
I tried to run the setup.py since I had read the INSTALL file that captured
and attached bellow.
the machine work anyway but I haven't figure out why the install file said
that.
[image: image.png]





HOÀNG TRỌNG NGUYÊN - 15DT3
--------------------
Khoa Điện Tử - Viễn Thông
*Department of Electronic and Telecommunication Engineering (ETE)*
*--------------------*
Trường ĐH Bách Khoa - ĐH Đà Nẵng
*Danang University of Science and Technology (DUT)*
---------------------
*Hugo English Club - DUT*

*---------------------*
Tel:     (+84)766582113
Gmail:  hoangtrongnguyen1997@gmail.com
Facebook: *https://www.facebook.com/hoangtrongnguyen1997
<https://www.facebook.com/hoangtrongnguyen1997>*



Vào Th 4, 7 thg 8, 2019 vào lúc 16:25 Patrick Kanzler <
notifications@github.com> đã viết:

**Comment by patkan** [comment]
Good to hear that you have managed to install the module.
I have updated the INSTALL file in order to reflect the current situation.
