### ISSUE TITLE
Serial paper_status doesn't exist?

### ISSUE THREAD

**Issue by Tony556** [python-escpos/python-escpos#359]
I have:
- [ X ] searched open and closed issues for duplicates

### Steps to reproduce
- Aquire Adafruit Mini Thermal Printer (CSN A2)
- Hook up to Raspi W 0 (or any USB->Serial, probably)
- Try to get the paper_status()

My test code

```
#!/usr/bin/python3


import sys

from escpos import printer

mine = printer.Serial(baudrate=19200, xonxoff=True)

# This does work
mine.qr("hey", size=5)


print(mine.device.__dict__.keys())
#dict_keys(['is_open', 'portstr', 'name', '_port', '_baudrate', '_bytesize', '_parity', '_stopbits', '_timeout', '_write_timeout', '_xonxoff', '_rtscts', '_dsrdtr', '_inter_byte_timeout', '_rs485_mode', '_rts_state', '_dtr_state', '_break_state', '_exclusive', 'fd', 'pipe_abort_read_r', 'pipe_abort_read_w', 'pipe_abort_write_r', 'pipe_abort_write_w'])

print(mine.__dict__.keys())
#dict_keys(['columns', 'devfile', 'baudrate', 'bytesize', 'timeout', 'parity', 'stopbits', 'xonxoff', 'dsrdtr', 'device'])

# And here's where it falls apart
print(mine.paper_status())
```

Error:
```
Traceback (most recent call last):
  File "./test.py", line 12, in <module>
    print(mine.paper_status())
AttributeError: 'Serial' object has no attribute 'paper_status'
```

# Important Note:

This does work on an Arduino with the Adafruit Thermal Printer Library

( https://github.com/adafruit/Adafruit-Thermal-Printer-Library )

Here's the code that asks for the paper status (and that is with the higher FW in that #if)

https://github.com/adafruit/Adafruit-Thermal-Printer-Library/blob/master/Adafruit_Thermal.cpp#L572

### Device info

 **Printer:** Adafruit Mini Thermal Printer (CSN A2)

Device Self Test: https://i.imgur.com/wUyTsYS.jpg

Printer "Version": GV2.09.08 20180627_R

 **python-escpos version:** 2.2.0

 **python version:** 3.7.3

 **operating system:** Raspbian/Debian ARM

**Comment by patkan** [comment]
OK, so your issue seems to be solved :-)
