### ISSUE TITLE
Problem with alignment QR and images in m-t530 printer

### ISSUE THREAD

**Issue by gigimon** [python-escpos/python-escpos#360]
I have:
- [x] searched open and closed issues for duplicates

### Bug description
I have a printer epson m-t530 and try to print qr codes and images with center align but this functional not work :( I saw this PR https://github.com/python-escpos/python-escpos/pull/250 and try check on latest master and still not work. QR code and images always in left but text alignment work fine. Moreover all text with left alignment crop partly (see photo)

### Steps to reproduce
```python
import escpos
from escpos import printer, constants

Epson = printer.File(devfile="/dev/usb/lp2")

Epson.set("left", "a")
Epson.textln("Left")
Epson.qr("test")
Epson.image("logo330.png")
Epson.ln(2)
Epson.textln('1KR3hWY5y56XGKfozxtDwhmQhrvd2v72iv1D9uM1CTjNnsKEu9oub72Gdr2u3eBYgxSu1365KZLCSY59Rq1GBNPG75Z5MsyehsaeqP1N9jpM68CDGg8GYF2BFMygfAqxPpdgatou1HZnaUm7omdHi5KbJfdSKGCyPGprZAJDng19yQ37C5kpNPfs3JQuLfKP5v97imQy4nUt1Aeqac4kziGxgycKzSSXPCsY2y331xywcB')
Epson.ln(2)
Epson.text(constants.CTL_HT)
Epson.textln('Text with tab')
Epson.ln(2)

Epson.set("right", "a")
Epson.textln("Right")
Epson.qr("REDEEM CODE: sdfsdfsdfsdfsdfsdfsd")
Epson.image("logo330.png")
Epson.ln(2)

Epson.set("center", "a")
Epson.textln("Center")
Epson.qr("test")
Epson.image("logo330.png")
Epson.ln(2)
Epson.hw('init')
Epson.textln('QR center arg')
Epson.qr('center qr', center=True)
Epson.image("logo330.png", center=True)

Epson.set('left', 'a')
Epson.textln('Check line spacing')
Epson.text(constants.LINESPACING_FUNCS[60])
Epson.textln('Text 60')
Epson.text(constants.LINESPACING_FUNCS[360])
Epson.textln('Text 360')
Epson.text(constants.LINESPACING_FUNCS[180])
Epson.textln('Text 180')

Epson.line_spacing(20)
Epson.textln('spacing 20')
Epson.line_spacing(60)
Epson.textln('spacing 60')

Epson.cut()
Epson.hw('init')
```
### Device info
 **Printer:** Epson M-T530

 **python-escpos version:** master

 **python version:** 3.5

 **operating system:** Linux

![2019-08-29 00 02 34](https://user-images.githubusercontent.com/297982/63892628-c40c8680-c9f0-11e9-8f21-bbdbd44f38dd.jpg)

**Comment by patkan** [comment]
What you can try is:
* print the self-test of the printer and see if it is properly aligned
* print the QR-code as image (but that of course doesn't help when image printing also has problems)
* see in the manual of your printer (Epson has coding-manuals for them) if there are options for moving or decreasing the size of your page
* if you find any useful commands, send them with the `_raw()`-function

**Comment by gigimon** [comment]
I found a problem. I add a new profile and all work, thx
