### ISSUE TITLE
Finding out printer status

### ISSUE THREAD

**Issue by jackkongjj** [python-escpos/python-escpos#363]
Hi, I have a simple Flask server runs on raspberry pi zero, which multi devices send request to print to a USB thermal printer.

Is there a way to know if the printer is busy, like in middle of printing from previous request, so I can have the new request on hold till is safe to print. 

My other solution is to put all the request into a background queue and have one worker mange the queue to print, which seem somewhat over kill.

**Comment by patkan** [comment]
As far as I know this might depend on the interface, but I think you cannot know if the printer is busy. (You could have a look if there is a command that gives you the current print status.)

I assume as long as you send your print as one sequence of characters and make sure that you do not access the interface at the same time, you should not have any collisions.

At least in the library we currently have no way of knowing if the printer is busy. If you find one, you could always create a PR.

**Comment by belono** [comment]
If a CUPS printer driver is available for your printer, you could install it via CUPS on your Rpi Zero and try #348, then send print jobs via python-escpos to the CUPS server.

We need testing and feedback for this feature, so any help will be appreciated.

**Comment by angelod1as** [comment]
Any solution to this? I'm in need to knowing if printer is busy or in standby.
