### ISSUE TITLE
Making beep sound

### ISSUE THREAD

**Issue by jackkongjj** [python-escpos/python-escpos#365]
I see there is BEEP constant, I tried _raw(BEEP), it doesn't do anything?

Any sample on how beep works?

**Comment by unnecessary-axiom** [comment]
As far as I know Beep is model specific. 

For example [these star models](http://www.starmicronics.com/support/mannualfolder/escpos_cm_en.pdf) (pg 4-187/PDF page 216) ring a buzzer if sent `GS BEEP` where BEEP in this library is the ASCII 0x7 BELL. 

Other [epson models](https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=212) don't use that command, instead beep using `( A 0x4 0x0 0x30` with some arguments.

**Comment by jackkongjj** [comment]
The printer I am using does come with testing app and driver for Windows, which it does produce beep noise.
I am asking what is the implementation for sending beep command, is it just _raw(BEEP)? Or I should try to send the same hex as the testing app comes with the printer.

**Comment by patkan** [comment]
Yes, you should be sending the hex sequence that  the testing app sends, because that is the only sequence that the printer probably knows.

**Comment by jackkongjj** [comment]
I played with nodejs lib for escpos, the [BEEP](https://github.com/song940/node-escpos/blob/master/commands.js#L277) command from that Lib works for my thermal printer. I trying to pass in the same string using _raw(), but not working. 
The function call provide number of beep and duration, not sure if that is something I need to pass in as well, https://github.com/song940/node-escpos/blob/master/printer.js#L708

Any suggestion what I should pass in?

**Comment by unnecessary-axiom** [comment]
It looks like they're sending `\x1b\x42` or `ESC B` then the arguments `n t` where `n` is the number of beeps and `t` is the sound length in t*100 milliseconds.

**Comment by jackkongjj** [comment]
Right, that is what I passed in to the _raw() but didn't beep at all. I didn't pass in the n and t, as I wasn't sure if that need to be hex as well or need to use uint.
