### ISSUE TITLE
bold text doesn't work

### ISSUE THREAD

**Issue by absormu** [python-escpos/python-escpos#372]
### Bug description
Error : set() got an unexpected keyword argument 'bold'

### Code

from escpos import *
""" Seiko Epson Corp. Receipt Printer (EPSON TM-T88III) """

def Cetak():
    try:

        try:
            p = printer.File("/dev/usb/lp0")
        except IOError as e:
            print('ioerror', e)

        # Print text
        p.set(bold=True)
        p.text("Hello World")

        p.cut(mode=u'FULL')
    except Exception as e:
        print('Errornya:',e)

Cetak()

### Device info 
 **Printer:** EPSON TM-T88III

 **python-escpos version:**python-escpos 2.2.0

 **python version:**3.6

 **operating system: **ubuntu 18.4

**Comment by patkan** [comment]
This is not a bug. The version that you are using has no bold-parameter: https://python-escpos.readthedocs.io/en/v2.2.0/api/escpos.html
