### ISSUE TITLE
Impossible to print Code 128 barcodes with FNC 1-4 symbols

### ISSUE THREAD

**Issue by Robert-K** [python-escpos/python-escpos#374]
I have:
- 

- [x] searched open and closed issues for duplicates
- [x] examined the barcode-validation / -printing code

### Bug description

Correct me if I'm wrong, but it seems like there's no way to print Code 128 barcodes with FNC 1-4 symbols. I tried various ways to input it ("{3" e.g.), but none seem to work ("not in a valid format").

Reference:
https://www.barcodefaq.com/1d/code-128/#Code-128CharacterSet 

### Device info

 **python-escpos version:** 3.0a6

**Comment by patkan** [comment]
Is python-escpos throwing an exception? or is the barcode not printed?
If python-escpos is throwing an exception about the format, you could try to supply [`check=False`](https://python-escpos.readthedocs.io/en/latest/api/escpos.html#escpos.escpos.Escpos.barcode).

**Comment by Robert-K** [comment]
Oh wow, I totally missed that parameter ^^"
Trying to print anything with "{3" in it used to result in an exception.
Now it just prints the string - no barcode.

**Comment by patkan** [comment]
Hmm, if I remember correctly this indicates that the printer could not make anything out of the inut you gave it. But to be honest, I am not sure.

Can you be sure, that the string that you are trying to print is conforming to how a Code 128 has to be formed?

**Comment by patkan** [comment]
No feedback
