### ISSUE TITLE
Printing from PDF

### ISSUE THREAD

**Issue by rangathedon** [python-escpos/python-escpos#377]
Can this library be used to print a pdf file directly to the printer? could not find any example on the same; please help

**Comment by rangathedon** [comment]
Posted earlier https://github.com/python-escpos/python-escpos/issues/376 but it was closed without even understanding the question

**Comment by patkan** [comment]
duplicate of #376

**Comment by rangathedon** [comment]
> 
> 
> duplicate of #376

really ridiculous, you are closing it as duplicate without understanding the issue :-(

**Comment by patkan** [comment]
I do not know why it should be ridiculuos to close a duplicate. After you have added additional information, I have reopened #376, so why should I keep this issue?

**Comment by rangathedon** [comment]
how would I know if it was reopened? It wasnt when I posted the other one;
thanks for the response on the other issue :-)
