### ISSUE TITLE
Finding the correct hex value for USB port?

### ISSUE THREAD

**Issue by therealrobster** [python-escpos/python-escpos#379]
I see this line:

    p = Usb(0x04b8, 0x0202, 0, profile="TM-T88III")

I can't for the life of me figure out how to get `0x04b8, 0x0202` but for my USB port?  There's no docs anywhere on this (that I can find after an hour of searching) so I thought I'd ask.  How can I find this?

I did an lsusb and got:

    Bus 001 Device 002: ID 0456:0808 Analog Devices, Inc. USB POS Printer 

Does this help?  Any advice would be great.  Thank you

### Device info
Hoin HOP E802 using CUPS and another docket printer's settings (working in linux)

 **python-escpos version:** 2.2.0

 **python version:** 3.75

 **operating system:**
Linux / Ubuntu 19.10

**Comment by belono** [comment]
Hi @therealrobster .

You say your printer is using CUPS, so you can try #348 that introduce a new CUPS printer connector to send pyescpos commands directly to a CUPS configured printer:

You'll need to update to that commit version to be able to use the feature:

`pip install -U git+git://github.com/python-escpos/python-escpos/pull/348/commits/f07d5e06109e37aa45a5a139f49f56d6399b98d3`.

Or, you can also download [my fork](https://github.com/belono/python-escpos) version and update trough the requirements.txt file:

`pip install -U  -r requirements.txt`

After update is finished, run:
```
import escpos.printer as printer

cups_conn = printer.CupsPrinter(printer_name="")  # Default CUPS printer
cups_conn.textln("Hello CUPS!")  # or any python-escpos command
cups_conn.close()
```
Note that a _printer_name_ argument must be supplied if your ESCPOS printer is not the default CUPS printer of the server.

Looking forward to your feedback.

Oh, and don't forget to install pycups before you start the update:
`pip install pycups`

**Comment by patkan** [comment]
Additionally for your original question:
Yes, this does help. The vendor and product ID is in the lsusb-line that you posted: `0456:0808`. That would translate to `0x0456` and `0x0808`. (Just a different representation for hexadecimal numbers).

**Comment by blinxe** [comment]
Hello,

For what it's worth, I have a device with the same VID/PID (although mine is sold as Hoin HOP H58) and I found out that the output endpoint is not 1 (the python-escpos default), but 3. So initialization looks like:
```python
p = Usb(0x0456, 0x0808, out_ep=3)
```

**Comment by mbay-ODW** [comment]
Had the same Excelvan Ho85 Printer and came through that issue here. However I had to add profile to out_ep to make it work:

`printer = Usb(0x0456, 0x0808, timeout=10,profile="TM-T88III",out_ep=3)`

![image](https://github.com/python-escpos/python-escpos/assets/58465677/e38ef8d2-0f98-4669-8497-859817eeaaa2)
