### ISSUE TITLE
usblp0 removed

### ISSUE THREAD

**Issue by MLGS** [python-escpos/python-escpos#387]
### Bug description
print by usb, usblp0 removed

log: 
usblp0 removed
usb 1-1.5: reset full-seep USB device number 11 using dwc_otg

### Steps to reproduce
- python3 test.py
- code here:
from escpos import *

""" Seiko Epson Corp. Receipt Printer (EPSON TM-T88III) """
p = printer.Usb(0x09c5, 0x0588, 0, out_ep=0x2)
print(p)
p.text("Hello World\n")
p.barcode("6484848575", "CODE128", function_type="B")
str = "123\n"
p.text(str)
p.qr("https://www.google.com")
p.cut()
p.close()

### Device info

 **Printer:** Manufacturer Kuai Mai LabelPrinter

 **python-escpos version:** 2.2.0
 **pyusb version:** 1.0.2
**pyserial version:** 3.4

 **python version:** 3.7

 **operating system:**centOS 7.7

**Comment by patkan** [comment]
Hi,
sorry, I don't understand your issue. As far as I get it you are telling, /dev/usblp01 is missing on your platform. In this case I am not sure, how we can help you.

**Comment by kesienajoel** [comment]
Hello i have the same issue, after executing the above code, dmesg | more shows "usblp0:removed".

**Comment by MLGS** [comment]
thank you



发自我的iPhone


------------------ Original ------------------
From: kesienajoel ***@***.***&gt;
Date: Sun,Jun 6,2021 1:55 PM
To: python-escpos/python-escpos ***@***.***&gt;
Cc: MLGS ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [python-escpos/python-escpos] usblp0 removed (#387)

**Comment by T0maas** [comment]
I have same issue, /dev/usb/lp0 disappears after using `Usb(0x04b8,0x0e2a)`.
Is there some workaround? How to re-add /dev/usb/lp0?

**Comment by bukowa** [comment]
Hey, I have same issue, 
```python
def printer_print(_text: str, retry=10):
    _p = Usb(
        idVendor=0x0416,
        idProduct=0x5011,
        profile="NT-5890K",
    )
    logger.info("Trying to print...")
    _p.text(_text)
    logger.info("Print success... (probably)")
    _p.close()
    del _p
```
After running this device is no longer accesible via `/dev/usb/lp0`. 
It was before running this code.

**Comment by bukowa** [comment]
> Sadly I don't own an USB ESC/POS printer but [this](https://github.com/pyusb/pyusb/issues/405#issuecomment-1015177125) comment at the [pyusb](https://github.com/pyusb/pyusb) library could be related to the root of this issue.
> 
> Hope this could be of help.

I still remember but had no chance to check, thank you
