### ISSUE TITLE
arabic codepage raspberry pi

### ISSUE THREAD

**Issue by sajjadaemmi** [python-escpos/python-escpos#393]
what is arabic or persian codepage in raspberry pi?

**Comment by patkan** [comment]
Hi, I'm sorry, but I don't understand your question. A arabic codepage is for example this one: https://en.wikipedia.org/wiki/Windows-1256.

The codepages should not be specific to the python platform. (And normally it should not be necessary to handle this manually in the lib)
For more information on how Unicode in Python works please refer to this article: https://docs.python.org/3/howto/unicode.html
As a reference you can also have a look at the documentation of `bytes.decode` in Python: https://docs.python.org/3/library/stdtypes.html#bytes.decode
