### ISSUE TITLE
Does not recognize my device

### ISSUE THREAD

**Issue by ernestoluciano** [python-escpos/python-escpos#403]
I have:
- [x] searched open and closed issues for duplicates

### Bug description
python3 -i
Python 3.8.3 (v3.8.3:6f8c8320e9, May 13 2020, 16:29:34) 
[Clang 6.0 (clang-600.0.57)] on darwin
>>> from escpos import printer; print(printer.Usb(0x0519, 0x0003))
<escpos.printer.Usb object at 0x10e7b2ac0>
>>> from escpos import printer; print(printer.Usb(1305, 3))
<escpos.printer.Usb object at 0x10e7e92e0>

### Steps to reproduce
from escpos import printer; print(printer.Usb(0x0519, 0x0003))

### Device info
Star TSP100

 **python-escpos version:** 2.2.0

 **python version:** 3.8.3

 **operating system:**
macOS Catalina

**Comment by ropraet** [comment]
Same issue.

**Comment by patkan** [comment]
Hi,
from the code that you have posted I cannot see any issues. You are telling python to print the printer object and it prints the printer object.

Could you please sum up, what you are expecting to happen or if there is any other error output?

**Comment by patkan** [comment]
Your device seems to be unsupported, please refer to #410 for more information.
