### ISSUE TITLE
Raspberry Pi: 'escpos' not a module

### ISSUE THREAD

**Issue by stevenbuehler** [python-escpos/python-escpos#404]
I have:
- [X] searched open and closed issues for duplicates

### Bug description
When trying to run the following:

```python
from escpos.printer import Usb
p = Usb(0x0416,0x5011,0x81,0x03)
p.text("Hello World\n")
p.barcode('1324354657687','EAN13',64,2,'','')
p.cut
```

Receive the following error under Python 3.7.3...

```
Traceback (most recent call last):
  File "escpos.py", line 1, in <module>
    from escpos.printer import Usb
  File "/home/steven/Documents/Scripts/escpos.py", line 1, in <module>
    from escpos.printer import Usb
ModuleNotFoundError: No module named 'escpos.printer'; 'escpos' is not a package
```

...and the following error in Python 2.7.16...

```
Traceback (most recent call last):
  File "escpos.py", line 1, in <module>
    from escpos.printer import Usb
  File "/home/steven/Documents/Scripts/escpos.py", line 1, in <module>
    from escpos.printer import Usb
ImportError: No module named printer
```

Configuration info:

- Raspberry Pi 4 (4 MB)
- python-escpos version 3.0a8
- Python version 2.7.16 and 3.7.3 (`python-escpos` installed under both versions using `pip` and `pip3`)
- OS: Linux 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
- Printer is a generic POS-5805DD

**Comment by J-VdS** [comment]
Try renaming your python script. 
The name of the script is the same as the name of the module you are importing. This could cause funky behaviour.
