### ISSUE TITLE
Bluetooth or CUPS print queue support?

### ISSUE THREAD

**Issue by ghost** [python-escpos/python-escpos#405]
I've got a bluetooth-connected POS-5805DD that I can set up in CUPS using a `bluetooth://` url; is there a way to send `escpos` output to the CUPS queue?

**Comment by mike42** [comment]
Hi @stevenbuehler, there is no built-in way to do this at the moment, but it's possible to extend the `Escpos` class to write to different places.

You can find a code snippet in the discussion at #348 which runs the `lp` command to print to a CUPS printer.

**Comment by stevenbuehler** [comment]
I figured out I could use `rfcomm` to create the `/dev/rfcomm0` device file and use `printer.File('/dev/rfcomm0'). 😁

**Comment by belono** [comment]
Hi @stevenbuehler 

Give a try to the new CUPS printer connector at #348 .
You can find instructions [here](https://github.com/python-escpos/python-escpos/issues/379#issuecomment-595474050) on how to install or update to that commit version.

Don't doubt to ask for help if needed.
Any feedback will be appreciated.

**Comment by dubaleeiro** [comment]
Hello @ghost, could you please ellaborate a bit more on how you send escpos printing information over bluetooth and rfcomm? Tks !
