### ISSUE TITLE
status reads very slow on Serial printers

### ISSUE THREAD

**Issue by drakorg** [python-escpos/python-escpos#407]
Hi, I came across an issue where I found my application stalling when reading printer statuses. Looking at the sources I found that there is a 1 second sleep between the write and the read for status requests. I guess it was meant to give time to the printer to answer back. I understand the motivation, but in practice the same effect of "giving time" is achieved by the timeout parameter in when constructing the Serial() object, with the benefit that the program would only pay the price of the delay (up to 1 second delay in this case) if the printer actually took that time to respond. In practice this is rarely the case, and the reads return almost immediately, with the expected data.

Removing the sleep did the trick for me (reduced printing times by many seconds each time), maybe you could review the current approach and make this change permanent.

Thanks.
Regards.
Eduardo

**Comment by patkan** [comment]
Thank you for the issue!
Pull requests are always welcome 😉

**Comment by belono** [comment]
Thanks @drakorg  for the issue.

@patkan I think #534 fixes it without harming other connectors or in case of the timeout parameter is set to zero.

**Comment by drakorg** [comment]
Hi, sorry to bother again with this, but you can safely remove the sleep
for good. The waiting is done by the timeout parameter of the read itself,
it doesn't need the extra dead time.  If the printer needs some time to
answer, you can set the timeout appropriately, there's no need, point, or
gain for the sleep, it's just a waste of thread's time.
With the current fix's approach of setting a sleep of .1, 10 reads would
still again sum up another second where your program is just waiting, for
nothing.
Please remove the sleep altogether, you don't need it.
Thank you.
Best regards.

**Comment by belono** [comment]
Ok, I will update the PR deleting the sleep as you state it is safe to remove.

Thank you for the feedback and the fast response. ;-)
Cheers!!

**Comment by drakorg** [comment]
No thank you instead :-)
Cheers!!
