### ISSUE TITLE
slow down printing 

### ISSUE THREAD

**Issue by chrislos** [python-escpos/python-escpos#408]
Hey,

thanks for the nice library. I'm wondering if there's a possiblity (flag or parameter) to slow down image printing? 
For a media installation that runs over a day I'd like to slow down the printing speed of my epson TM 88.

thanks in advace,
christian

**Comment by patkan** [comment]
Currently implemented: I don't think so. Depending on what you want to slow down you could always add artifical waits into the code.

If you want to reduce the actual printing speed, you could try to read in the escpos manual for the TM88 (which version?) and see if you can find such a command. If yes, you could experiment by sending this command with the `_raw()`-method.
