### ISSUE TITLE
xml encoder?

### ISSUE THREAD

**Issue by ayushin** [python-escpos/python-escpos#409]
Hi guys, great project, I wonder if anybody is using it to encode/render XML/HTML receipts with ESCPOS?

This seems to be a great idea:

https://pypi.org/project/python-escpos-xml/

.. but unfortunately seem to be discontinued.

Anybody working on something similar?

**Comment by patkan** [comment]
Hi, something similar but also not continued is this lib here: https://github.com/miracle2k/py-xml-escpos by @miracle2k
