### ISSUE TITLE
printer.close issue 

### ISSUE THREAD

**Issue by reda1987** [python-escpos/python-escpos#417]
this Code working well for first print only but on second print give me the below error
I tried close and close()
*******************************************************************************************
***error***
***********

Exception ignored in: <function Escpos.__del__ at 0x000001C610C36EE0>
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\escpos\escpos.py", line 46, in __del__
    self.close()
  File "C:\Python38\lib\site-packages\escpos\printer.py", line 214, in close
    self.device.shutdown(socket.SHUT_RDWR)
OSError: [WinError 10057] A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied

*******************************************************************************************
*********
**Code**
*********
#for printerIp in printers:
    # print(orderId)
    for orderId in orders:
        URL     = 'URL'+printerIp+'/'+orderId
        imageName = printerIp+'-'+orderId+".png"         
        try:                
                printer = Network(printerIp, port=9100, timeout=5)
                printer.image(getImage(URL,imageName))
                printer.cut('PART')
                #printer.close
                printer.close()
                print('order has been printer'+printerIp +'/'+ orderId)
        except Exception:
                print("unacpected error"+printerIp +'/'+ orderId)

**Comment by patkan** [comment]
Hi, could you please correct your indentation? This makes it otherwise hard to read and guess.

`close()` should definitely be more correct than `close`

**Comment by patkan** [comment]
Also,this might be related to #344

**Comment by belono** [comment]
@patkan this issue was fixed by #431 merged at v.3.0a9.
It works for me without a glitch, so you can close as completed.

**Comment by patkan** [comment]
@belono thank you for the confirmation!
