### ISSUE TITLE
Directory for Image

### ISSUE THREAD

**Issue by ale13137** [python-escpos/python-escpos#426]
I have:
- [X] searched open and closed issues for duplicates

### Bug description
Hello all,
I am haviung troubles in importing the image to print. 
So, for instance, I added in the one and only folder of my Raspberry Pi 4 model B a jpg image called "iosonomalto.jpg"
Below i copied the error message.
For sure I messed up something with directory and folder to add images but i cannot understand how to tackle the problem.
I know it is something trivial yet I do not know how to solve it

### Steps to reproduce
 File "test.oy", line 4, in <module>
    p.image("iosonomalto.jpg")
  File "/usr/local/lib/python3.7/dist-packages/escpos/escpos.py", line 83, in image
    im = EscposImage(img_source)
  File "/usr/local/lib/python3.7/dist-packages/escpos/image.py", line 37, in init
    img_original = Image.open(img_source)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'iosonomalto.jpg'

**Comment by patkan** [comment]
Hi,
if you could add a minimal working example of code that leads to this problem, it would be easier to track it down. From the error message I assume that this likely has nothing to do with the library, but we can have a look. You should probably make sure that the image is in the current working directory from which you are calling your script. Otherwise, try to get accustomed with how files are opened in python in general, as this is what the library does internally.

**Comment by ale13137** [comment]
![e0fd4915-9f26-44e8-b14a-21162a7ced53](https://user-images.githubusercontent.com/73106995/96441933-9e50cb00-120a-11eb-9ac5-55b4ede276b4.jpg)

Thank you patkan.

I mean does the image should be placed in the same folder as the script?

That is a screenshot of the folder in which the script is placed and script test is as follows:

from escpos import *

p = printer.Usb(0x04b8,0x0202)
p.image("iosonomalto.jpg")
p.cut()

**Comment by patkan** [comment]
If you call it like this, you will have to place the image in the directory in which your script is executed. (Which is not necessarily the same as the directory in which your script is placed)

**Comment by ale13137** [comment]
Thank you patkan.
Now I see what is wrong in my workflow.
I do need to practise and study the use of different directories
