### ISSUE TITLE
CODE128 Barcode length

### ISSUE THREAD

**Issue by geftactics** [python-escpos/python-escpos#428]
I am trying to

### Steps to reproduce
- print a CODE128 barcode on my TSP650ii printer
- This works: `p.barcode('{BS8245486fb9e', 'CODE128', function_type='B')`
- But this doesn't: `p.barcode('{BS8245486fb9ec99718', 'CODE128', function_type='B')`

### Device info

 **Printer:** ID 0519:0001 Star Micronics Co., LTD TSP654 (ESP-001)

 **python-escpos version:** 2.2.0

 **python version:** 3.8.6

 **operating system:** MacOS

I guess as barcode is handled by the printer itself, the limitation may be there? If so, does anyone have an example of using `python-barcode` sending data into escpos image() ?

Cheers

**Comment by patkan** [comment]
Please check closely that the second CODE128 barcode is actually correct. It might be the case that this printer simply does not render invalid barcodes.

Apart from that you can try out the soft_barcode function in newer versions of python-escpos (master of this repository or pre release from pypi). It does exactly that: call python-barcode, render an image and send it to the printer. (Alternatively you can have a look at the code, if you want to try it out with interfacing directly python-barcode)

**Comment by geftactics** [comment]
`soft_barcode()` to the rescue! Thanks!
