### ISSUE TITLE
Partial cut

### ISSUE THREAD

**Issue by GoogleCodeExporter** [python-escpos/python-escpos#44]
```
Also i could not find info on how to do partial cut

Epson.cut() for full cut is easy... but how do i do a partial?

my printer is a Epson TM-T88II
```

Original issue reported on code.google.com by `bo.herrm...@gmail.com` on 15 Mar 2015 at 4:03

**Comment by mentarus** [comment]
To do a partial cut use 
```
cut("PART")
```

**Comment by boelle** [comment]
oki, i thin the TM-T88II is not able to do partial cut, at least i cant find any documentation on it
