### ISSUE TITLE
Print over shared printer

### ISSUE THREAD

**Issue by aljimgar** [python-escpos/python-escpos#443]
Hi,
I'm trying to print over a shared printer in Windows, is this possible?
Could I print over \\192.168.0.5\printer ?

I have:
- [x ] searched open and closed issues for duplicates

Thank you

**Comment by belono** [comment]
Hi @aljimgar .

Since v.3.0a5 python-escpos supports printing through the win32 print queue thanks to #320, so if your printer is properly configured in Windows, you can send the commands as a print job using the `Win32Raw()` printer connector of the `printer` module.
