### ISSUE TITLE
The media.width.pixel field of the printer profile is not set. The center flag will have no effect.

### ISSUE THREAD

**Issue by angelod1as** [python-escpos/python-escpos#446]
I have:
- [x ] searched open and closed issues for duplicates

### Bug description
I think this might be a silly question but I couldn't find anything on the docs regarding printer profile.

When I print a image using `p.image`, each image fragment prints this to the console:

```
The media.width.pixel field of the printer profile is not set. The center flag will have no effect.
```

Last try it was about 20 lines of this phrase, as I was printing 3 long images (about 20 fragments of 500px)

How can I make it disappear?

### Steps to reproduce
- Initialize printer as seen below:
```
p = Usb(0x0416, 0x5011, in_ep=0x81, out_ep=0x03)
p.charcode("CP860")
```
- Print an image file using `p.image(image, fragment_height=500)`.
- See error

### Device info
 **Printer:** POS-5890C

 **python-escpos version:** 3.0a8

 **python version:** 3.8.5

 **operating system:** Pop_os

**Comment by H0yVoy** [comment]
You can define the printer profile when instantiating the printer, for example:

```
p = Usb(0x0416, 0x5011, in_ep=0x81, out_ep=0x03, profile="TM-T88II")
```

The profiles are sourced from here: https://github.com/receipt-print-hq/escpos-printer-db/blob/master/dist/capabilities.json

So in the case of your printer you probably want to instantiate it as:
```
p = Usb(0x0416, 0x5011, in_ep=0x81, out_ep=0x03, profile="POS-5890")
```
I don't see the POS-5890C in the database, but the POS-5890 is there. I'm assuming they're similar enough. Let me know if that works.

**Comment by angelod1as** [comment]
Worked like a CHARM, thanks!
