### ISSUE TITLE
Can not change set parameters

### ISSUE THREAD

**Issue by sansal54** [python-escpos/python-escpos#450]
I can normally print from Birch Bp-T3W printer without any problem. But When I need to change some parameter such as size or bold with the code 👍 

`adisyon_printer.set(codepage=None, size='2x', align='center', bold=True)`

it gives error, saying set is undefined. 

Python 3.8
python-escpos : latest

**Comment by patkan** [comment]
In V2.2 the set method does not have these parameters.
In v3 releases (currently up to v3.0a9) this is possible.
