### ISSUE TITLE
License is GPLv3 on pypi.org and automated license auditing tools

### ISSUE THREAD

**Issue by bitplane** [python-escpos/python-escpos#453]
The license for the project is incorrect on pypi.org - it's listed as GPLv3.

I had a panic attack when `liccheck` told me that I had a GPL violation in the receipt printer!

Can someone with access please fix it?

**Comment by patkan** [comment]
Hi @bitplane, I think `liccheck` is completely right on this as long as you are using this version: https://pypi.org/project/python-escpos/2.2.0/

I never got around up to now to finalize an API for 3.0 (for which I have contacted every registered author if we should change the license to MIT, see #171). So the MIT versions are only available as pre releases: https://pypi.org/project/python-escpos/#history
