### ISSUE TITLE
Unable to print dynamic text to printer got stcucked or not responding

### ISSUE THREAD

**Issue by sumanthreddy-a** [python-escpos/python-escpos#456]
### Steps to reproduce
from escpos.printer import Network
def give_print(text):
     print = Network("192.168.1.172")  # Printer IP Address
    print.set("CENTER", "A", "B")
    print.image(
        img_source="300.png")
    print.text(text)
    print.cut(

### Device info
 **Printer:** EPSON  

 **python-escpos version:** latest

 **python version:** 3.9

**Comment by belono** [comment]
Hi @sumanthreddy-a .

Only fails on dynamic text?
Does it print a hard-coded string?

**Comment by patkan** [comment]
No feedback
