### ISSUE TITLE
Windows Shared Printer Unable use

### ISSUE THREAD

**Issue by EngineerWill** [python-escpos/python-escpos#457]
# question
hi,I have a question

I want to use the raspberry PI to print a string of data, but I can't connect to the printer.

My printer is shared on a Windows computer
## 
* Device info
* Printer: EPSON L4150
* Share os： Windows10
* python-escpos version: latest
* python version: 3.7

**Comment by belono** [comment]
Hi @EngineerWill .

First, you must configure your remote printer in your Raspberry Pi's CUPS server, if you haven't done it yet, and assert it prints the test page, or any document, properly.
If you have other printers configured in CUPS, set the remote printer as the rpi's default printer.

After the remote printer is configured and working, you need to install pycups.
To install pycups via pip you'll need to install the CUPS development package for your system first:

> `sudo apt install libcups2-dev`
> `pip install -U pycups`

Now, you need to update the python-escpos version to the one in #348:

> ```pip install -U git+git://github.com/python-escpos/python-escpos/pull/348/commits/f07d5e06109e37aa45a5a139f49f56d6399b98d3```

Now you can use the experimental python-escpos CUPS connector, and send a job to the printer's queue:

Here's a snippet:
> ```
>import escpos.printer as printer
> 
> cups_conn = printer.CupsPrinter(printer_name="")  # Default CUPS printer
> cups_conn.textln("Hello CUPS!")  # or any python-escpos command
> cups_conn.close()```

If `Hello CUPS!` is printed by your remote printer, you are success.

Don't doubt to ask for help if needed.
Looking forward to your feedback.

**Comment by DudeWhereIsMyTardis** [comment]
Hello! I am using CUPS to print from a Raspberry Pi. I also have pycups installed, and I'm able to print documents properly (both the print page from CUPS as well as pdf documents using pycups). 

I wanted to use some ESC/POS commands but I followed the steps above and I couldn't get the string printed (but no error arose). In the terminal, it only said that the CUPS connection was closed.

I also tried the is_online() command, but then I had the "python escpos 'nonetype' object has no attribute query_status" attribute error. 

Any suggestions? Thanks in advance.

**Comment by belono** [comment]
Hi @DudeWhereIsMyTardis !

The instructions in this issue are a bit out of date,
Please follow these which add new parameters that allow the printer to connect to a remote server:

- Update to the last commit:
`pip install -U git+https://github.com/python-escpos/python-escpos.git@69e9dca761cbc2b03d5ae54865926482d8953b1d`

- Run replacing _<the_server_ip>_ with the Raspberry Pi ip:
```
import escpos.printer as printer

cups_conn = printer.CupsPrinter(printer_name="", host="<the_server_ip>", port=631)
cups_conn.textln("Hello CUPS!")  # or any python-escpos command
# more commands...
cups_conn.close()
```
If you confirm it worked, I will update the outdated instructions above.
Thanks in advance.

**Comment by DudeWhereIsMyTardis** [comment]
Hello @belono! Thank you for your fast reply.

- When replacing _<the_server_ip>_ with the Raspberry Pi ip, there was the following error `AtributeError: 'CupsPrinter' object has no attribute 'pending_job'`. 
- After that, I tried using the CUPS server host ip, namely `127.0.0.1`. The result was the same as before, no errors, and no printing, only `Closing CUPS connection to printer <printer_name>`.

**Comment by DudeWhereIsMyTardis** [comment]
Hello again @belono!
I contacted the printer manufacturer (I have a Vretti 420B Thermal Label Printer), and the reply was that this printer doesn't support ESC/POS commands. Nevertheless, thank you for your help.

**Comment by belono** [comment]
No problem @DudeWhereIsMyTardis !
Here we are if you ever get an ESC/POS compatible printer.
