### ISSUE TITLE
Is there a way to initialize the system default printer? the VID and PID are hard to get!

### ISSUE THREAD

**Issue by hui001** [python-escpos/python-escpos#460]
I have:
- [x] searched open and closed issues for duplicates

### Bug description
Is there a way to initialize the system default printer? The VID and PID is hard to get

**Comment by belono** [comment]
Hi @hui001 .

It depends on your system platform:

On Windows, you can use the [Win32Raw](https://github.com/python-escpos/python-escpos/blob/27b7ae8629e0f9ccebad383a27f180c7632628cc/src/escpos/printer.py#L359) connector

On Linux, follow [this](https://github.com/python-escpos/python-escpos/issues/457#issuecomment-885877627) instructions, that are valid for any Debian based distro.

Don't doubt to ask for help if needed.

**Comment by kedare** [comment]
To get the VID and PID on Linux it's quite easy with the `lsusb` command
