### ISSUE TITLE
T20II 003

### ISSUE THREAD

**Issue by H1GHWAvE** [python-escpos/python-escpos#47]
Hi,

I am using the TM20II 003 Version and i cannot find the printer in lsusb. Everything worked fine with the TM20II 002. Can someone help me with this issue?

Thanks,
H1GHWAvE

**Comment by piniyini** [comment]
I find it helps if you have the printer switched on and plugged before you switch on the computer.

Can you provide output from lsusb after doing this?

**Comment by H1GHWAvE** [comment]
I figured it out. It was in auto mode which does not work correctly.
Neither USB nor Ethernet were recognized. When i switched to USB mode it
worked fine.
