### ISSUE TITLE
Spacing in the image print

### ISSUE THREAD

**Issue by Joris73** [python-escpos/python-escpos#48]
When I print a picture (eg qrcode) I have lines which are in the picture.
![img_20150527_111104](https://cloud.githubusercontent.com/assets/2796439/7832775/dcb1d090-0461-11e5-92d3-6aad940afda9.jpg)

With official driver on mac, no problem (pdf):
![img_20150527_111131](https://cloud.githubusercontent.com/assets/2796439/7832794/f0e9f65a-0461-11e5-8c53-dfa7c1a91a74.jpg)

A solution ?

Thanks

**Comment by mentarus** [comment]
Having a similar issue on my GS-8030A printer. Lines seem to appear on the same place in the image files, but don't seems to be as regular as in the photos above though

**Comment by taylorstevens** [comment]
Same here, using Epson TM-T88V
