### ISSUE TITLE
Use a variable for Qr & Barcode data

### ISSUE THREAD

**Issue by aero9560** [python-escpos/python-escpos#483]
Hello
i would like to know how we can use a variable object for the data of Qr & barcode.
like 
var = "hello"
p.barcode('1324354657687', 'EAN13', 64, 2, '', '')
use var in place of '1324354657687'

p.qr("You can read  from your smartphone")
use var in place of "You can read from your smartphone"

Thanks

**Comment by BlakeAlvarez** [comment]
Hello, to use a variable, you simply replace the first argument with your variable.
 For example:
`
x = "Hello, nice to meet you"
p.qr(x, 0, 10)
`
where 0 is default error correction, and 10 is the size of the qr.
My printer only supports qr, but I assume that the same can be done with a normal barcode command as well.

I hope this helps and feel free to ask for clarification if I did not explain well enough.
