### ISSUE TITLE
CUPS support

### ISSUE THREAD

**Issue by SydneyOwl** [python-escpos/python-escpos#488]
Can we send data to cups server and print from there instead of usb or serial? I tried `Network` but seems not working. I also tried PR#348 but failed-perhaps it is incompatible for today's python-escpos.Any solutions?

**Comment by belono** [comment]
Hi @SydneyOwl 
The `Network` connector is not suitable for printing through a CUPS server. You should use the `CupsPrinter` connector at #348 , but since that PR hasn't been merged yet, you need to follow [these](https://github.com/python-escpos/python-escpos/issues/457#issuecomment-885877627) instructions to update your python-escpos installation to that commit. You should then be able to start sending commands to your ESC/POS printer's CUPS queue.

Please, let us know if that works for you.
Anyway, don't doubt to ask for help if needed.

**Comment by SydneyOwl** [comment]
Hello @belono ,
Since my machine works in offline mode so pip is unavailable, I tried `pip3 uninstall escpos` and pull your code from [here](https://github.com/belono/python-escpos/tree/f07d5e06109e37aa45a5a139f49f56d6399b98d3) which should be same and manually copied src/escpos to `/usr/local/lib/python3.7/dist-packages/`. Also I have to remove version-import part from `__init__.py` since it raises ImportError if escpos is not installed from PyPI as it said in sourcecode. However, it finally reached a TypeError:
```python
Traceback (most recent call last):
  File "/home/raspi-weather/rsp/flask_upload/tese.py", line 1, in <module>
    import escpos.printer as printer
  File "/usr/local/lib/python3.7/dist-packages/escpos/printer.py", line 18, in <module>
    from .escpos import Escpos
  File "/usr/local/lib/python3.7/dist-packages/escpos/escpos.py", line 48, in <module>
    from .magicencode import MagicEncode
  File "/usr/local/lib/python3.7/dist-packages/escpos/magicencode.py", line 23, in <module>
    from .codepages import CodePages
  File "/usr/local/lib/python3.7/dist-packages/escpos/codepages.py", line 1, in <module>
    from .capabilities import CAPABILITIES
  File "/usr/local/lib/python3.7/dist-packages/escpos/capabilities.py", line 47, in <module>
    PROFILES = CAPABILITIES['profiles']
TypeError: string indices must be integers
```
I'll try connecting my device to internet and using pip later. Thank you for your reply!

**Comment by SydneyOwl** [comment]
I use `pip install -U git+https://github.com/belono/python-escpos.git@f07d5e06109e37aa45a5a139f49f56d6399b98d3` instead of `pip install -U git+git://github.com/python-escpos/python-escpos/pull/348/commits/f07d5e06109e37aa45a5a139f49f56d6399b98d3`. Pip failed to clone pr via `git+git://`, so I used the former one.
I made some changes to your code (constructor of CupsPrinter(Escpos)) to enable connecting to remote CUPS server:
```python3
def __init__(self, host=None,port=None,printer_name=None, *args, **kwargs):
            Escpos.__init__(self, *args, **kwargs)
            if host!=None:
                cups.setServer(host)
            if port!=None:
                cups.setPort(port)
            self.conn = cups.Connection()
            self.tmpfile = None
            self.printer_name = printer_name
            self.job_name = ''
            self.pending_job = False
            self.open()
```
And according to your instruction I ran  
```python
import escpos.printer as printer

cups_conn = printer.CupsPrinter(host="192.168.2.1",port=631,printer_name="XP-58IIH")  # Default CUPS printer
cups_conn.textln("Hello CUPS!")  # or any python-escpos command
cups_conn.close()
```
It works!

Here are detailed info of my devices. Hope they're useful to you.
> CUPS server: raspi zero w, Linux raspberrypi 5.15.32+ #1538 Thu Mar 31 19:37:58 BST 2022 armv6l GNU/Linux
> Printer: XP-58IIH
> print request sender: an simple armv7l device based on armbian

**Comment by belono** [comment]
If I understood, my fork's version didn't work for you due to the lack of `.setServer()` and `.setPort()`.
What happened before you added them? Any exception thrown?

**Comment by SydneyOwl** [comment]
No exception thrown. This is just an enhancement for those who separated the print command sender and the print command processer.
For example, Raspi is the cups server and is only responsible for receiving printing instructions and performing printing operations. In other words, It will not print without receiving instructions. Therefore, the terminal (instruction sender) needs to specify the address and port of cups service to connect to raspi, then a series of operations can be performed by sending instructions to cups server. Or the default connection of ` CupsPrinter(Escpos)` will be localhost instead of raspi.

**Comment by belono** [comment]
Oh! So the raspi is a remote CUPS server on a lan, right?.
I will add `host` and `port` to the parameters of the `CupsPrinter` constructor to configure the `.setServer()` and `.setPort()` setters, but let them be optional via `args`, `kwargs` for convenience to maintain consistency with the `Win32Raw` class constructor.
Your feedback is being very helpful, thanks.

**Comment by SydneyOwl** [comment]
Glad that I could be of help😁
