### ISSUE TITLE
Print error in logs after printing images

### ISSUE THREAD

**Issue by crawfab** [python-escpos/python-escpos#492]
I have:
- [x] searched open and closed issues for duplicates
i cannot seem to get rid of this error it is running on a web app using flask 2.02 2.4.41-4ubuntu3.12
it doesn't happen straight away after the print and i think it is some kind of timeout that is causing it to occur 
any help would be greatly appricated

### Bug description
[wsgi:error] [pid 1385163:tid 140559440144128] [client**** ] Exception ignored in: <function Escpos.__del__ at 0x7fd6810d7280>
[wsgi:error] [pid 1385163:tid 140559440144128] [client**** ] Traceback (most recent call last):
[wsgi:error] [pid 1385163:tid 140559440144128] [client**** ]   File "/usr/local/lib/python3.8/dist-packages/escpos/escpos.py", line 57, in __del__
[wsgi:error] [pid 1385163:tid 140559440144128] [client****]     self.close()
[wsgi:error] [pid 1385163:tid 140559440144128] [client******]   File "/usr/local/lib/python3.8/dist-packages/escpos/printer.py", line 244, in close
[wsgi:error] [pid 1385163:tid 140559440144128] [client 104.199.82.58:18706]     self.device.shutdown(socket.SHUT_RDWR)

### Steps to reproduce
office = Network(chaninfo[2])
office.image(rpath + orderidshort + "-reciept.png", high_density_vertical=True, high_density_horizontal=True, center=True)
office.cut()
## below was added to try and fix issue but it happens wether or not this line is here
office.close()
### Device info

Epson TM30II

 **python-escpos version:** 1.9

 **python version:** 3.8.10

 **operating system:**
ubunto 22.04 LTS

**Comment by patkan** [comment]
Hi, python-escpos 1.9 is a fork that has nothing to do with this project. Please feel free to reopen if issues arise also with the current v3.0
