### ISSUE TITLE
TypeError when importing the library

### ISSUE THREAD

**Issue by F3arRa1n** [python-escpos/python-escpos#494]
Hi,

I am using the following command to install the library:
`pip install git+https://github.com/python-escpos/python-escpos.git`

System: Windows 10 22H2
Python: 3.11.0

When I import the library, this error shows:
`File "C:\Users\fergp\AppData\Local\Programs\Python\Python311\Lib\site-packages\escpos\codepages.py", line 1, in <module>
    from .capabilities import CAPABILITIES
File "C:\Users\fergp\AppData\Local\Programs\Python\Python311\Lib\site-packages\escpos\capabilities.py", line 54, in <module>
    PROFILES: Dict[str, Any] = CAPABILITIES["profiles"]
                               ~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'`

I used that command because the version found at https://pypi.org/project/python-escpos/ is 2.2.0 and I need the centering of QR codes which 2.2.0 does not have.

I'll keep using 2.2.0 for the meantime and find a workaround, am just giving a headsup. 

Thanks for your work!

**Comment by belono** [comment]
Hi @F3arRa1n .

It looks like the capabilities data is missing during the installation on Windows. It's not following the sim-link to the data source, so a wrong capabilities.json file is generated.

I think you can workaround the error by manually copy a right populated _capabilities.json_ file into _site-packages/escpos/_ until we solve the problem.

Here you are one: [capabilities.json.zip](https://github.com/python-escpos/python-escpos/files/10061184/capabilities.json.zip)

Greetings!

**Comment by belono** [comment]
See #391 and #396 for more info about the missing capabilities.json file.

It seems that this is not fixed as we believed.

**Comment by patkan** [comment]
Upon closer look, I would assume that this is due to the fact that your checkout does not check out subprojects in git.

If you want to install a newer release, please use --pre with pypi which will allow you to install the pre-releaes that are available on pypi
