### ISSUE TITLE
Warning: missing lib... win32print

### ISSUE THREAD

**Issue by kdc1919** [python-escpos/python-escpos#495]
Good Day,
I'm having a bug issue which I hope someone can help me solve. I have TM-T20II Epson printer. Upon trying to get a simple print I'm getting the following error: - 

`
Warning: missing lib... win32print
`
 Here is the code I'm using :- 
`from escpos.printer import Usb

""" Seiko Epson Corp. Receipt Printer (EPSON TM-T88III) """
p = Usb(0x04B8, 0x0E15, 0)
p.text("Hello World\n")
p.barcode('1324354657687', 'EAN13', 64, 2, '', '')
p.cut()`

Is anyone having a similar error while trying to print on Windows 10?

![Error1](https://user-images.githubusercontent.com/80336444/205993017-cd20a450-d33f-4fc5-a50d-19281ba05eb9.PNG)

Regards,

Kevin

**Comment by belono** [comment]
Hi @kdc1919 !

I'm sorry but I don't have an USB printer, nor a Windows machine to reproduce the issue. Even so, the win32print library is an optional dependency of the [escpos.printer.Win32Raw()](https://github.com/python-escpos/python-escpos/blob/master/src/escpos/printer.py#L384) connector, but you are initializing an [escpos.printer.Usb()](https://github.com/python-escpos/python-escpos/blob/master/src/escpos/printer.py#L21) connector that makes use of the usb library that is throwing the exception. So, as far as I know, the exception is not related to the missing win32print lib. It seems more like wrong usb params in the initialization of the [escpos.printer.Usb()](https://github.com/python-escpos/python-escpos/blob/master/src/escpos/printer.py#L21) class, specifically the endpoint params.
