### ISSUE TITLE
usb.core.USBError: [Errno None] b'libusb0-dll:err [claim_interface] could not claim interface 0, invalid configuration 0\n'

### ISSUE THREAD

**Issue by Davidamgad2** [python-escpos/python-escpos#499]
I'm trying to use the library, but it gives exception :module 'serial' has no attribute 'PARITY_NONE'

At the start of the example code.

Thanks in advance!

Code:
from escpos.printer import Usb

""" Seiko Epson Corp. Receipt Printer (EPSON TM-T88III) """
p = Usb(0x1FC9, 0x2016)
p.text("Hello World\n")
p.image("logo.gif")
p.barcode('1324354657687', 'EAN13', 64, 2, '', '')
p.cut()

**Comment by Davidamgad2** [comment]
I fixed it by modifying the usb class for the constants to 0 for PARITY_NONE and 1 for the error of stopbits.

After that I have error says no backend available  I fixed it from [here ](https://stackoverflow.com/questions/13773132/pyusb-on-windows-no-backend-available)

Now, I have only one issue left that detach_kernel_driver

**Comment by belono** [comment]
Hi @Davidamgad2 .
Are you using a USB to Serial adapter?
In that case, you should use the `escpos.printer.Serial()` connector.

**Comment by Davidamgad2** [comment]
> Hi @Davidamgad2 . Are you using a USB to Serial adapter? In that case, you should use the `escpos.printer.Serial()` connector.

Thanks for your reply! 
No, the printer is connected to the laptop directly.

Also, kindly note I'm using windows 10 python 3.10.6. I attached a picture of the error.
![image](https://user-images.githubusercontent.com/111524016/209662387-14fc34d5-6eb3-4888-9b89-9d191d7f519f.png)

**Comment by Davidamgad2** [comment]
I fixed this issue from [here ](https://github.com/python-escpos/python-escpos/pull/349)

Now I have this issue: [Errno None] b'libusb0-dll:err [claim_interface] could not claim interface 0, invalid configuration 0\n'

**Comment by Davidamgad2** [comment]
I solved it by installing zadig and install the driver of my thermal printer as libusb-K
