### ISSUE TITLE
needs a method to set tab positions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [python-escpos/python-escpos#5]
```
What steps will reproduce the problem?
try and do a horizontal tab

What is the expected output? What do you see instead?
no output

What version of the product are you using? On what operating system?


Please provide any additional information below.

the horizontal and I think vertical tabs do nothing (or might do a line feed) 
until the tab positions have been set with ESC D <list of columns> null
```

Original issue reported on code.google.com by `alanbell...@gmail.com` on 15 Nov 2012 at 10:40

**Comment by patkan** [comment]
relevant: #161 and #27

**Comment by MicroJoe** [comment]
Proposed solution for a 32 columns-wide font:
```python
>>> solution = '{:<24}{:>8}\n'.format('left', 'right')
'left                    abcdabcd'
>>> p.text(solution)
```
Where 24 is the maximum character count of the left part and 8 is the maximum character count of the right part (24+8 = 32 columns). See [Python .format() examples](https://docs.python.org/2/library/string.html#format-examples).

We should draft something better than this hack for software tabs I think, but use this trick for implementation.
