### ISSUE TITLE
USB连接问题

### ISSUE THREAD

**Issue by ROTHSCHILD-CINITY** [python-escpos/python-escpos#503]
操作系统：windows10 64位
python版本：3.8.5
打印机：GPprinter D801
问题描述：打印机已安装驱动，通过打印机厂家的测试工具可实现打印机所有操作，但通过python-escpos无法查找到打印机，打印机权限已设定，printer.py需要屏蔽的代码已屏蔽，使用的是打印机厂家配置的USB线缆，具体代码如下：
                              from escpos.printer import Usb
                              p = Usb(0x0471,0x0055,timeout=15)
错误提示：
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    p = printer.Usb(0x0471,0x0055,timeout = 15)
  File "C:\Python\Python38\lib\site-packages\escpos\printer.py", line 52, in __init__
    self.open(usb_args)
  File "C:\Python\Python38\lib\site-packages\escpos\printer.py", line 61, in open
    raise USBNotFoundError("Device not found or cable not plugged in.")
escpos.exceptions.USBNotFoundError: USB device not found (Device not found or cable not plugged in.)

**Comment by DroneMesh** [comment]
Use Zadig.exe to change the driver of the printer to libusbk and then you can detect it and print with it.
