### ISSUE TITLE
help pls i cant connect using Network with flask

### ISSUE THREAD

**Issue by tsukiguni** [python-escpos/python-escpos#530]
I have:
- [ done ] searched open and closed issues for duplicates

### Bug description
i am trying to connect my POSSIFY FY825X on raspberry pi with ubuntu it works fine but when i try to connect inside Flask app
it gives request timed out error

`self.device.connect((self.host, self.port))
TimeoutError: timed out
`

### Steps to reproduce
- my printer ip is 192.168.1.25
- from flask import Flask
- from escpos.printer import Network
- app = Flask(__name__)
- p = Network("192.168.1.25")
- if __ name__ == "__main__":
-      app.run(debug= True)

### Device info

 **Printer:** POSSIFY FY825X

 **python-escpos version:** 2.2.0

 **python version:** 3.10.6

 **operating system:** Ubuntu 22.04.2 LTS

**Comment by tsukiguni** [comment]
it works fine alone but it gives error with flask

**Comment by patkan** [comment]
Hi, are you sure that the said flask app has the exactly same access to your network printer? (running on the same host, no docker, ...)
Is the connection from the script closed when you try to access from within the app?
If that doesn't help, please provide a script that demonstrates your issue, (even though the issue with the flask app might be out of scope of this project)

**Comment by tsukiguni** [comment]
Thanks for the return i am currently busy nowadays ill check them when ill be available

**Comment by tsukiguni** [comment]
Yes it has acces and i can make it work but its strange. I comment the line "p = Network(localip)" then run it, after the flask app starts i uncomment the line and flask restarts the app and works perfectly. Its manual and i cant keep it like that it wont work in production

**Comment by tsukiguni** [comment]
found the issue not from the package

**Comment by meepstertron** [comment]
What was the issue im having the same problem help aprechiated
