### ISSUE TITLE
ITF barcode is not printed

### ISSUE THREAD

**Issue by alfredo138923** [python-escpos/python-escpos#54]
Hi, I'm trying to print the barcode:  Interleaved 2 of 5 (ITF): *6110439551* 
using: **Epson.barcode('6110439551', 'ITF',64,2,'','')** 
but anything is printed. I have tried with EAN13 and it works but fails for ITF. Can somebody help me with this issue?.

Thanks in advance.

**Comment by patkan** [comment]
For me this prints just fine. @alfredo138923 could you please test the ITF-printing with the version in #98 (or with branch development after the PR has been merged)?

**Comment by alfredo138923** [comment]
It's working well in with branch development. Thanks
