### ISSUE TITLE
problem with my printer

### ISSUE THREAD

**Issue by dboira** [python-escpos/python-escpos#56]
Hello,
I followed all the steps you describe and I can't write with my printer (FENIX-INVICO).
I get this error message:

pi@raspi2 ~ $ python prn.py
Traceback (most recent call last):
  File "prn.py", line 6, in <module>
    fenix = escpos.Escpos(0x4651,0x0164,0,0x81,0x01)
TypeError: this constructor takes no arguments

This is my prn.py code

#!/usr/bin/env python

from escpos import *

#  """ Seiko Epson Corp. Receipt Printer M129 Definitions (EPSON TM-T88IV) """
fenix = escpos.Escpos(0x4651,0x0164,0,0x81,0x01)
fenix.text("Hello World")
#fenix.image("logo.gif")
#fenix.barcode
#  Epson.barcode('1324354657687','EAN13',64,2,'','')
fenix.cut()

I want to know if it is possible print with this printer.
My sistem is a raspberry pi:
Linux raspi2 3.18.11+ #781 PREEMPT Tue Apr 21 18:02:18 BST 2015 armv6l GNU/Linux

When I put some lsusb command I get a warning message:

pi@raspi2 ~ $ lsusb -vvv -d 4651:0164 | grep iInterface
Couldn't open device, some information will be missing
      iInterface              0

Thanks a lot for your help
Daniel B

**Comment by manpaz** [comment]
HI Daniel,

I'm not sure where you got that example code.
Please, make sure you are following the printer definition described in the wiki:
https://github.com/manpaz/python-escpos/wiki/Usage

For the printer you are using the code to define that printer should be like:
```
fenix = printer.Usb(0x4651,0x0164)
```

Thank you.

**Comment by dboira** [comment]
Hello,
thanks for your response;
previously, I also put that code:

fenix = printer.Usb(0x4651,0x0164)

with the same error.
But today I'll try again.

2015-08-06 0:05 GMT+02:00 manpaz <notifications@github.com>:

> HI Daniel,
>
> I'm not sure where you got that example code.
> Please, make sure you are following the printer definition described in
> the wiki:
> https://github.com/manpaz/python-escpos/wiki/Usage
>
> For the printer you are using the code to define that printer should be
> like:
>
> fenix = printer.Usb(0x4651,0x0164)
>
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/manpaz/python-escpos/issues/56#issuecomment-128163641>
> .
>



-- 
Daniel Boira
+34 661 15 84 38

**Comment by dboira** [comment]
I see now my mistake!!!
Then I try again with the correct code.

Thank you!

**Comment by dboira** [comment]
with corrected code:
#!/usr/bin/env python
from escpos import *

fenix = printer.Usb(0x4651,0x0164)
fenix.text("Hello World")
fenix.cut()

I get this error:
pi@raspi2 ~ $ python prn.py
Traceback (most recent call last):
  File "prn.py", line 6, in <module>
    fenix = printer.Usb(0x4651,0x0164)
  File "/usr/local/lib/python2.7/dist-packages/escpos/printer.py", line 34, in __init__
    self.open()
  File "/usr/local/lib/python2.7/dist-packages/escpos/printer.py", line 43, in open
    if self.device.is_kernel_driver_active(0):
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 992, in is_kernel_driver_active
    interface)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/__init__.py", line 363, in is_kernel_driver_active
    _not_implemented(self.is_kernel_driver_active)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/__init__.py", line 79, in _not_implemented
    raise NotImplementedError(func.__name__)
NotImplementedError: is_kernel_driver_active

**Comment by dboira** [comment]
I can print with generic printer:
fenix = printer.File("/dev/usb/lp0")

When I try insert set commands, etc. something goes wrong.
Sample python code:
#!/usr/bin/env python
from escpos import *

fenix = printer.File("/dev/usb/lp0")
#fenix = printer.Usb(0x4651,0x0164)
fenix.control("LF")
fenix.control("LF")
fenix.control("LF")
fenix.set('center', 'a','bold' , 1, 1)
fenix.text('First line')
fenix.control('LF')
fenix.control('LF')
fenix.control('CR')
fenix.set('CENTER', 'A','normal' , 1, 1)
fenix.text("Second line")
fenix.cut(mode='PART')


Printer begins to print over the previous cut and all control and set commands doesn't work.

Could you help me, please?
Thanks in advance.
