### ISSUE TITLE
When I print a receipt with images I get an error, please help.

### ISSUE THREAD

**Issue by SmokeDevil666** [python-escpos/python-escpos#571]
When I print a receipt with images I get an error, please help.
Once the receipt is printed normally, as it should, then there is an error

Bug description
The media.width.pixel field of the printer profile is not set. The center flag will have no effect.

Steps to reproduce
from escpos.printer import Network
from PIL import Image
import datetime

`class Printer:
    def __init__(self):
        try:
            self.printer = Network('192.168.0.6')
        except Exception as e:
            print(f"Ошибка в функции __init__ : {e}")

    def print_receipt_canteen(self, employee_username: str, menu: str) -> None:
        date, time = datetime.datetime.now().strftime("%d.%m.%Y"), datetime.datetime.now().strftime("%H:%M:%S")
        self.printer._raw(b"\x1b\x61\x01")  # Center-align text
        self.printer._raw(b"\x1b\x45\x01")  # Set bold text
        self.printer.image("media/images/logotip.bmp", impl="bitImageRaster")  # Add logo
        text = f'\n\n{" СТОЛОВАЯ ".center(len(" СТОЛОВАЯ ") + 24, "*")}\n' \
               f'\n{"ФИО:".ljust(14)}{employee_username.center(25)}' \
               f'\n{"Дата:".ljust(14)}{date.center(25)}' \
               f'\n{"Время:".ljust(14)}{time.center(25)}\n\n' \
               f'\n{"Меню:".ljust(14)}{menu.center(25)}\n\n' \
               f'{"-" * 40}\n\n'.encode("cp1251")
        self.printer._raw(text)
        image_path = f"media/images/{menu}.png"
        img = Image.open(image_path)
        new_width = 300
        new_height = 300
        img = img.resize((new_width, new_height))
        resized_image_path = f"media/images/resized_{menu}.png"
        img.save(resized_image_path)
        self.printer.image(resized_image_path, impl="bitImageRaster")
        self.printer.cut()`

Xprinter: Manufacturer Model XP-A160H

python-escpos version: 3.0a9

python version:** 3.10

operating system: Debian 10

**Comment by patkan** [comment]
Please verify you python-escpos version. To my knowledge there is no release 1.9

**Comment by SmokeDevil666** [comment]
> Please verify you python-escpos version. To my knowledge there is no release 1.9

Installed python-escpos==3.0a9 same error

**Comment by patkan** [comment]
How did you install that version? If it is really a version 1.9, then I guess that you have installed a fork and not this project.

**Comment by SmokeDevil666** [comment]
> How did you install that version? If it is really a version 1.9, then I guess that you have installed a fork and not this project.

In the requirements.txt file python-escpos==3.0a9

**Comment by SmokeDevil666** [comment]
> How did you install that version? If it is really a version 1.9, then I guess that you have installed a fork and not this project.

I set the desired width in pixels, the error disappeared, but after printing gunicorn restarts

class Printer:
    def __init__(self):
        try:
            self.printer = Network('192.168.72.6')
            self.printer.profile.profile_data["media"]["width"]["pixels"] = 576
        except Exception as e:
            print(f"Ошибка в функции __init__ : {e}")

**Comment by patkan** [comment]
Could you please give the traceback of the error? (Or did I miss it?)

**Comment by SmokeDevil666** [comment]
> Could you please give the traceback of the error? (Or did I miss it?)

After setting the width value in pixels, the error disappeared, but the problem with printing images remained the same, printing without images is successful, but I would like to print a receipt with images

**Comment by patkan** [comment]
I have read your issue again, but unfortunately I do not understand, which issue with printing images remains now?

**Comment by SmokeDevil666** [comment]
Thanks for your help, the problem turned out to be not with Python-escpos, I apologize..
