### ISSUE TITLE
pip package "python-escpos" wildly out of date

### ISSUE THREAD

**Issue by gilbertfl** [python-escpos/python-escpos#572]
I have:
- [x ] searched open and closed issues for duplicates

### Bug description
When installing with pip (as instructed in README.md), the package dates back to 2016.   The documentation is very different from the capabilities of that version.

[See the pipy page for proof](https://pypi.org/project/python-escpos/)

Suggested paths to repair:  
- update the pip package "python-escpos[all]" 
- change the installation method in readthedocs.

### Device info

 **python-escpos version:** 2.2.0

 **python version:** 3.11

 **operating system:**

**Comment by patkan** [comment]
Hi, please have a look at the pre-releases: https://pypi.org/project/python-escpos/3.0a9/

The issue is that there is no final release for v3 yet. If you follow the instructions from readthedocs, you can also install pre-releases, otherwise the doc is already written for v3, which will be released when the corresponding milestone is done.

**Comment by scott-r** [comment]
Related question: What is the status of the `escpos` package on PyPi, which also points here for its source repository? The current version `escpos 1.9` seems to have the same MagicEncoder functions as `python-escpos` 3.x, but only the CP437 encoding works. Looking to solve that problem, I found that the current master source here works correctly (apart from the minor bug I identified in issue #570).

@patkan I see that you are a maintainer for both projects. Do you plan to remove `escpos` from PyPi when `python-escpos 3.0` is released?

**Comment by patkan** [comment]
> Related question: What is the status of the `escpos` package on PyPi, which also points here for its source repository? The current version `escpos 1.9` seems to have the same MagicEncoder functions as `python-escpos` 3.x, but only the CP437 encoding works. Looking to solve that problem, I found that the current master source here works correctly (apart from the minor bug I identified in issue #570).
> 
> @patkan I see that you are a maintainer for both projects. Do you plan to remove `escpos` from PyPi when `python-escpos 3.0` is released?

Hi, that package has nothing to do with me.
The uploader has forked this project and not changed the meta data. I have asked him recently to remove that information and am hoping that he complies.
I am definitely not maintainer of this package and would recommend not to install it. (The code is not viewable as far as I see it)

**Comment by scott-r** [comment]
OK, that explains a lot. Thank you for the quick reply.

I think I’ll move to your current prerelease as soon as I can test it at my client’s site with the actual printer. Do you have any idea when the stable 3.0 version is likely to be released? Depending on what still needs to be completed, I might be in a position to offer some help.

**Comment by gilbertfl** [comment]
Thank you for the explanation.   I switched to the 3.0a9 pip package and now magicencode is functional!

I hope the road to the release milestone goes well.
