### ISSUE TITLE
No barcode printing with WinBond/Zjiang 5890

### ISSUE THREAD

**Issue by matiasw** [python-escpos/python-escpos#58]
Hi,
I'm having trouble with getting barcode printing to work: only the code gets printed, not the bars. My printer is this one: http://www.aliexpress.com/item/Free-shipping-New-mini-58mm-thermal-receipt-printer-ticket-pos-58-thermal-printer-USB-black-white/856027185.html
It is identified as `ATTRS{idVendor}=="0416", ATTRS{idProduct}=="aabb"` and text/image printing work.
Where should I look for the problem? I can see two ways around it: find and fix the issue where barcode is handled, or work around it by rendering the barcode to an image and printing that. I think the first one is simpler, would you agree?

**Comment by patkan** [comment]
Hi @matiasw. Do you know whether the printer speaks "real" esc/pos?
Have you already solved the problem?

**Comment by bmjbmj** [comment]
It took me a while to find the problem. My 5802LD from the same manufacture demands a NUL last in the data field. Python-escpos only sends 'self._raw(code)' NOT self._raw(code+'\0'). A work around is to use a line like: Zjiang.barcode('1324354657687\0','EAN13',64,2,'','') OBS! the '\0'. I'm also confused by "BARCODE_FONT_A  = '\x1d\x66\x00' # Barcode font"  In the Zjiang manual it is described as 'GS f n' and f is not x66. But the Zjiang is a topographical disaster with many errors!

**Comment by patkan** [comment]
You are right. Function type A detects the end of the code with a NUL. Function type B via a supplied length.
So, @DavisGoglin: could you maybe add this to #98 while you're at it? I think we only habe to add a `\x00` in A-mode.

**Comment by patkan** [comment]
OK, I suspect this should be fixed in #98. If no one opposes I will close this issue at the latest after merging into master.

**Comment by bondzo** [comment]
I have this printer [http://www.amazon.de/gp/product/B00LUIST7W/ref=ask_ql_qh_dp_hza](url)
which is also Zjiang ZJ-5890T, ID 0416:5011
Everything works except barcode. I tried both master and development branch. The description says that JAN13 (EAN 13) / JAN8 (EAN8) / CODE39 is supported. The programmer manual even says that all usual barcode types and function type A and B are supported.
I tested the demo-code on #98.
This is what it looks like:
![barcode](https://cloud.githubusercontent.com/assets/19343673/15244521/d39666f0-1901-11e6-8985-84935712e142.jpg)
Looks like something is wrong.

**Comment by patkan** [comment]
Hi @bondzo, the Text with a leading @ should go into a Barcode. So it looks like there is a fault somewhere.
Have you already tried to construct a raw control sequence from the manual and pass it directly to the printer with `_raw()`?

**Comment by bondzo** [comment]
Yes, I tried several _raw sequences - no success.
Thanks for pointing out the barcode.bin file. Not a single barcode is printed. I tried both p.Usb(...) and p.File(/dev/usb/lp0) - same result. The programming manual looks equal.
I'm not dependent on bar codes. Just wanted to fix this. I'll tell you as soon as I found out.

**Comment by patkan** [comment]
Thank you for testing this! It seems to me that these printers do something very different or simply can't print barcodes :-(
A last resort for someone who really needs that feature could be creating pictures and printing them.

**Comment by mike42** [comment]
Based on my own tests on this printer, I can basically confirm the above: the ZJ5890T does not speak standard ESC/POS, despite what the manual says. It's likely to be software-based rendering or no-barcodes on this model I'm afraid.

Screen capture below of the PDF shipped with the printer.

---
![image](https://cloud.githubusercontent.com/assets/2080552/15423842/b9fc90a4-1ec2-11e6-8ffe-55997cd48152.png)
---

**Comment by mike42** [comment]
I've tried using the [pyBarcode library](https://pypi.python.org/pypi/pyBarcode/0.7) to generate barcode images for python-escpos

Printing "1234" in CODE39 showed a few bugs and missing features. Most of it's in the bug tracker, see [bitbucket](https://bitbucket.org/whitie/python-barcode).

### Example
Dependencies for this snippet:

```bash
pip install python-escpos pyBarcode
```

Hacky setup to get a PIL object out without writing to disk:

```python
import barcode
from barcode.writer import ImageWriter

def get_barcode_image(codetype, content):
    """
    Get a PIL image object from a given barcode type and content.
    
    Note that barcode.PROVIDED_BARCODES contains the list of
    valid barcode types.
    """
    barcode_class=barcode.get_barcode_class(codetype)
    my_code=barcode_class(content, writer=ImageWriter())
    my_code.write("/dev/null")
    return my_code.writer._image
```

The idea being that you could print it:

```python
from escpos.printer import File
a =  File("/dev/usb/lp0")
img = get_barcode_image("code39", "1234")
```

Unfortunately, no chance to set the size, and the output is buggy as anything. Debug time:

```python
img.save(open("aa.png", "wb"), format="png")
```

![aa](https://cloud.githubusercontent.com/assets/2080552/18787754/86802d66-81e7-11e6-8adc-dc9cf02390ac.png)

### Next up

In the absence of any other suggestions for getting barcodes on the ZJ5890, I think we can close this issue off.

For anyone dealing with a printer which does not support `GS k` correctly, your choices are basically to try a different printer, or to take this snippet as a starting point, looking up issues in [the python-barcode issue tracker](https://bitbucket.org/whitie/python-barcode/issues?status=new&status=open) as you go.

**Comment by thijstriemstra** [comment]
@mike42, I tried your example with pyBarcode 0.8beta1 from their hg repository with a `USB Mini 58mm POS Thermal Dot Receipt Bill Printer POS Z-5890C` but nothing was printed (on `/dev/usb/lp1`). Is there anything missing from your example? Fortunately I don't need barcodes right now, but just fyi.

**Comment by mike42** [comment]
Please read the comment in detail: I'm pointing out that the generated barcode is un-usable!

In any case, edited the comment above, I forgot to include the call to `image()` that actually does the printing.

**Comment by thijstriemstra** [comment]
Thanks for the feedback. There's also a cups filter for this printer it seems (https://github.com/klirichek/zj-58) and during my tests it printed images/text. Haven't checked barcodes yet.

**Comment by thijstriemstra** [comment]
Thanks @mike42, with your new code it printed the barcode in your image (the 1234 was also printed, i just ripped didn't rip the paper correctly):

![barcode](https://cloud.githubusercontent.com/assets/305679/19494702/acccb082-9580-11e6-972e-72736f071b02.png)

That means it's working right?

**Comment by mike42** [comment]
Get a copy of [zxing/zxing](https://github.com/zxing/zxing) for Android to test this.

Very few of the barcodes I generated could be scanned correctly. If you see those sorts of bugs, they should be replicated with a snippet that does not use `python-escpos` (write them to an image), and posted upstream to the pBarcode project.

I am also aware of the CUPS filter. The CUPS print pipeline makes an image out of an entire page for the filter to convert, so if you can print text/images, and you have barcodes in a HTML or PDF document, this may work for you.

**Comment by thijstriemstra** [comment]
I see. I've ordered a [USB Laser Barcode Scanner X-9100](http://www.ebay.com/itm/-/121957825521?roken=cUgayN&soutkn=r4hZup) and will report back whether it can scan this barcode or not.

**Comment by MicroJoe** [comment]
I have the same printer and was able to print legible bar codes using pyBarcode (last beta has code128). Beware that if the barcode is too long in length the printer with roll and roll a lot of paper. An image-too-large exception should be implemented too in order to not waste paper.

I propose a feature to add barcode software rendering in order to fix this problem. The issue should be created appart and this issue closed for simpler identification for contributors.

**Comment by patkan** [comment]
Thank you for the feedback. So the actual issue seems to be non-fixable.
See #218 for a follow-up.
