### ISSUE TITLE
Text size not working (width and height)

### ISSUE THREAD

**Issue by PonnyTheLight** [python-escpos/python-escpos#592]
### Bug description
I used python-escpos before and all the code working perfectly, but a few days ago, all sizes not work. I dont know why but the text align work, but then the width and height not work in the same line. Any one can help me?

### Steps to reproduce
* Install python-escpos 2.2.0 and then connect to the printer with Network().
* Then use the printer has connusar and try the code below.

```python
    if connusar:
            if productsinc.exists():
                connusar.set(width=2, height=2, align='center')
                connusar.text(f"--= NUEVO PEDIDO =--\n\n{mesa.name}\n\n")
                connusar.set(align=u'center', width=1, height=1)
                connusar.text(f"Pedido Por: {userm.username}\n")
                connusar.set(align=u'center', width=2, height=2)
                connusar.text("\n ----------------\n\n")
                for product in productsinc:
                    if product.bolas != 0:
                        connusar.set(align=u'left', height=2)
                        connusar.text(f"{product.num}x {product.name.upper()}\n")
                        if product.formato == "1":
                            connusar.text(f"  * EN TARRINA {product.bolas} BOLAS\n")
                        elif product.formato == "2":
                             connusar.text(f"  * EN COPA {product.bolas} BOLAS\n")
                        elif product.formato == "3":
                             connusar.text(f"  * EN CUCURUCHO {product.bolas} BOLAS\n")
                        for add in product.adds.all():
                            connusar.text(f"  + {add.name.upper()}\n")
                        for sabor in product.sabores.all():
                            connusar.text(f"  - {sabor.namei.upper()}\n")
                        connusar.text("\n")
                    else:
                        connusar.set(align=u'left', width=2, height=2)
                        connusar.text(f"{product.num}x {product.name.upper()}\n")
                        for sina in product.sins.all():
                            connusar.text(f"  - {sina.name.upper()}\n")
                        for add in product.adds.all():
                            connusar.text(f"  + {add.name.upper()}\n")
                        connusar.text("\n")
                connusar.set(align=u'center', width=2, height=2)
                connusar.text("\n\n ----------------")
                connusar.cut()`
```

All align variables, working, but all width and height variables not working..

### Device info
 **Printer:** I dont know sorry
**OS:** Windows 11

**Comment by patkan** [comment]
Hi @PonnyTheLight,
could you please provide the information requested in the issue template?
on which OS are you? From which to which python-escpos version did you change?

**Comment by PonnyTheLight** [comment]
> Hi @PonnyTheLight, could you please provide the information requested in the issue template? on which OS are you? From which to which python-escpos version did you change?

Hello @patkan 
Im using Windows 11 and Network() to connect to the printer. I changed from 2.0.0 to 2.2.0, I've been looking at it and in principle in both versions it is the same, so it should work exactly the same and send that request to the printer well.

**Comment by PonnyTheLight** [comment]
up

**Comment by Framelony** [comment]
up
I  downgraded to 3.0a9 and it works

**Comment by patkan** [comment]
Great to hear, does it also work with v3.0?

**Comment by Framelony** [comment]
> Great to hear, does it also work with v3.0?

nope, it is the 3.0 release that is broken

**Comment by patkan** [comment]
> > Great to hear, does it also work with v3.0?
> 
> nope, it is the 3.0 release that is broken

And in which way for which printer?

I have checked the diff between 3.0a9 and 3.0 and I cannot see that there should be any change for the size parameters of set? https://github.com/python-escpos/python-escpos/compare/v3.0a9...v3.0. The only thing that has changed is the behavior whether default values for the unspecified parameters are transmitted, but that (based on the code above) should not affect the output. Some more input would be helpful please.

**Comment by gcervifi** [comment]
I had the same problem, 3.08a was working and 3.1 did not.
Set the parameter custom_size=True to enable a custom width and size in set function.

:param double_height: doubles the height of the text
:param double_width: doubles the width of the text
:param custom_size: uses custom size specified by width and height
parameters. Cannot be used with double_width or double_height.

**Comment by belono** [comment]
Hi @gcervifi and thanks for the tip :wink: 

It seems like we should clarify in the documentation the requirement of `custom_size=True` when setting custom width and height.
