### ISSUE TITLE
Image printing prints only garbage

### ISSUE THREAD

**Issue by tuxmaster5000** [python-escpos/python-escpos#598]
I have:
- [X ] searched open and closed issues for duplicates

### Bug description
Instant of the graphics only control char's are printed.

### Steps to reproduce
Call this sample code:
import escpos.printer
p = escpos.printer.File("/dev/usb/lp0", profile="TM-U220")
p.image("/tmp/QR_deWP.svg.png",impl="bitImageColumn")

### Device info
 **Printer:**  Epson TM-U220B

 **python-escpos version:** 2.0.0

 **python version:**  3.11.6

 **operating system:** Fedora-38
![QR_deWP svg](https://github.com/python-escpos/python-escpos/assets/837503/02c170a5-71ed-4897-ab71-807c70914f7b)

**Comment by tuxmaster5000** [comment]
The result is the same.
the qr and the image function prints only garbage.
Using the cups filter from epson an print the png file via:
`lpr -P Epson /tmp/QR_deWP.svg.png`
will work. So the printer itself will be ok.

**Comment by patkan** [comment]
Thank you! Since you are forcing the implementation to bitImageColumn, are you sure that a) your printer supports that implementation and b) that is the same implementation used by the cups driver. (Maybe try to get a dump of the raw data stream)

Have you tried the other implementations? If yes, the next step would be that we have a look at the actual output. (To see if there is an implementation issue)

**Comment by tuxmaster5000** [comment]
In the device list, the printer is listed as support bitImageColumn only.
For the cups driver you can take a look in the C source code.:
https://download.ebz.epson.net/dsc/du/02/DriverDownloadInfo.do?LG2=EN&CN2=US
&CTI=205&PRN=Software&OSC=LX
The "tmx-cups-src-ImpactReceipt-3.0.0.0.tar.gz" will contain all code.
Set the impl to bitImageRaster or graphics, will also result in garbage code.

**Comment by belono** [comment]
Hi @tuxmaster5000 !

What is the output when using the qr() method?

```python
import escpos.printer
p = escpos.printer.File("/dev/usb/lp0", profile="TM-U220")
p.qr("https://de.wikipedia.org" , native="false", impl="bitImageColumn")
```

**Comment by tuxmaster5000** [comment]
@belono it will result in:
"1A21C1E01P0https://de.wikipedia.o"

**Comment by patkan** [comment]
Could you please try the same with the Dummy printer and then give us the content of Dummy.output?

**Comment by tuxmaster5000** [comment]
```
p = escpos.printer.Dummy(profile="TM-U220")
p.qr("https://de.wikipedia.org" , native="false", impl="bitImageColumn")
print(p.output)
```
Will result in:

> b'\x1d(k\x04\x001A2\x00\x1d(k\x03\x001C\x03\x1d(k\x03\x001E0\x1d(k\x1b\x001P0https://de.wikipedia.org\x1d(k\x03\x001Q0'

**Comment by belono** [comment]
@tuxmaster5000
Please, try setting the `high_density_vertical` param to `false` in the image method:`

`p.image("/tmp/QR_deWP.svg.png", impl="bitImageColumn", high_density_vertical=false)`

**Comment by tuxmaster5000** [comment]
Now the printer prints an QR code, but it is complete miss formatted.
![WLAN1](https://github.com/python-escpos/python-escpos/assets/837503/c9debd50-e549-44fc-b8e2-371d0b83bd5b)

**Comment by tuxmaster5000** [comment]
Hi @belono, now the QR code will be quadratic, but don't fit on the paper.
I have added an sample using cups and python. The size can be bigger, this will not be an problem, as far the image will fit on the paper.
![WLAN1](https://github.com/python-escpos/python-escpos/assets/837503/2f56038d-5066-4a5f-ae0d-570dbb8cbf8c)

**Comment by belono** [comment]
@tuxmaster5000 
The oversize of the image should be due to the difference between the image dpi and the printer dpi resolution that we are not handling at the image method.
Maybe the `fragment_height` param can be of help, but if it is not, I think you should externally adjust the image size before issue the command.

@patkan 
The issue origin is that we are defaulting to high density = True for both horizontal and vertical parameters in the `image()` method that translates respectively to mode 32 and 33 of the `ESC *` command. Well, those modes are not supported by, at least, the TM-U220 and TM-U230 models as stated in the command reference (screenshot below), and is probably the cause of some opened issues like #508.

![Screenshot 2023-12-03 at 19-03-56 ESC - TM Printer - ESC_POS Command - Tech Reference - POS - Epson](https://github.com/python-escpos/python-escpos/assets/12175851/00351d3c-8fb6-48db-bedd-3529d1dfb4f6)

I think we should find a way to automatically switch to `high_density_horizontal=False`, `high_density_vertical=False` on the models that only support modes 0, 1. Maybe a capabilities field?

**Comment by tuxmaster5000** [comment]
@belono the image() call is only an workaround, because the qr() also fails.
Because I will print QR codes, an working qr() call will be the best option.

**Comment by belono** [comment]
> the image() call is only an workaround, because the qr() also fails

When the printing of qr codes is not supported natively by the printer as in the TM-U220 model there is the param `native=False` of the `qr()` method to render an image of the qr code and send it out to the printer through the `image()` method, but as the `image()` method defaults are incompatible with your printer, it ends up failing to print the image (qr code).
That's the reason why you, by the moment, have to workaround the qr code print out by externally generate the qr code image and send it manually to the printer through the `image()` method switching to the non default `high_density_horizontal=False, high_density_vertical=False` params to match your printer's capabilities.

> Because I will print QR codes, an working qr() call will be the best option.

By fixing the `image()` method to switch to those values automatically on printers that don't support the defaults would fix both the image and qr code outputs on those printers.
On a second stage we could look at the size mismatch and try to fix it.

It would be great if you could make some tests during the process. ;-)

**Comment by patkan** [comment]
@belono How about as a hotfix we allow a dict to be passed to qr() that will be used for the arguments of image() (explicitely set values through one of qr's image arguments should be overwritten and deprecated in the future?!).

In the long term an "automatic" setting based on capability would be great. Maybe we add a feature called `bit_image_column_high_density` or something?

**Comment by patkan** [comment]
Here you can find the current lib as of 5914c7c (this includes #600):
[pyescp3.1.dev6.zip](https://github.com/python-escpos/python-escpos/files/13540699/pyescp3.1.dev6.zip)

With this qr has a new argument image_arguments to which you can pass a dict with all arguments that should be passed to image().

**Comment by tuxmaster5000** [comment]
I have tried, an qr code will be printed, but it looks deformed. I think the with must be doubled or?
My code snip:
```
import escpos.printer
p = escpos.printer.File("/dev/usb/lp0", profile="TM-U220")
opt = {
        "impl": "bitImageColumn",
        "high_density_vertical": False,
        "center": True,
    }
p.qr("https://de.wikipedia.org" , native=False, image_arguments=opt)
```
And the result:
![WLAN1](https://github.com/python-escpos/python-escpos/assets/837503/af975a4d-bd22-4fa0-9c20-b17d0a019a96)

**Comment by tuxmaster5000** [comment]
And adding:
"high_density_horizontal": False,
will result in:
![wiki1](https://github.com/python-escpos/python-escpos/assets/837503/5756d8e4-ad14-4d54-b205-807494c3e85f)

**Comment by belono** [comment]
> Are there any new code that I can test?

Disable center?
```python
opt = {
        "impl": "bitImageColumn",
        "high_density_vertical": False,
        "high_density_horizontal": False,
        "center": False,
    }
p.qr("https://de.wikipedia.org", native=False, image_arguments=opt)

**Comment by tuxmaster5000** [comment]
Yes now it looks much better. So now the center option looks like broken to or?
![Pol1](https://github.com/python-escpos/python-escpos/assets/837503/ab02954f-c0d9-4007-9361-3d4bb65784f8)

**Comment by belono** [comment]
> So now the center option looks like broken to or?

It was my first thought but the centering code seems correct to me. :thinking: 
On the other hand image centering is calculated based on the media.width.pixel value of the TM-U220 capabilities profile which is set to 400px for a paper width of 76mm but the printer also supports 69.5mm or 57.5mm paper width with different number of pixels per line.
What is your paper size?

**Comment by tuxmaster5000** [comment]
I use the 76mm role, because it will be the default for it. In the original profile for the  TM-U220 80mm was noted, but this is wrong. For the TM-U220B profile I have correct it to 76mm. But it can be that also the other default values are wrong.

**Comment by belono** [comment]
Ok, I think we are getting closer.

According to page 24 of the printer's [technical reference](https://files.support.epson.com/pdf/pos/bulk/tm-u220_trg_en_std_reve.pdf) the maximum dots x line for 76mm paper width is 200. This is the value we have to supply at the `media.width.pixel` field in the TM-U220 profile.

You can force this value to be used by the printer's instance in order to test it beforehand:
```python

import escpos.printer

opt = {
        "impl": "bitImageColumn",
        "high_density_vertical": False,
        "high_density_horizontal": False,
        "center": True,
    }
p = escpos.printer.File("/dev/usb/lp0", profile="TM-U220B")
p.profile.profile_data["media"]["width"]["pixels"] = 200
p.qr("https://de.wikipedia.org", native=False, image_arguments=opt)
p.cut()
```
What is the output now? It should be centered.

**Comment by belono** [comment]
Great!!!

> Do have create an PR for it an the profile developers?

Yes, please do it.

Thank you for your fast feedback and testing.
I'm looking forward to that barcode issue. :wink:

**Comment by tuxmaster5000** [comment]
PR done:
https://github.com/receipt-print-hq/escpos-printer-db/pull/87

**Comment by belono** [comment]
Thank you!!
