### ISSUE TITLE
Font switching not working.

### ISSUE THREAD

**Issue by tuxmaster5000** [python-escpos/python-escpos#621]
I have:
- [X] searched open and closed issues for duplicates

### Bug description
Both lines are printed in the same font.

### Steps to reproduce
Sample Code:
```
with EscposIO(printer.File('...')) as x:
  x.set(align='center', bold=True, font='b')
  x.writelines("Foo",)
  x.set(align='left', bold=False, font='a')
  x.writelines("Bar")
```

### Device info
 **Printer:** Epson TM-. U220B
See: https://download4.epson.biz/sec_pubs/pos/reference_en/escpos/esc_cm.html
The device support two font's.

 **python-escpos version:** 3.1

 **python version:** 3.11.7

 **operating system:** Fedora-38

**Comment by Yanni8** [comment]
I had the same error when using Version `3.0`. 

It also works for me on version `3.1` but the alternative would be to use version `2.2`

**Comment by tuxmaster5000** [comment]
Yes you have right. I have created an new sample. The differences between both fonts are very small. So I have overseen it. :(
Code:
```
from escpos.escpos import EscposIO
from escpos import printer

with EscposIO(printer.File("<Path>", profile="TM-U220B")) as x:
     x.set(align='left', font='b')
     x.writelines("FOOfoo",)
     x.set(align='left', font='a')
     x.writelines("FOOfoo")
```
Result:
![Rätsel2](https://github.com/python-escpos/python-escpos/assets/837503/30809409-3387-409f-82ba-85ef7f6f4c25)
Sorry for the unpleasantries.

**Comment by belono** [comment]
Great!

The `set()` method was refactored by @patkan in #547 and it looked to be fine with the `EscposIO()` context manager. Is nice to know it works well.

Thank you @tuxmaster5000 and @Yanni8 !!!
