### ISSUE TITLE
Max Theoretical Image Size

### ISSUE THREAD

**Issue by taylorstevens** [python-escpos/python-escpos#65]
Now that we have the ability to print images larger than 255px long (thanks guys!) I went for the gusto and tried printing an image sized 512x4483, weighing in at 344kb. Needless to say after a long wait the image didn't print and all I got was garbage. So, what is the theoretical max on printed image size? I'm using a TM-T88V if that helps. Thanks again,
- Taylor

**Comment by taylorstevens** [comment]
I've done some preliminary tests, and it looks like the max image length for this library is somewhere between 2300-2400 pixels, with 2400 pixels throwing an error.

**Comment by manpaz** [comment]
To be honest, I haven't pushed my printer to the limits, but my guess is that the size is going to be very dependent of the model. I'll take a look a the ESC/POS documentation to see what can I find.

**Comment by matiasw** [comment]
Yeah; there just might be some limit built-in to the lib but there  most certainly are limits dependent on your printer. Eg. my cheap-o printer has a buffer size of 64kB.

**Comment by mike42** [comment]
Hey, observed the same issue on a TM-T20II with [escpos-php](https://github.com/mike42/escpos-php). My work-around is to pre-process the image into sections and print them one-at-a-time. There is usually no gap if the sections have heights that have round numbers (divisible by 8), but sometimes a thin line is visible between the tiles.

Easiest driver-side fix is to allow the RECV buffer to be set, and issue the image as *n* print commands small enough to fit in the buffer (in escpos-php, such a value would sit in a per-model profile)

**Comment by patkan** [comment]
I have set up a small fix in #152. This should probably do the trick. What do you think?

**Comment by patkan** [comment]
I think this should be fixed now.
Feel free to reopen or comment if any issues arise.
