### ISSUE TITLE
Transfer to organization?

### ISSUE THREAD

**Issue by patkan** [python-escpos/python-escpos#71]
Hi,
I just recently saw that there seem to be several active forks of this project in different repos.
@manpaz what do you think of transferring this repository into an github-organization? This would allow several people to work in a team on one repository, thus saving the hassle of keeping track of the different versions out there.
If you were willing to do this, I would set up the organization, invite you to it and assign you admin access.
Moreover I would ask e.g. @braveheuel and the recent contributors whether they would want to be part of this organization.

Best regards,
Patrick Kanzler

**Comment by manpaz** [comment]
@patkan,

As I always say to everyone helping out, thank you for your interest in the project. Frankly speaking, I should admit that the idea of the project was purely as a hubby, and never expected to have so much feedback.

I used to visit the project from time to time, to make some changes here and there, but when the Raspberry PI started to spread more and more people started to use this project to have their printers attached to their RPIs.

I do really appreciate your offer, and to be fair with the community of user's binding their projects around this repo, as long as the project stays as "open source", think I have to accept your proposal, so, if you are willing to do so, please, go ahead and setup an organization and I'll do the transfer once you are done.

Once again, thank you for your help and support to this project.

**Comment by patkan** [comment]
Cool, thank you for being so forthcoming.
I will write you again once the organization is set up.

**Comment by patkan** [comment]
Hi @manpaz,
the organization is up: @python-escpos. You should have an invite for joining it.
So if you want to, you could transfer it now.

**Comment by patkan** [comment]
@manpaz Thank you and merry Christmas ;)

**Comment by manpaz** [comment]
@patkan your very welcome, and Merry Christmas for you as well!
