### ISSUE TITLE
Collect forks

### ISSUE THREAD

**Issue by patkan** [python-escpos/python-escpos#72]
This project has several forks.
The aim is to collect all forks that are useful and to apply those changes to this repository.
Some forks are:
* [x] @noio and forks
* [x] @braveheuel
* [x] @eddiehung 
* [x] @buildrevision
* [x]  @mosquito and its forks ("blocks" #82)
* [x]  https://github.com/benoitguigal/python-epson-printer
* [x]  https://github.com/jbittencourt/python-escpos
* [x]  clean up image printing (the current version is partially broken and has multiple methods for the same tasks) 

EDIT: the buildrevision fork introduces the idea of a buffer for USB. This should be, if needed, reimplemented in the abstract base class.

EDIT: the eddiehung fork contains mostly hacky stuff and an implementation for a single printer. In the long run this probably should be included, but better not now.

EDIT: the braveheuel-fork is now in development-branch.

EDIT the noio-fork is now a PR. For unincluded commits issues have been created.

**Comment by noio** [comment]
Do you have a workflow for this? I'll help out any way I can.

My main addition was creating a method that can automatically print larger images "line-by-line"; most of it is in this commit: https://github.com/noio/python-escpos/commit/b4f8de002ccc8e87c0233378496303514697f40f

**Comment by patkan** [comment]
I am still thinking of the best way to do this. Do you have an idea?
In general, creating a fork and then a pull request would make a start. I quite like the idea of [this article](http://nvie.com/posts/a-successful-git-branching-model/). However, I don't think we need to zealously adhere to it.

**Comment by noio** [comment]
Yeah it might be a bit heavyweight for the amount of contributions, but it never hurts to be structured.

I did just realize that my copy is not a real fork (on Github) and that I created a bit of a jungle (with additional forks) by copying over the code from Google. :)

But honestly, we could just copy over my main contribution to a pull request on this repo (if you're interested in the image printing..). There really isn't much need for _all_ my edits to be preserved. I think most of them are ad-hoc fixes to stuff I encountered in a specific project.

**Comment by patkan** [comment]
As I see it, your function is an addition to the functionality of the software, so why not :-)
The easiest would probably be, if you could fork the repository and then apply all changes that you think make sense.
If you want to you can directly create the Pull Request, otherwise I could do this.

**Comment by noio** [comment]
Actually, after doing some research, I think it's possible to merge two repos even if one is not a fork of the other ([source](http://blog.caplin.com/2013/09/18/merging-two-git-repositories/)). This is probably the easiest solution. If you merge in the repo at @ztane's or @DavisGoglin's latest commits, you'll have all their functionality (QR codes, python3 compatibility, faster image printing).

**Comment by DavisGoglin** [comment]
I think I started with the original Google code and merged in @noio's, but I couldn't tell you why. I'll try to help clean up this mess and try to figure out how to merge my changes in.

**Comment by patkan** [comment]
I think I merged all changes by @ztane and @DavisGoglin and consequently all other contributors in this fork together in [python-escpos/python-escpos-1](https://github.com/python-escpos/python-escpos-1).
I think the next step would be to bring this fork to a development branch in the main repository (which is not a simple merge since some things changed heavily) where it will gradually be merged with the other forks. Once this branch gets stable it will be merged into master.

**Comment by mosquito** [comment]
I try to merge my codebase with this codebase. I will create the pull request soon. Next week probably.

**Comment by patkan** [comment]
OK, thank you! 
Some features have evolved differently across the forks so maybe we will have to see how to solve collisions.
