### ISSUE TITLE
Release on PyPI

### ISSUE THREAD

**Issue by cedk** [python-escpos/python-escpos#82]
It will be great if release where also published on PyPI.

**Comment by patkan** [comment]
Yeah that would be great and I plan to do this in the long run. However, I still have to contact the maintainer of python-escpos on PyPI. I will get in touch with him and see what can be done.

**Comment by patkan** [comment]
OK, I am now maintainer of the package on PyPi.
I promised the original maintainer to ensure compatibility with his fork, so a PyPi release will come once we have the current development-branch ready.

**Comment by patkan** [comment]
We should release a source and wheel.

**Comment by patkan** [comment]
Release is out.
