### ISSUE TITLE
python-escpos does not support all barcode types as per esc/pos specification

### ISSUE THREAD

**Issue by Loafdude** [python-escpos/python-escpos#85]
Just a heads up some newer printers support more barcode types.
Please see epson's esc/pos reference page here
https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=128
Sorry I believe it requires registration to access their website.

Specifically 
CODE93
CODE128
GS1-128
GS1 DataBar Omnidirectional
GS1 DataBar Truncated
GS1 DataBar Limited
GS1 DataBar Expanded

**Comment by patkan** [comment]
Yeah you're right. At the moment we are pulling together all the forks out there so there might be large changes in the code which is somewhat unfortunate for Pull Requests, but if you want to you can contribute.
In the long run I would be happy if we could set up something that allows for older printers to emulate those new barcode types by prerendering the barcodes. Maybe we could pass the barcode function simply a flag whether it should send directly to the printer or pre-render.
