### ISSUE TITLE
White/black reverse print mode

### ISSUE THREAD

**Issue by clarkewing** [python-escpos/python-escpos#95]
Just wondering if it would be feasible to implement the possibility of using the white/black reverse print mode as an option in the 'set' method?

**Comment by patkan** [comment]
Please have a look at the set-method in `development`-branch. @loafdude implemented there the color reverse. You can access it with the key `invert=True`.
Is this what you are searching for?

**Comment by patkan** [comment]
The mentioned commit is 7c98de672786064bd90db6b76084a145613c16cc.

**Comment by clarkewing** [comment]
Thanks!
