### ISSUE TITLE
improve set-method

### ISSUE THREAD

**Issue by patkan** [python-escpos/python-escpos#96]
Improve the set-method just like in e1960c896527f3c6b201ba46045bb769bb5293f0.
(This would then change the behaviour of the class, but also makes it better testable.)

**Comment by MicroJoe** [comment]
See PR #216 for a WIP of this issue.

**Comment by patkan** [comment]
Sorry, this has not been linked, but is also relevant #176. (And also sorry for the very short description of the issue)

**Comment by MicroJoe** [comment]
Should we close this?

I know someone wanted a method like set but without reseting everything for efficiency, but this need should be expressed clearly in another issue IMO.

**Comment by patkan** [comment]
You are right, this is just undefined. I'm gonna create a new issue.
