### ISSUE TITLE
charcode() and parameters are missing from documentation 

### ISSUE THREAD

**Issue by bmjbmj** [python-escpos/python-escpos#99]
This is definitely not essential but charcode() and parameters are missing from documentation at 
http://python-escpos.readthedocs.org/en/latest/user/methods.html ;-)

Moreover, thanks for all the work you put into the code! It has saved me many hours!

**Comment by patkan** [comment]
You are welcome (I think we can thank everyone that contributes to this project.)

That's right and it has to be fixed. Best when someone is at #92.
For now, please have a look at http://python-escpos.readthedocs.org/en/development/api/escpos.html
It is auto-generated and the docstring for charcode() is not that descriptive (and the charcodes are missing), but it's a start.

**Comment by patkan** [comment]
fixed with e595bc21508505fff4566c094f759fa928fcc6f8
